"""Bharat-grounded seed dataset for ValueWeave Idea Library.

Mix:
 - 40% Local Physical Businesses (12)
 - 30% Hybrid Tech + Local (9)
 - 20% Pure Digital (6)
 - 10% Future Economy (3)
Total: 30 curated ideas spanning ~12 sectors.
"""

IDEAS_SEED = [
    # -------------------- LOCAL PHYSICAL (12) --------------------
    {
        "slug": "soil-testing-micro-lab",
        "title": "Soil Testing Micro Lab",
        "short_description": "Affordable soil-health testing for nearby farmers with 24-hour reports and crop-wise advisory.",
        "detailed_description": "Set up a small lab in a mandal or tehsil town that tests soil samples for NPK, micronutrients, pH and EC. Partner with FPOs, krishi seva kendras and progressive farmers. Issue digital reports in Telugu/English with crop-specific input recommendations.",
        "sector": "AgriTech",
        "tags": ["agriculture", "rural", "soil", "advisory", "bharat"],
        "problem_solved": "Most small farmers blindly apply fertilizers, hurting yields and margins. Affordable district-level soil testing is rare.",
        "target_customers": "Smallholder farmers, FPOs, agri input dealers, horticulture growers",
        "beginner_friendly": True,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 150000,
        "medium_scale_investment": 500000,
        "advanced_scale_investment": 1500000,
        "estimated_monthly_revenue_min": 40000,
        "estimated_monthly_revenue_max": 180000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Agrarian", "Semi-Urban", "Rural"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 4,
        "team_roles_needed": ["Lab Technician", "Field Coordinator", "Agronomist Advisor"],
        "skills_required": ["Basic Chemistry", "Field Sampling", "Telugu/Local Language", "Excel/Reporting"],
        "contribution_types_needed": ["Capital", "Local Network", "Field Operations"],
        "ideal_for": ["Rural Youth", "First-Time Entrepreneurs", "Small Teams"],
        "eligible_government_schemes": ["PMKSY", "RKVY", "Soil Health Card Scheme"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": True,
        "trending_score": 88,
        "save_count": 142,
        "team_interest_count": 28,
    },
    {
        "slug": "ro-water-service",
        "title": "Community RO Water Service",
        "short_description": "Hyperlocal 20L RO water cans delivered to homes, shops and schools on subscription.",
        "detailed_description": "Install a 500-1000 LPH RO plant in a town with ground water issues. Sell branded 20L cans on daily/alternate-day routes. Add tiffin-style subscription billing and WhatsApp ordering.",
        "sector": "Local Services",
        "tags": ["water", "subscription", "delivery", "essential"],
        "problem_solved": "Hard or contaminated water is a daily headache in semi-urban Bharat; bottled water is too expensive for routine use.",
        "target_customers": "Households, tea stalls, small offices, schools, clinics",
        "beginner_friendly": True,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 250000,
        "medium_scale_investment": 800000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 300000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Semi-Urban", "Tier-3 City", "Town"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 5,
        "team_roles_needed": ["Plant Operator", "Delivery Driver", "Route Manager"],
        "skills_required": ["Plant Maintenance", "Driving", "Local Sales", "Route Planning"],
        "contribution_types_needed": ["Capital", "Operations", "Local Sales"],
        "ideal_for": ["First-Time Entrepreneurs", "Rural Youth", "Small Teams"],
        "eligible_government_schemes": ["PMEGP", "Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 72,
        "save_count": 96,
        "team_interest_count": 17,
    },
    {
        "slug": "solar-installation-service",
        "title": "Rooftop Solar Installation Service",
        "short_description": "Turn-key rooftop solar for homes, schools and small shops in your district.",
        "detailed_description": "Become a registered channel partner for solar OEMs. Handle site survey, DISCOM paperwork, installation, net metering and 5-year AMC. Stack with PM Surya Ghar subsidies.",
        "sector": "Clean Energy",
        "tags": ["solar", "energy", "rooftop", "green", "subsidy"],
        "problem_solved": "Households want lower power bills and reliable backup but find solar paperwork and trustworthy installers hard to access locally.",
        "target_customers": "Homeowners, schools, small factories, clinics",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 300000,
        "medium_scale_investment": 1200000,
        "advanced_scale_investment": 5000000,
        "estimated_monthly_revenue_min": 80000,
        "estimated_monthly_revenue_max": 600000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Urban", "Semi-Urban", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Electrician", "Sales Lead", "DISCOM Liaison", "Site Engineer"],
        "skills_required": ["Electrical Wiring", "Site Survey", "Sales", "Subsidy Paperwork"],
        "contribution_types_needed": ["Capital", "Technical Skills", "Local Network"],
        "ideal_for": ["Skilled Workers", "Small Teams", "Working Professionals"],
        "eligible_government_schemes": ["PM Surya Ghar", "MNRE Subsidy", "Mudra Loan"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "Medium",
        "featured": True,
        "trending_score": 94,
        "save_count": 210,
        "team_interest_count": 41,
    },
    {
        "slug": "mobile-repair-network",
        "title": "Neighbourhood Mobile Repair Network",
        "short_description": "Branded smartphone repair shops with same-day service, transparent pricing and warranty.",
        "detailed_description": "Run a chain of 2-5 small repair counters across a town. Standardise pricing, parts sourcing and a basic POS app. Add doorstep pickup via WhatsApp.",
        "sector": "Local Services",
        "tags": ["mobile", "repair", "retail", "warranty"],
        "problem_solved": "Customers don't trust unbranded repair shops; pricing is opaque and quality inconsistent.",
        "target_customers": "Students, working professionals, shopkeepers",
        "beginner_friendly": True,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 100000,
        "medium_scale_investment": 400000,
        "advanced_scale_investment": 1200000,
        "estimated_monthly_revenue_min": 35000,
        "estimated_monthly_revenue_max": 200000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Urban", "Semi-Urban", "Town"],
        "district_demand_level": "High",
        "competition_level": "High",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 7,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Repair Technician", "Counter Sales", "Parts Sourcer"],
        "skills_required": ["Soldering", "Diagnostics", "Customer Service"],
        "contribution_types_needed": ["Capital", "Technical Skills", "Operations"],
        "ideal_for": ["Skilled Workers", "Students", "First-Time Entrepreneurs"],
        "eligible_government_schemes": ["PMEGP", "Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 65,
        "save_count": 78,
        "team_interest_count": 11,
    },
    {
        "slug": "dairy-collection-center",
        "title": "Village Dairy Collection Center",
        "short_description": "Daily milk procurement, fat-testing and cold-chain handoff to dairies — fairer pricing for farmers.",
        "detailed_description": "Set up a chilling-equipped collection center serving 3-5 villages. Test milk quality, pay farmers digitally same-day, and supply to a major dairy or directly to retailers.",
        "sector": "AgriTech",
        "tags": ["dairy", "rural", "cold-chain", "fpc"],
        "problem_solved": "Dairy farmers often face delayed payments, unfair fat readings and middleman cuts.",
        "target_customers": "Smallholder dairy farmers, urban dairies, restaurants",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 400000,
        "medium_scale_investment": 1500000,
        "advanced_scale_investment": 5000000,
        "estimated_monthly_revenue_min": 90000,
        "estimated_monthly_revenue_max": 450000,
        "risk_level": "Medium",
        "scalability_level": "Medium",
        "suitable_district_types": ["Rural", "Agrarian"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Center Manager", "Quality Tester", "Logistics Coordinator"],
        "skills_required": ["Milk Testing", "Cold-chain Handling", "Local Trust", "Bookkeeping"],
        "contribution_types_needed": ["Capital", "Local Network", "Operations"],
        "ideal_for": ["Rural Youth", "Local Shop Owners", "Small Teams"],
        "eligible_government_schemes": ["NPDD", "Dairy Entrepreneurship Development Scheme"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 70,
        "save_count": 88,
        "team_interest_count": 19,
    },
    {
        "slug": "food-processing-unit",
        "title": "Small Food Processing Unit",
        "short_description": "Process locally abundant produce — millets, mangoes, chillies — into branded retail-ready packs.",
        "detailed_description": "Identify one high-volume local crop. Set up cleaning, drying, milling and packaging for retail. Sell via kirana stores, FPOs and online D2C in a 200km radius.",
        "sector": "Food & FMCG",
        "tags": ["processing", "millets", "fmcg", "rural"],
        "problem_solved": "Farmers sell raw produce at low margins while consumers pay a premium for branded processed versions; the value chain is empty locally.",
        "target_customers": "Kirana stores, D2C consumers, restaurants, schools",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 500000,
        "medium_scale_investment": 2000000,
        "advanced_scale_investment": 8000000,
        "estimated_monthly_revenue_min": 100000,
        "estimated_monthly_revenue_max": 700000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Agrarian", "Semi-Urban"],
        "district_demand_level": "Medium",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 4,
        "ideal_team_size_max": 10,
        "team_roles_needed": ["Plant Supervisor", "Packaging Lead", "Sales/Distribution", "FSSAI Compliance"],
        "skills_required": ["Food Safety", "Packaging", "Branding", "Distribution"],
        "contribution_types_needed": ["Capital", "Operations", "Branding"],
        "ideal_for": ["Small Teams", "Women Entrepreneurs", "First-Time Entrepreneurs"],
        "eligible_government_schemes": ["PMFME", "PMEGP", "SFURTI"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "Medium",
        "featured": True,
        "trending_score": 82,
        "save_count": 165,
        "team_interest_count": 33,
    },
    {
        "slug": "tailoring-cluster",
        "title": "Women's Tailoring & Stitching Cluster",
        "short_description": "Organised tailoring cluster delivering school uniforms, B2B bulk orders and D2C ethnic wear.",
        "detailed_description": "Onboard 15-40 trained women tailors. Take bulk orders from schools, garment exporters, ecommerce labels. Pay per piece. Offer pickup/drop of materials in the colony.",
        "sector": "Textiles",
        "tags": ["women", "tailoring", "cluster", "manufacturing"],
        "problem_solved": "Skilled women tailors at home lack steady orders; bulk buyers can't find reliable distributed manufacturing.",
        "target_customers": "Schools, ecommerce labels, garment exporters, local boutiques",
        "beginner_friendly": True,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 150000,
        "medium_scale_investment": 600000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 400000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Semi-Urban", "Urban", "Town"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Cluster Coordinator", "Quality Checker", "B2B Sales Lead"],
        "skills_required": ["Tailoring", "QC", "Order Management", "Bulk Sales"],
        "contribution_types_needed": ["Working Capital", "Local Network", "Sales"],
        "ideal_for": ["Women Entrepreneurs", "Rural Youth", "Small Teams"],
        "eligible_government_schemes": ["NULM", "Mudra Loan", "DAY-NRLM"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": True,
        "trending_score": 78,
        "save_count": 132,
        "team_interest_count": 26,
    },
    {
        "slug": "local-delivery-fleet",
        "title": "Hyperlocal Delivery Fleet",
        "short_description": "EV-first 2-wheeler delivery fleet for restaurants, pharmacies and kirana D2C in your town.",
        "detailed_description": "Run a fleet of 5-25 riders serving local merchants. Build a basic dispatcher dashboard. Sell delivery as a per-order or subscription service to merchants.",
        "sector": "Logistics",
        "tags": ["delivery", "ev", "hyperlocal", "fleet"],
        "problem_solved": "Tier-3 merchants want delivery but can't justify Swiggy/Zomato commissions; aggregators don't go deep into towns.",
        "target_customers": "Restaurants, kirana stores, pharmacies, sweet shops",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 300000,
        "medium_scale_investment": 1000000,
        "advanced_scale_investment": 4000000,
        "estimated_monthly_revenue_min": 80000,
        "estimated_monthly_revenue_max": 500000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Tier-3 City", "Town", "Semi-Urban"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 6,
        "ideal_team_size_min": 4,
        "ideal_team_size_max": 15,
        "team_roles_needed": ["Fleet Manager", "Dispatcher", "Merchant Sales"],
        "skills_required": ["Operations", "Route Planning", "Sales", "Basic Tech"],
        "contribution_types_needed": ["Capital", "Operations", "Tech"],
        "ideal_for": ["Small Teams", "First-Time Entrepreneurs"],
        "eligible_government_schemes": ["PMEGP", "Mudra Loan", "FAME-II for EVs"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 73,
        "save_count": 102,
        "team_interest_count": 22,
    },
    {
        "slug": "agri-input-store",
        "title": "Agri Input & Advisory Store",
        "short_description": "Trusted agri input retail with bundled crop advisory, weather alerts and digital khata.",
        "detailed_description": "Stock fertilizers, seeds and bio-inputs. Differentiate with WhatsApp-based crop advisory, weather alerts, season planning and a digital ledger that helps farmers track expenses.",
        "sector": "AgriTech",
        "tags": ["agriculture", "retail", "advisory", "khata"],
        "problem_solved": "Farmers walk into agri stores blind; nobody tells them what to apply when, and credit recordkeeping is messy.",
        "target_customers": "Smallholder farmers, FPOs, horticulture growers",
        "beginner_friendly": True,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 200000,
        "medium_scale_investment": 700000,
        "advanced_scale_investment": 2000000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 250000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Rural", "Agrarian", "Semi-Urban"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 5,
        "team_roles_needed": ["Store Manager", "Agronomy Advisor", "Field Promoter"],
        "skills_required": ["Crop Knowledge", "Retail Ops", "Local Language", "WhatsApp Advisory"],
        "contribution_types_needed": ["Capital", "Local Network"],
        "ideal_for": ["Local Shop Owners", "Rural Youth", "First-Time Entrepreneurs"],
        "eligible_government_schemes": ["PMKSY", "Agri Infrastructure Fund"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 68,
        "save_count": 84,
        "team_interest_count": 13,
    },
    {
        "slug": "tiffin-meal-service",
        "title": "Healthy Tiffin Meal Service",
        "short_description": "Subscription home-style tiffins for hostels, working professionals and bachelors.",
        "detailed_description": "Set up a clean kitchen, plan weekly menus, deliver tiffins on subscription. Add millet/diabetic-friendly options for premium tier.",
        "sector": "Food & FMCG",
        "tags": ["tiffin", "food", "subscription", "women-led"],
        "problem_solved": "Hostelers and bachelors crave home-style food; existing options are oily, unhygienic or pricey.",
        "target_customers": "Students, working professionals, hostels, PG residents",
        "beginner_friendly": True,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 80000,
        "medium_scale_investment": 300000,
        "advanced_scale_investment": 1000000,
        "estimated_monthly_revenue_min": 40000,
        "estimated_monthly_revenue_max": 250000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Urban", "Semi-Urban", "College Town"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Head Cook", "Helper", "Delivery", "Sales/Subscription"],
        "skills_required": ["Cooking", "Hygiene", "Customer Service", "Route Planning"],
        "contribution_types_needed": ["Working Capital", "Operations"],
        "ideal_for": ["Women Entrepreneurs", "First-Time Entrepreneurs", "Small Teams"],
        "eligible_government_schemes": ["Mudra Loan", "NULM", "PMFME"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 75,
        "save_count": 118,
        "team_interest_count": 21,
    },
    {
        "slug": "two-wheeler-service-garage",
        "title": "Multi-Brand 2-Wheeler Service Garage",
        "short_description": "Honest, on-time bike servicing with digital job cards and pickup-drop in your town.",
        "detailed_description": "Open a modern multi-brand garage with transparent service menus, digital job cards on WhatsApp and pickup-drop for working customers.",
        "sector": "Automotive",
        "tags": ["automotive", "garage", "service", "trust"],
        "problem_solved": "Authorised service centres are slow and expensive; local garages lack trust and modern customer experience.",
        "target_customers": "Daily commuters, gig workers, fleet operators",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 200000,
        "medium_scale_investment": 800000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 350000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Urban", "Semi-Urban", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "High",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 7,
        "team_roles_needed": ["Lead Mechanic", "Helper Mechanic", "Front Desk/CRM"],
        "skills_required": ["Mechanic Skills", "Customer Service", "Basic Tech"],
        "contribution_types_needed": ["Capital", "Technical Skills", "Customer Experience"],
        "ideal_for": ["Skilled Workers", "Small Teams"],
        "eligible_government_schemes": ["PMEGP", "Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 62,
        "save_count": 71,
        "team_interest_count": 9,
    },
    {
        "slug": "cold-storage-rental",
        "title": "Small Cold Storage Rental",
        "short_description": "Modular cold rooms rented out to farmers, dairy and seafood traders.",
        "detailed_description": "Build 50-200 MT cold rooms near a market yard. Rent capacity by the pallet to fruit, vegetable and dairy traders. Add insurance and finance tie-ups.",
        "sector": "AgriTech",
        "tags": ["cold-storage", "supply-chain", "rental"],
        "problem_solved": "Farmers and small traders lose huge value to post-harvest spoilage because mandi-level cold rooms are scarce.",
        "target_customers": "Farmers, FPOs, fruit/vegetable traders, dairy aggregators",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 1500000,
        "medium_scale_investment": 5000000,
        "advanced_scale_investment": 15000000,
        "estimated_monthly_revenue_min": 120000,
        "estimated_monthly_revenue_max": 800000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Agrarian", "Mandi Towns"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Plant Engineer", "Operations Manager", "Sales/Liaison"],
        "skills_required": ["Refrigeration", "Operations", "Bulk Sales", "Compliance"],
        "contribution_types_needed": ["Large Capital", "Operations", "Local Network"],
        "ideal_for": ["Small Teams", "Working Professionals"],
        "eligible_government_schemes": ["Agri Infrastructure Fund", "PM Kisan SAMPADA Yojana"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "High",
        "featured": False,
        "trending_score": 80,
        "save_count": 96,
        "team_interest_count": 18,
    },

    # -------------------- HYBRID TECH + LOCAL (9) --------------------
    {
        "slug": "whatsapp-commerce-setup",
        "title": "WhatsApp Commerce Setup Service",
        "short_description": "Setup WhatsApp catalogs, payments and order workflows for local merchants — done-for-you.",
        "detailed_description": "Onboard kirana, boutiques, sweet shops and clinics onto WhatsApp Business with catalog, auto-replies, payment links, and order tracking. Charge setup + monthly retainer.",
        "sector": "MSME Digital",
        "tags": ["whatsapp", "ecommerce", "msme", "setup"],
        "problem_solved": "Local merchants want to sell online but Shopify/Amazon is overkill. WhatsApp Business is perfect but they don't know how.",
        "target_customers": "Kirana stores, boutiques, clinics, sweet shops, small D2C brands",
        "beginner_friendly": True,
        "execution_type": "Hybrid",
        "remote_possible": True,
        "minimum_investment": 30000,
        "medium_scale_investment": 150000,
        "advanced_scale_investment": 600000,
        "estimated_monthly_revenue_min": 40000,
        "estimated_monthly_revenue_max": 250000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Semi-Urban", "Urban", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 6,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 5,
        "team_roles_needed": ["Sales/Onboarding", "Tech Setup Specialist", "Customer Success"],
        "skills_required": ["WhatsApp Business API", "Sales", "Basic Design", "Customer Support"],
        "contribution_types_needed": ["Skills", "Local Network", "Tech"],
        "ideal_for": ["Students", "First-Time Entrepreneurs", "Working Professionals"],
        "eligible_government_schemes": ["Digital India MSME", "Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": True,
        "trending_score": 90,
        "save_count": 198,
        "team_interest_count": 47,
    },
    {
        "slug": "ai-content-studio",
        "title": "AI-Powered Content Studio",
        "short_description": "Reels, ads and brand content for local businesses — powered by AI tools with human editing.",
        "detailed_description": "Run a studio that produces short-form video, ads, voiceovers and product photography using AI tools. Sell monthly content packs to local D2C brands, real estate, restaurants.",
        "sector": "Creator Economy",
        "tags": ["ai", "content", "reels", "studio"],
        "problem_solved": "Local brands need daily content for Instagram, YouTube, ads — but agencies are expensive and freelancers are inconsistent.",
        "target_customers": "Local D2C brands, restaurants, real estate, coaching institutes",
        "beginner_friendly": True,
        "execution_type": "Hybrid",
        "remote_possible": True,
        "minimum_investment": 50000,
        "medium_scale_investment": 250000,
        "advanced_scale_investment": 1000000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 400000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Urban", "Tier-2 City", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "Low",
        "automation_resistance_score": 4,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["AI Tool Operator", "Video Editor", "Account Manager", "Scriptwriter"],
        "skills_required": ["AI Tools", "Video Editing", "Storyboarding", "Client Management"],
        "contribution_types_needed": ["Skills", "Equipment", "Sales"],
        "ideal_for": ["Students", "Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Startup India Seed Fund", "MSME Innovation Scheme"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": True,
        "trending_score": 96,
        "save_count": 245,
        "team_interest_count": 58,
    },
    {
        "slug": "local-business-digitalization",
        "title": "Local Business Digitalization Agency",
        "short_description": "Get nearby shops online — Google Business Profile, payments, billing, ads and reviews.",
        "detailed_description": "Offer a productised digitalization pack: GMB setup, UPI/QR, GST billing software, basic ads, review collection. Monthly retainer for ongoing optimisation.",
        "sector": "MSME Digital",
        "tags": ["digital", "gmb", "msme", "ads"],
        "problem_solved": "Local shops are invisible on Google and don't run any ads; they lose customers to better-marketed competitors.",
        "target_customers": "Restaurants, salons, clinics, retailers, coaching institutes",
        "beginner_friendly": True,
        "execution_type": "Hybrid",
        "remote_possible": True,
        "minimum_investment": 25000,
        "medium_scale_investment": 150000,
        "advanced_scale_investment": 500000,
        "estimated_monthly_revenue_min": 35000,
        "estimated_monthly_revenue_max": 200000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Urban", "Tier-2 City", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 5,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 5,
        "team_roles_needed": ["Sales Lead", "GMB/Ads Specialist", "Content Lead"],
        "skills_required": ["Google Ads", "GMB", "Sales", "Copywriting"],
        "contribution_types_needed": ["Skills", "Local Network"],
        "ideal_for": ["Students", "First-Time Entrepreneurs"],
        "eligible_government_schemes": ["Digital India MSME"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 84,
        "save_count": 152,
        "team_interest_count": 30,
    },
    {
        "slug": "hyperlocal-delivery-platform",
        "title": "Hyperlocal Multi-Merchant Platform",
        "short_description": "A district-level commerce app — order from any local shop, single delivery network.",
        "detailed_description": "Build a town-level commerce app that aggregates 50-500 local merchants (kirana, pharmacy, sweets, electronics). Run shared rider fleet. Earn commission + delivery fee.",
        "sector": "MSME Digital",
        "tags": ["hyperlocal", "marketplace", "delivery"],
        "problem_solved": "Big aggregators ignore Tier-3 towns; local merchants have no neutral marketplace.",
        "target_customers": "Households, hostels, small offices",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 500000,
        "medium_scale_investment": 2500000,
        "advanced_scale_investment": 10000000,
        "estimated_monthly_revenue_min": 80000,
        "estimated_monthly_revenue_max": 600000,
        "risk_level": "High",
        "scalability_level": "High",
        "suitable_district_types": ["Tier-3 City", "Tier-2 City", "Town"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 5,
        "ideal_team_size_min": 4,
        "ideal_team_size_max": 12,
        "team_roles_needed": ["Tech Lead", "Merchant Sales", "Fleet Lead", "Customer Support"],
        "skills_required": ["App Development", "Sales", "Operations", "Growth Marketing"],
        "contribution_types_needed": ["Capital", "Tech", "Operations"],
        "ideal_for": ["Small Teams", "Working Professionals"],
        "eligible_government_schemes": ["Startup India Seed Fund", "MSME Innovation"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "High",
        "featured": False,
        "trending_score": 79,
        "save_count": 138,
        "team_interest_count": 32,
    },
    {
        "slug": "rural-digital-services",
        "title": "Rural Digital Seva Center",
        "short_description": "One-stop digital seva — government forms, banking, exams, KYC, bookings — for villagers.",
        "detailed_description": "Become a CSC/VLE and add value-added services: e-shram, PM-Kisan applications, train/bus booking, mutual fund onboarding, exam form filling, mobile recharges.",
        "sector": "Govt & Citizen Services",
        "tags": ["csc", "vle", "rural", "egov"],
        "problem_solved": "Villagers can't navigate government portals; banks don't reach last mile; nearest service is 20+ km away.",
        "target_customers": "Rural households, farmers, students, senior citizens",
        "beginner_friendly": True,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 50000,
        "medium_scale_investment": 200000,
        "advanced_scale_investment": 600000,
        "estimated_monthly_revenue_min": 25000,
        "estimated_monthly_revenue_max": 150000,
        "risk_level": "Low",
        "scalability_level": "Medium",
        "suitable_district_types": ["Rural", "Agrarian", "Semi-Urban"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Stable",
        "ai_proof_level": "High",
        "automation_resistance_score": 7,
        "ideal_team_size_min": 1,
        "ideal_team_size_max": 3,
        "team_roles_needed": ["Center Operator", "Field Assistant"],
        "skills_required": ["Computer Operation", "Local Language", "Customer Service", "Forms Knowledge"],
        "contribution_types_needed": ["Capital", "Skills", "Trust"],
        "ideal_for": ["Rural Youth", "First-Time Entrepreneurs", "Local Shop Owners"],
        "eligible_government_schemes": ["CSC Scheme", "PMGDISHA", "Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 67,
        "save_count": 89,
        "team_interest_count": 14,
    },
    {
        "slug": "coaching-edtech-hybrid",
        "title": "Hybrid Coaching & EdTech Center",
        "short_description": "Local coaching center with online practice tests, doubt-solving and recorded lessons.",
        "detailed_description": "Run physical batches for competitive exams (SSC, EAMCET, JEE-foundation, banking) and bundle an app with mock tests, doubt chat and recorded videos. Subscription based.",
        "sector": "EdTech",
        "tags": ["coaching", "edtech", "exams"],
        "problem_solved": "Tier-3 students need both classroom rigor and 24x7 doubt-solving; pure-online courses don't suit them.",
        "target_customers": "Class 9-12 students, govt-exam aspirants, parents",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 150000,
        "medium_scale_investment": 600000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 400000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Semi-Urban", "Tier-3 City", "Town"],
        "district_demand_level": "High",
        "competition_level": "High",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 6,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Lead Faculty", "Subject Teachers", "Counsellor", "Admin"],
        "skills_required": ["Subject Mastery", "Teaching", "Operations", "Marketing"],
        "contribution_types_needed": ["Capital", "Teaching Skills", "Local Network"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Mudra Loan", "Skill India"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 76,
        "save_count": 110,
        "team_interest_count": 19,
    },
    {
        "slug": "fitness-wellness-studio",
        "title": "Neighbourhood Fitness & Yoga Studio",
        "short_description": "Mid-sized fitness + yoga studio with app-based booking, diet plans and group challenges.",
        "detailed_description": "Run a 1500-3000 sqft studio with strength, group classes and yoga. Add a simple booking app, attendance, diet plans, monthly challenges. Premium 'transformation packs'.",
        "sector": "Health & Wellness",
        "tags": ["fitness", "yoga", "wellness", "subscription"],
        "problem_solved": "Towns lack modern, hygienic, women-friendly fitness spaces with personalised guidance.",
        "target_customers": "Working professionals, homemakers, students, senior citizens",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 400000,
        "medium_scale_investment": 1500000,
        "advanced_scale_investment": 5000000,
        "estimated_monthly_revenue_min": 100000,
        "estimated_monthly_revenue_max": 500000,
        "risk_level": "Medium",
        "scalability_level": "Medium",
        "suitable_district_types": ["Urban", "Tier-2 City", "Tier-3 City"],
        "district_demand_level": "High",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Head Trainer", "Yoga Instructor", "Front Desk", "Nutritionist"],
        "skills_required": ["Fitness Certification", "Yoga", "Customer Service", "Marketing"],
        "contribution_types_needed": ["Capital", "Skills", "Operations"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Mudra Loan", "Stand-Up India"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 71,
        "save_count": 93,
        "team_interest_count": 16,
    },
    {
        "slug": "real-estate-discovery-platform",
        "title": "Local Real Estate Discovery Service",
        "short_description": "Verified rental and resale property listings for your town — with site visits and paperwork help.",
        "detailed_description": "Run a hyperlocal property service: walk inventory, shoot proper photos/videos, verify owner KYC, list on your site + WhatsApp + Instagram, handle paperwork. Brokerage + paid promotions.",
        "sector": "Real Estate",
        "tags": ["real-estate", "local", "verified", "listings"],
        "problem_solved": "Local real estate is chaotic — unverified listings, fake photos, opaque pricing.",
        "target_customers": "Tenants, home buyers, NRIs, property owners",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 80000,
        "medium_scale_investment": 350000,
        "advanced_scale_investment": 1500000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 400000,
        "risk_level": "Medium",
        "scalability_level": "Medium",
        "suitable_district_types": ["Urban", "Tier-2 City", "Tier-3 City"],
        "district_demand_level": "Medium",
        "competition_level": "Medium",
        "growth_trend": "Stable",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 5,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Field Lead", "Content/Photography", "Sales/Closer"],
        "skills_required": ["Sales", "Local Knowledge", "Photography", "Negotiation"],
        "contribution_types_needed": ["Skills", "Local Network", "Working Capital"],
        "ideal_for": ["Small Teams", "Working Professionals"],
        "eligible_government_schemes": ["Mudra Loan"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 64,
        "save_count": 72,
        "team_interest_count": 10,
    },

    # -------------------- PURE DIGITAL (6) --------------------
    {
        "slug": "video-editing-agency",
        "title": "Boutique Video Editing Agency",
        "short_description": "Remote video editing pod for YouTubers, podcasters and D2C brands.",
        "detailed_description": "Build a small pod of editors handling weekly YouTube long-form + Shorts, podcast clips and ad creatives. Retainer-based pricing per client.",
        "sector": "Creator Economy",
        "tags": ["video", "editing", "remote", "agency"],
        "problem_solved": "Creators and brands need consistent editing but agencies are expensive and freelancers vanish.",
        "target_customers": "YouTubers, podcasters, D2C brands, course creators",
        "beginner_friendly": True,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 30000,
        "medium_scale_investment": 120000,
        "advanced_scale_investment": 500000,
        "estimated_monthly_revenue_min": 40000,
        "estimated_monthly_revenue_max": 300000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Anywhere"],
        "district_demand_level": "Medium",
        "competition_level": "High",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 5,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Senior Editor", "Junior Editor", "Account Manager"],
        "skills_required": ["Premiere/DaVinci", "Motion Graphics", "Storytelling", "Client Comms"],
        "contribution_types_needed": ["Skills", "Equipment"],
        "ideal_for": ["Students", "Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Startup India"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 81,
        "save_count": 134,
        "team_interest_count": 27,
    },
    {
        "slug": "creator-studio",
        "title": "Multi-Creator Studio",
        "short_description": "Production + management studio for 5-15 regional creators (Telugu, Tamil, Hindi).",
        "detailed_description": "Build a managed creator studio: handle shooting, editing, scheduling, brand deals and analytics for regional creators on a revenue share + retainer.",
        "sector": "Creator Economy",
        "tags": ["creators", "studio", "regional"],
        "problem_solved": "Regional creators don't have the time or skills to manage production and brand deals; they leave money on the table.",
        "target_customers": "Regional YouTubers, Instagram creators, podcasters",
        "beginner_friendly": False,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 100000,
        "medium_scale_investment": 500000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 80000,
        "estimated_monthly_revenue_max": 600000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Urban", "Tier-2 City"],
        "district_demand_level": "Medium",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 7,
        "ideal_team_size_min": 4,
        "ideal_team_size_max": 10,
        "team_roles_needed": ["Studio Lead", "Editors", "Brand Sales", "Analytics Lead"],
        "skills_required": ["Production", "Brand Sales", "Analytics", "Talent Management"],
        "contribution_types_needed": ["Capital", "Skills", "Network"],
        "ideal_for": ["Small Teams", "Working Professionals"],
        "eligible_government_schemes": ["Startup India Seed Fund"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": True,
        "trending_score": 87,
        "save_count": 156,
        "team_interest_count": 35,
    },
    {
        "slug": "freelance-design-team",
        "title": "Freelance Design Collective",
        "short_description": "A collective of designers offering branding, web design and packaging on retainer.",
        "detailed_description": "Form a 4-8 person design collective with shared pipeline. Offer branding sprints, packaging design, and web/Shopify design as productised services.",
        "sector": "Creator Economy",
        "tags": ["design", "branding", "remote"],
        "problem_solved": "Startups and D2C brands need ongoing design help but lone freelancers can't handle volume or specialisation.",
        "target_customers": "Startups, D2C brands, SaaS companies, agencies",
        "beginner_friendly": True,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 20000,
        "medium_scale_investment": 100000,
        "advanced_scale_investment": 400000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 350000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Anywhere"],
        "district_demand_level": "Medium",
        "competition_level": "High",
        "growth_trend": "Stable",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 5,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Brand Designer", "Web Designer", "Account Lead", "Illustrator"],
        "skills_required": ["Figma", "Branding", "Webflow/Shopify", "Client Comms"],
        "contribution_types_needed": ["Skills"],
        "ideal_for": ["Students", "Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Startup India"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": False,
        "trending_score": 74,
        "save_count": 108,
        "team_interest_count": 22,
    },
    {
        "slug": "ai-automation-service",
        "title": "AI Workflow Automation Service",
        "short_description": "Build LLM + n8n workflows that save SMBs 10+ hours a week — sales, support, ops.",
        "detailed_description": "Audit SMB workflows, then deliver automations: AI sales outreach, support reply drafting, lead scoring, internal Slack bots. Charge setup + monthly retainer per workflow.",
        "sector": "AI Services",
        "tags": ["ai", "automation", "llm", "n8n"],
        "problem_solved": "SMBs hear about AI everywhere but don't know how to actually use it; consultants are too expensive.",
        "target_customers": "Agencies, ecommerce brands, B2B SaaS, real estate firms",
        "beginner_friendly": False,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 25000,
        "medium_scale_investment": 150000,
        "advanced_scale_investment": 750000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 500000,
        "risk_level": "Low",
        "scalability_level": "High",
        "suitable_district_types": ["Anywhere"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "Low",
        "automation_resistance_score": 2,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Automation Engineer", "LLM Prompt Engineer", "Sales/Solutioning"],
        "skills_required": ["LLM APIs", "n8n/Zapier/Make", "JavaScript/Python", "Sales"],
        "contribution_types_needed": ["Skills"],
        "ideal_for": ["Working Professionals", "Students"],
        "eligible_government_schemes": ["Startup India Seed Fund"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Low",
        "featured": True,
        "trending_score": 98,
        "save_count": 280,
        "team_interest_count": 64,
    },
    {
        "slug": "community-learning-platform",
        "title": "Niche Community Learning Platform",
        "short_description": "Cohort-based learning communities for specific careers — UX, data, AI, design.",
        "detailed_description": "Run 6-12 week cohort programs for specific careers (UX, Data Analytics, GenAI, Brand Design). Discord/Slack communities + live sessions + projects + placement support.",
        "sector": "EdTech",
        "tags": ["edtech", "cohort", "community"],
        "problem_solved": "Recorded courses have terrible completion rates; people want accountability and community to actually finish learning something.",
        "target_customers": "Students, early-career professionals, career switchers",
        "beginner_friendly": False,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 50000,
        "medium_scale_investment": 300000,
        "advanced_scale_investment": 1500000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 600000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Anywhere"],
        "district_demand_level": "Medium",
        "competition_level": "Medium",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 7,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 8,
        "team_roles_needed": ["Lead Instructor", "Community Manager", "Marketing Lead", "Mentor Network"],
        "skills_required": ["Teaching", "Community Building", "Marketing", "Career Guidance"],
        "contribution_types_needed": ["Skills", "Network", "Content"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Skill India", "Startup India"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 83,
        "save_count": 145,
        "team_interest_count": 31,
    },
    {
        "slug": "saas-niche-microtool",
        "title": "Niche B2B SaaS Micro-Tool",
        "short_description": "Tiny SaaS solving one painful workflow for one Bharat industry (e.g., tutors, salons, clinics).",
        "detailed_description": "Pick one underserved Bharat niche (e.g., spoken English tutors, salon chains, dental clinics). Build a focused tool — bookings, billing, WhatsApp reminders — and sell directly.",
        "sector": "SaaS",
        "tags": ["saas", "niche", "b2b"],
        "problem_solved": "Bharat niches use messy WhatsApp + Excel + paper today; horizontal SaaS doesn't fit them.",
        "target_customers": "Bharat SMBs in a single chosen vertical",
        "beginner_friendly": False,
        "execution_type": "Digital",
        "remote_possible": True,
        "minimum_investment": 50000,
        "medium_scale_investment": 400000,
        "advanced_scale_investment": 2500000,
        "estimated_monthly_revenue_min": 30000,
        "estimated_monthly_revenue_max": 500000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Anywhere"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "Medium",
        "automation_resistance_score": 6,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 5,
        "team_roles_needed": ["Full-stack Engineer", "Designer", "Sales/Customer Success"],
        "skills_required": ["React/Node", "Product Design", "Bharat Sales"],
        "contribution_types_needed": ["Skills", "Capital"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["Startup India Seed Fund", "MSME Innovation"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 77,
        "save_count": 122,
        "team_interest_count": 24,
    },

    # -------------------- FUTURE ECONOMY (3) --------------------
    {
        "slug": "drone-spraying-service",
        "title": "Agricultural Drone Spraying Service",
        "short_description": "DGCA-certified drone spraying for cotton, paddy and chilli farms — pay per acre.",
        "detailed_description": "Buy 2-5 agri-drones, train as Remote Pilots, partner with FPOs to spray pesticide/nutrients at scale. Faster, safer and cheaper than manual labour.",
        "sector": "AgriTech",
        "tags": ["drone", "agri", "future", "dgca"],
        "problem_solved": "Manual pesticide spraying is dangerous, slow and increasingly hard with rural labour shortages.",
        "target_customers": "FPOs, large farmers, agri input companies, govt schemes",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 1000000,
        "medium_scale_investment": 3500000,
        "advanced_scale_investment": 10000000,
        "estimated_monthly_revenue_min": 100000,
        "estimated_monthly_revenue_max": 800000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Agrarian", "Rural"],
        "district_demand_level": "High",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 8,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Drone Pilot", "Technician", "Field Sales/Coordinator"],
        "skills_required": ["DGCA Remote Pilot License", "Drone Maintenance", "Agri Knowledge"],
        "contribution_types_needed": ["Capital", "Skills", "Network"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["SMAM Drone Subsidy", "Namo Drone Didi", "Sub-Mission on Agricultural Mechanization"],
        "licensing_complexity": "High",
        "setup_difficulty": "High",
        "featured": True,
        "trending_score": 92,
        "save_count": 188,
        "team_interest_count": 42,
    },
    {
        "slug": "ev-charging-point-network",
        "title": "EV Charging Point Network",
        "short_description": "Strategically located 2W/3W/4W charging points along highways and townships.",
        "detailed_description": "Install AC/DC chargers at high-traffic locations (highway dhabas, shopping streets, apartments). Earn through per-kWh + parking fees. Stack with OMC partnerships.",
        "sector": "Clean Energy",
        "tags": ["ev", "charging", "future", "infrastructure"],
        "problem_solved": "EV adoption is hitting range anxiety in Tier-3 and highway routes; chargers are missing.",
        "target_customers": "EV owners (2W/3W/4W), fleet operators, cab drivers",
        "beginner_friendly": False,
        "execution_type": "Physical",
        "remote_possible": False,
        "minimum_investment": 800000,
        "medium_scale_investment": 3000000,
        "advanced_scale_investment": 12000000,
        "estimated_monthly_revenue_min": 60000,
        "estimated_monthly_revenue_max": 500000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Highway", "Urban", "Tier-2 City"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 9,
        "ideal_team_size_min": 2,
        "ideal_team_size_max": 6,
        "team_roles_needed": ["Site Selection Lead", "Electrical Engineer", "Operations"],
        "skills_required": ["Electrical", "Site Negotiation", "Operations", "Subsidy Paperwork"],
        "contribution_types_needed": ["Capital", "Site Access", "Operations"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["FAME-II", "MNRE EV Charging Subsidy"],
        "licensing_complexity": "Medium",
        "setup_difficulty": "High",
        "featured": False,
        "trending_score": 85,
        "save_count": 161,
        "team_interest_count": 36,
    },
    {
        "slug": "smart-farming-systems",
        "title": "Smart Farming IoT Systems",
        "short_description": "Soil sensors, weather stations and drip-automation kits installed and managed for farmers.",
        "detailed_description": "Sell + manage low-cost IoT kits (soil moisture, weather, drip control) on subscription. Deliver alerts and irrigation control via WhatsApp / app in regional languages.",
        "sector": "AgriTech",
        "tags": ["iot", "smart-farming", "future"],
        "problem_solved": "Farmers over- or under-irrigate, hurting yield and water table; data-driven farming is still inaccessible.",
        "target_customers": "Progressive farmers, horticulture growers, FPOs",
        "beginner_friendly": False,
        "execution_type": "Hybrid",
        "remote_possible": False,
        "minimum_investment": 200000,
        "medium_scale_investment": 1000000,
        "advanced_scale_investment": 5000000,
        "estimated_monthly_revenue_min": 50000,
        "estimated_monthly_revenue_max": 400000,
        "risk_level": "Medium",
        "scalability_level": "High",
        "suitable_district_types": ["Agrarian", "Horticulture Belt"],
        "district_demand_level": "Medium",
        "competition_level": "Low",
        "growth_trend": "Rising",
        "ai_proof_level": "High",
        "automation_resistance_score": 7,
        "ideal_team_size_min": 3,
        "ideal_team_size_max": 7,
        "team_roles_needed": ["IoT/Hardware Engineer", "Field Installer", "Agronomy Lead"],
        "skills_required": ["Embedded Systems", "Sensors", "Local Language", "Agri Domain"],
        "contribution_types_needed": ["Capital", "Tech", "Field Operations"],
        "ideal_for": ["Working Professionals", "Small Teams"],
        "eligible_government_schemes": ["PMKSY", "RKVY-RAFTAAR", "Agri Infrastructure Fund"],
        "licensing_complexity": "Low",
        "setup_difficulty": "Medium",
        "featured": False,
        "trending_score": 79,
        "save_count": 124,
        "team_interest_count": 25,
    },
]


def get_all_sectors():
    return sorted({i["sector"] for i in IDEAS_SEED})


def get_all_execution_types():
    return ["Physical", "Hybrid", "Digital"]


def get_all_ideal_for():
    s = set()
    for i in IDEAS_SEED:
        s.update(i.get("ideal_for", []))
    return sorted(s)
