#!/usr/bin/env python3
"""
Generate the DDL for the five output tables.

    python3 user_intelligence/generate_migration.py
    python3 user_intelligence/generate_migration.py --check

WHY `user_intelligence` AND NOT `public`
----------------------------------------
Same reasoning as Step 1's `knowledge` schema. These five tables hold *derived*
per-user data — recomputable from a profile plus a knowledge snapshot — and they
must be droppable without a moment's thought about whether a user table is nearby.

    drop schema user_intelligence cascade;

The brief protects `profiles`, `connections` and seven others. A separate schema
makes them unreachable from this migration by construction, not by care.

WHY EVERY TABLE IS KEYED ON (user_id, rules_version)
----------------------------------------------------
A recommendation must be explainable months later. Keying on user alone would
overwrite the row that a user acted on the moment a rule changed, and the
explanation would be gone. Keying on the rules version keeps the old row until
someone deliberately prunes it.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from user_intelligence import RULES_VERSION                     # noqa: E402
from user_intelligence.config import (OUTPUT_TABLES,            # noqa: E402
                                      RECOMMENDATION_CATEGORIES, SCORES)

SCHEMA = "user_intelligence"
OUT = Path(__file__).resolve().parent / "migrations" / "001_user_intelligence.sql"


def render():
    score_keys = ", ".join(f"'{s.key}'" for s in SCORES)
    cat_keys = ", ".join(f"'{c.key}'" for c in RECOMMENDATION_CATEGORIES)
    no_data = ", ".join(c.key for c in RECOMMENDATION_CATEGORIES if c.no_data_reason)

    return f"""-- ValueWeave User Intelligence (Platform v3.0, Step 1.5)
-- GENERATED by user_intelligence/generate_migration.py — do not edit by hand.
--
-- Five derived tables, one per output the brief specifies. Everything here is
-- recomputable from `profiles` plus a knowledge snapshot, so the whole schema is
-- disposable:
--
--     drop schema {SCHEMA} cascade;
--
-- A separate schema means this migration cannot reach profiles, connections,
-- opportunities or any other application table — by construction rather than by
-- care.
--
-- EVERY ROW CARRIES ITS PROVENANCE
--   rules_version   which logic produced it
--   result_hash     proves two runs over the same input agree
--   generated_at    when
--   reason          why, in words
--   evidence        which entities and edges, as jsonb
--
-- Rows are keyed on (user_id, rules_version): a recommendation a user acted on
-- must remain explainable after the rules change.

create schema if not exists {SCHEMA};
comment on schema {SCHEMA} is
  'Derived per-user intelligence. Recomputable from profiles + the knowledge '
  'graph; safe to drop and rebuild. Written only by the intelligence engine.';

grant usage on schema {SCHEMA} to authenticated;

-- ─────────────────────────────────────────────────────── user_skill_profile
create table if not exists {SCHEMA}.user_skill_profile (
  user_id                uuid        not null references public.profiles(id) on delete cascade,
  rules_version          text        not null,
  score                  numeric(5,2),
  status                 text        not null,
  confidence             smallint    not null default 0,
  reason                 text        not null,
  claimed_skill_count    integer     not null default 0,
  resolved_skill_count   integer     not null default 0,
  resolve_rate_pct       numeric(5,2),
  resolved_skills        jsonb       not null default '[]'::jsonb,
  -- The honest half. Skills the user claims that the knowledge base has no
  -- researched counterpart for: 50 such skills exist today (Step 0).
  unresolved_skills      jsonb       not null default '[]'::jsonb,
  categories             jsonb       not null default '[]'::jsonb,
  evidence               jsonb       not null default '[]'::jsonb,
  generated_at           timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ──────────────────────────────────────────────────── user_business_profile
-- One row per user holding the five business-facing scores as jsonb. Separate
-- columns would need a migration every time a score is added; the score keys are
-- constrained by the engine, which is where they are declared.
create table if not exists {SCHEMA}.user_business_profile (
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  business_readiness   jsonb       not null default '{{}}'::jsonb,
  district_opportunity jsonb       not null default '{{}}'::jsonb,
  ai_readiness         jsonb       not null default '{{}}'::jsonb,
  funding_readiness    jsonb       not null default '{{}}'::jsonb,
  startup_readiness    jsonb       not null default '{{}}'::jsonb,
  generated_at         timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ──────────────────────────────────────────────────── user_learning_profile
create table if not exists {SCHEMA}.user_learning_profile (
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  score                numeric(5,2),
  status               text        not null,
  confidence           smallint    not null default 0,
  reason               text        not null,
  distinct_gaps        integer     not null default 0,
  steps_with_provider  integer     not null default 0,
  roadmap              jsonb       not null default '[]'::jsonb,
  recommended_courses  jsonb       not null default '[]'::jsonb,
  generated_at         timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ───────────────────────────────────────────────────── user_recommendations
-- One row per recommendation. The four fields the brief requires are all NOT
-- NULL: a recommendation without a reason, evidence, confidence or timestamp is
-- not a recommendation this engine is willing to store.
create table if not exists {SCHEMA}.user_recommendations (
  id                   bigserial   primary key,
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  category             text        not null check (category in ({cat_keys})),
  category_status      text        not null,
  rank                 integer     not null,
  item_id              text        not null,
  item_label           text        not null,
  item_type            text        not null,
  match_score          numeric(5,2) not null,
  confidence           smallint    not null,
  confidence_band      text        not null,
  reason               text        not null,
  rule                 text        not null,
  supporting_entities  jsonb       not null default '[]'::jsonb,
  detail               jsonb       not null default '{{}}'::jsonb,
  unverified_notice    text        not null,
  generated_at         timestamptz not null default now(),
  unique (user_id, rules_version, category, item_id)
);

-- ─────────────────────────────────────────────────── user_activity_summary
create table if not exists {SCHEMA}.user_activity_summary (
  user_id                  uuid        not null references public.profiles(id) on delete cascade,
  rules_version            text        not null,
  engine_version           text        not null,
  scores                   jsonb       not null default '{{}}'::jsonb,
  recommendations_by_category jsonb    not null default '{{}}'::jsonb,
  total_recommendations    integer     not null default 0,
  -- Which scores could not be computed, and which categories have no data at all
  -- ({no_data}). Stored so a UI can explain a gap instead of rendering a blank.
  scores_unavailable       jsonb       not null default '[]'::jsonb,
  categories_without_data  jsonb       not null default '[]'::jsonb,
  inputs_unavailable       jsonb       not null default '[]'::jsonb,
  accepted_connections     integer     not null default 0,
  pending_connections      integer     not null default 0,
  profile_complete         boolean     not null default false,
  knowledge_snapshot_hash  text        not null,
  result_hash              text        not null,
  generated_at             timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ───────────────────────────────────────────────────────────────── indexes
create index if not exists user_recs_user_idx
  on {SCHEMA}.user_recommendations (user_id, category, rank);
create index if not exists user_recs_item_idx
  on {SCHEMA}.user_recommendations (item_id);
create index if not exists user_recs_generated_idx
  on {SCHEMA}.user_recommendations (generated_at desc);
create index if not exists user_summary_hash_idx
  on {SCHEMA}.user_activity_summary (result_hash);

-- ───────────────────────────────────────────────── row level security
-- A user reads their own intelligence and nobody else's. `auth.uid() = user_id`
-- is the whole policy, and there is deliberately no admin-read exception: these
-- rows are derived from a profile and describe that person.
{"".join(f'''
alter table {SCHEMA}.{t} enable row level security;
drop policy if exists "{t} own read" on {SCHEMA}.{t};
create policy "{t} own read"
  on {SCHEMA}.{t} for select
  using (auth.uid() = user_id);
''' for t in OUTPUT_TABLES)}
-- No insert, update or delete policy on any table. The engine writes with the
-- service role, which bypasses RLS; nothing reachable by a user session can
-- fabricate a recommendation.

grant select on all tables in schema {SCHEMA} to authenticated;
alter default privileges in schema {SCHEMA}
  grant select on tables to authenticated;

-- Current rules version at generation time: {RULES_VERSION}
-- Scores produced: {score_keys}
"""


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    sql = render()
    if args.stdout:
        print(sql)
        sys.exit(0)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != sql:
            print(f"{OUT.name} differs from a fresh generation "
                  f"(or is missing). Run without --check.", file=sys.stderr)
            sys.exit(1)
        print(f"  {OUT.name}: matches the engine configuration")
        sys.exit(0)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT.name} ({len(sql.splitlines())} lines, "
          f"{len(OUTPUT_TABLES)} tables)")
