#!/usr/bin/env python3
"""
Package007_Government_Schemes v1.0.0 — Documentation Builder

Generates from the actual CSVs + schema catalog + validation summary:
  docs/DATA_DICTIONARY.md   every column of every dataset with observed domains
  docs/IMPORT_GUIDE.md      load order, DDL, sentinel handling
  validation_report.md      narrative validation report
  quality_report.md         package quality assessment
  VERSION_HISTORY.md        version lineage
  RELEASE_NOTES.md          v1.0.0 release notes
"""

import csv
import json
from pathlib import Path

PKG = Path(__file__).resolve().parent
DATASETS = PKG / "datasets"
VERSION = "1.0.0"
CD = "2026-07-25"
PV = "PENDING_VERIFICATION"

SUMMARY = json.loads((PKG / "validation_summary.json").read_text())
CATALOG = json.loads((PKG / "schemas" / "schema_catalog.json").read_text())
STATS = SUMMARY["per_dataset"]
BY = {d["dataset_name"] + ".csv": d for d in CATALOG["datasets"]}
ORDER = [d["dataset_name"] + ".csv" for d in CATALOG["datasets"]]
XF = SUMMARY["cross_package_fk"]

PROVENANCE = {"data_source", "source_url", "collection_date",
              "confidence_score", "verification_status", "notes"}


def rows_of(name):
    with open(DATASETS / name, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def classify(col, values):
    nonpv = [v for v in values if v != PV]
    pv_n = len(values) - len(nonpv)
    distinct = sorted(set(nonpv))
    if col.endswith("_id") or col.endswith("_ids"):
        kind, domain = "identifier", f"{len(distinct)} distinct"
    elif nonpv and all(v.replace(".", "", 1).isdigit() for v in nonpv):
        nums = [float(v) for v in nonpv]
        kind, domain = "numeric", f"{min(nums):g}–{max(nums):g}"
    elif nonpv and len(distinct) <= 9:
        kind, domain = "enum", ", ".join(f"`{v}`" for v in distinct)
    elif col == "source_url":
        kind, domain = "url", f"{len(distinct)} distinct"
    elif col == "collection_date":
        kind, domain = "date", ", ".join(f"`{v}`" for v in distinct)
    else:
        kind, domain = "text", f"{len(distinct)} distinct values"
    if pv_n:
        domain += f" · **{pv_n} sentinel**"
    return kind, domain


# --------------------------------------------------------- DATA_DICTIONARY.md
dd = [
    f"# Data Dictionary — Package007_Government_Schemes v{VERSION}",
    "",
    "Every column of every dataset, with the value domain **actually observed in the released "
    "CSVs** — not an intended schema. Generated by `build_docs.py`; regenerate rather than edit.",
    "",
    f"**{len(ORDER)} datasets · {SUMMARY['total_records']} records · {SUMMARY['total_cells']} cells "
    f"· {SUMMARY['schemes_registered']} schemes · {SUMMARY['pending_verification_cells']} sentinel "
    f"({SUMMARY['pending_verification_rate_pct']}%)**",
    "",
    "## Conventions",
    "",
    "| Term | Meaning |",
    "|---|---|",
    "| **PK** | Primary key — unique and non-empty, enforced by check V2 |",
    "| **FK** | Foreign key — resolves in-package (V8) or upstream (V9) |",
    "| **sentinel** | The bare string `PENDING_VERIFICATION`: no public source found for that fact |",
    "| **enum** | Small closed set; the full observed domain is listed |",
    "",
    "### The six provenance columns",
    "",
    "Present on all 15 datasets with identical semantics, documented once here:",
    "",
    "| Column | Type | Meaning |",
    "|---|---|---|",
    "| `data_source` | text | Scheme portal, ministry or authority the row is attributed to |",
    "| `source_url` | url | Public URL for that body |",
    f"| `collection_date` | date | `{CD}` on every row (V7) |",
    f"| `confidence_score` | numeric | Integer 0–100, capped at 85 (V4). Observed range "
    f"{SUMMARY['confidence_min']}–{SUMMARY['confidence_max']} |",
    "| `verification_status` | enum | `VST-NEEDS_REVIEW` on every row — no human sign-off (V6) |",
    "| `notes` | text | Caveats and sourcing remarks |",
    "",
    "---",
    "",
]

for name in ORDER:
    d, st, rows = BY[name], STATS[name], rows_of(name)
    hdr = [c["name"] for c in d["columns"]]
    dd += [
        f"## `{name}`", "", d["purpose"], "",
        f"**Layer** {d['layer']} · **PK** `{d['primary_key']}` · **{st['records']} records** × "
        f"{st['columns']} columns · **confidence** {st['confidence_min']}–{st['confidence_max']} "
        f"(avg {st['confidence_avg']}) · **sentinel** {st['pending_verification_cells']} cells", "",
    ]
    if d["foreign_keys"]:
        dd += ["**Foreign keys**", ""]
        for fk in d["foreign_keys"]:
            dd.append(f"- `{fk['column']}` → `{fk['references_dataset']}` (`{fk['references_column']}`)")
        dd.append("")
    dd += ["| Column | Type | Observed domain | Notes |", "|---|---|---|---|"]
    fkc = {fk["column"]: fk for fk in d["foreign_keys"]}
    for col in hdr:
        if col in PROVENANCE:
            continue
        kind, domain = classify(col, [r[col] for r in rows])
        note = ""
        if col == d["primary_key"]:
            note = "**PK**"
        elif col in fkc:
            note = f"**FK** → `{fkc[col]['references_dataset']}`"
        elif col.endswith("_name") and any(
                f["column"].replace("_id", "_name") == col for f in d["foreign_keys"]):
            note = "denormalised from FK; V8/V9 verify agreement"
        dd.append(f"| `{col}` | {kind} | {domain} | {note} |")
    dd += ["| *…6 provenance columns* | | | see Conventions |", "",
           f"**Limitations.** {d['known_limitations']}", "", "---", ""]

(PKG / "docs" / "DATA_DICTIONARY.md").write_text("\n".join(dd))
print("docs/DATA_DICTIONARY.md")

# ------------------------------------------------------------ IMPORT_GUIDE.md
sent = []
for name in ORDER:
    for col, n in BY[name]["pending_verification_columns"].items():
        sent.append((name, col, n, STATS[name]["records"]))
sent.sort(key=lambda t: -t[2])

ig = [
    f"# Import Guide — Package007_Government_Schemes v{VERSION}",
    "",
    "How to load these 15 CSVs into a relational store without corrupting them.",
    "",
    "## 1. Load order",
    "",
    "Dependency order, also recorded as `import_order` in `package_manifest.json`.",
    "",
    "| # | Dataset | Depends on |",
    "|---|---|---|",
]
for i, name in enumerate(ORDER, 1):
    deps = ", ".join(f"`{fk['references_dataset']}`" for fk in BY[name]["foreign_keys"]) or "—"
    ig.append(f"| {i} | `{name}` | {deps} |")

ig += [
    "",
    "Reference taxonomies load first, then `government_schemes` (the canonical registry), then its "
    "child datasets, then the five cross-package mappings, and `scheme_ai_recommendations` last "
    "because it references `government_schemes` three times — including a semicolon-delimited "
    "multi-value column.",
    "",
    "Five of the mapping datasets carry foreign keys **outside** this package. Loading Package007 "
    "standalone is fine — treat those columns as unresolved text until the upstream packages are "
    "present in the same schema.",
    "",
    "## 2. Every column is text on ingest",
    "",
    "Load as `TEXT`/`VARCHAR`, then cast in a second pass. The sentinel occupies cells in "
    "otherwise-numeric columns, so a directly typed load fails or silently coerces.",
    "",
    "```sql",
    "CREATE TABLE stg_government_schemes (",
    "  scheme_id            TEXT,",
    "  scheme_name          TEXT,",
    "  short_name           TEXT,",
    "  category_id          TEXT,",
    "  category_name        TEXT,",
    "  ministry             TEXT,",
    "  department           TEXT,",
    "  government_level     TEXT,",
    "  launch_year          TEXT,",
    "  objective            TEXT,",
    "  benefit_summary      TEXT,",
    "  financial_assistance TEXT,   -- sentinel on nearly every row",
    "  subsidy_component    TEXT,",
    "  loan_support         TEXT,",
    "  coverage             TEXT,",
    "  application_mode     TEXT,",
    "  official_portal      TEXT,",
    "  status               TEXT,",
    "  also_in_package      TEXT,   -- sentinel where the scheme is Package007-only",
    "  data_source          TEXT,",
    "  source_url           TEXT,",
    "  collection_date      TEXT,",
    "  confidence_score     TEXT,",
    "  verification_status  TEXT,",
    "  notes                TEXT",
    ");",
    "```",
    "",
    "Promote with an explicit sentinel guard:",
    "",
    "```sql",
    "CREATE TABLE government_schemes AS",
    "SELECT scheme_id, scheme_name, short_name, category_id,",
    "       ministry, department, government_level,",
    "       NULLIF(launch_year,          'PENDING_VERIFICATION')::INT AS launch_year,",
    "       NULLIF(financial_assistance, 'PENDING_VERIFICATION')      AS financial_assistance,",
    "       NULLIF(also_in_package,      'PENDING_VERIFICATION')      AS also_in_package,",
    "       objective, benefit_summary, coverage, application_mode,",
    "       official_portal, status,",
    "       confidence_score::INT AS confidence_score,",
    "       verification_status, notes",
    "FROM stg_government_schemes;",
    "```",
    "",
    "`confidence_score` needs no guard — V4 guarantees a plain integer on every row of every "
    "dataset, never a sentinel.",
    "",
    "## 3. Columns that carry sentinels",
    "",
    "| Dataset | Column | Sentinel rows |",
    "|---|---|---|",
]
for name, col, n, tot in sent:
    ig.append(f"| `{name}` | `{col}` | {n} / {tot} |")

ig += [
    "",
    "Whole-column cases — a `NOT NULL` constraint on any of these will fail the load:",
    "",
    "- `application_process.typical_timeline` — **all 43 rows**",
    "- `district_scheme_mapping.district_specific_variation` — **all 305 rows**",
    "- `scheme_benefits.benefit_quantum` — nearly every row",
    "- `government_schemes.financial_assistance` — nearly every row",
    "",
    "This is intentional (see `docs/METHODOLOGY.md` §2): scheme amounts and processing timelines "
    "are notification-driven and were not confirmable, so none is asserted.",
    "",
    "## 4. Constraints to declare",
    "",
    "```sql",
    "ALTER TABLE scheme_categories   ADD PRIMARY KEY (category_id);",
    "ALTER TABLE required_documents  ADD PRIMARY KEY (document_id);",
    "ALTER TABLE government_schemes  ADD PRIMARY KEY (scheme_id);",
    "",
    "ALTER TABLE government_schemes ADD FOREIGN KEY (category_id)",
    "  REFERENCES scheme_categories(category_id);",
    "ALTER TABLE eligibility_criteria ADD FOREIGN KEY (scheme_id)",
    "  REFERENCES government_schemes(scheme_id);",
    "ALTER TABLE scheme_benefits ADD FOREIGN KEY (scheme_id)",
    "  REFERENCES government_schemes(scheme_id);",
    "ALTER TABLE application_process ADD FOREIGN KEY (scheme_id)",
    "  REFERENCES government_schemes(scheme_id);",
    "-- and the same on all five *_scheme_mapping tables",
    "",
    "ALTER TABLE government_schemes",
    "  ADD CHECK (confidence_score BETWEEN 0 AND 85),",
    "  ADD CHECK (verification_status IN ('VST-NEEDS_REVIEW','VST-VERIFIED')),",
    "  ADD CHECK (government_level IN ('Central','State','Central-State','Local')),",
    "  ADD CHECK (status IN ('Active','Closed','Subsumed','Revised'));",
    "```",
    "",
    "**Do not** declare foreign keys on the cross-package columns "
    "(`package001_dist_id`, `package002_record_id`, `package005_*`, `package006_*`, "
    "`package004_opportunity_name`) unless those packages are loaded in the same schema — several "
    "carry sentinels and will violate a naive FK.",
    "",
    "`scheme_ai_recommendations.related_scheme_ids` is a **semicolon-delimited multi-value column**. "
    "Normalise it into a junction table rather than declaring an FK on it:",
    "",
    "```sql",
    "CREATE TABLE recommendation_related_scheme AS",
    "SELECT recommendation_id,",
    "       TRIM(UNNEST(STRING_TO_ARRAY(related_scheme_ids, ';'))) AS scheme_id",
    "FROM scheme_ai_recommendations",
    "WHERE related_scheme_ids <> 'PENDING_VERIFICATION';",
    "```",
    "",
    "## 5. Denormalised name columns",
    "",
    "Child and mapping datasets carry `scheme_short_name` alongside `scheme_id` for readability, "
    "and the mapping datasets do the same for upstream names. V8 and V9 verify these agree with "
    "the referenced row — this is what caught a real short-name inconsistency during release "
    "(`SUI` in the registry versus `Stand-Up India` in five child datasets).",
    "",
    "If you normalise on import, drop the name columns and join. If you keep them, re-run "
    "`validate.py` after any edit.",
    "",
    "## 6. Post-load verification",
    "",
    "| Table | Rows |",
    "|---|---|",
]
for name in ORDER:
    ig.append(f"| `{name.replace('.csv','')}` | {STATS[name]['records']} |")
ig += [
    f"| **total** | **{SUMMARY['total_records']}** |",
    "",
    "Authoritative counts live in `registry/dataset_registry.csv` and `package_manifest.json`, "
    "both generated from the CSVs themselves.",
    "",
    "## 7. Re-validating",
    "",
    "```bash",
    "cd packages/Package007_Government_Schemes",
    "python3 validate.py      # exit 0 = clean",
    "```",
    "",
    "Run before any import and after any hand-edit.",
]
(PKG / "docs" / "IMPORT_GUIDE.md").write_text("\n".join(ig) + "\n")
print("docs/IMPORT_GUIDE.md")

# --------------------------------------------------------- validation_report.md
conf_sorted = sorted(ORDER, key=lambda n: STATS[n]["confidence_avg"])
vr = [
    f"# Validation Report — Package007_Government_Schemes v{VERSION}",
    "",
    f"**Result: {SUMMARY['result']}** · {SUMMARY['violations']} violations · {len(ORDER)} datasets "
    f"· {SUMMARY['total_records']} records · {SUMMARY['total_cells']} cells · "
    f"{SUMMARY['schemes_registered']} schemes",
    "",
    f"Validated {CD} by `validate.py` (in-package, re-runnable). Machine-readable output in "
    "`validation_summary.json`.",
    "",
    "## Checks run",
    "",
    "| Check | Enforces | Result |",
    "|---|---|---|",
    "| V1 Structural | Every row matches its header's column count | PASS |",
    "| V2 Primary key | First column unique and non-empty in all 15 datasets | PASS |",
    "| V3 Provenance | All six provenance columns present on every dataset | PASS |",
    "| V4 Confidence | Integer, 0–100, ≤ 85 policy ceiling | PASS |",
    "| V5 Sentinel | `PENDING_VERIFICATION` only as a bare exact string | PASS |",
    "| V6 Verification | `verification_status` in the allowed enum | PASS |",
    f"| V7 Collection date | Uniform `{CD}` package-wide | PASS |",
    "| V8 In-package FK | FKs resolve; denormalised names agree; multi-value column members resolve | PASS |",
    "| V9 Cross-package FK | Package001/002/004/005/006 references resolve upstream | PASS |",
    "| V10 Empty cells | No silently blank cells — a gap must be the sentinel | PASS |",
    "| V11 Scheme coverage | Every scheme has ≥1 eligibility criterion and ≥1 benefit row | PASS |",
    "| V12 Enum integrity | `government_level`, `status`, `is_mandatory`, `is_terminal`, `priority_sector_lending` use closed domains | PASS |",
    "",
    "## Per-dataset results",
    "",
    "| Dataset | Records | Cols | PK unique | Confidence | Avg | Sentinel | Blank |",
    "|---|---|---|---|---|---|---|---|",
]
for name in ORDER:
    st = STATS[name]
    vr.append(f"| `{name}` | {st['records']} | {st['columns']} | ✓ | "
              f"{st['confidence_min']}–{st['confidence_max']} | {st['confidence_avg']} | "
              f"{st['pending_verification_cells']} | 0 |")
vr.append(f"| **package** | **{SUMMARY['total_records']}** | — | ✓ | "
          f"**{SUMMARY['confidence_min']}–{SUMMARY['confidence_max']}** | — | "
          f"**{SUMMARY['pending_verification_cells']}** "
          f"({SUMMARY['pending_verification_rate_pct']}%) | **0** |")

vr += [
    "",
    "## Cross-package foreign key integrity (V9)",
    "",
    "This is the widest cross-package surface in the knowledge base: **nine distinct foreign key "
    "sets into five released packages.** Every one was resolved by reading the upstream CSVs at "
    "generation time, and all are re-checked on every validation run, so a rename upstream fails "
    "the build rather than silently breaking.",
    "",
    "| Reference | Upstream target | Resolved | Sentinel | Unresolved |",
    "|---|---|---|---|---|",
]
XLABEL = {
    "Package001 district": "`district_scheme_mapping.package001_dist_id` → Package001 `district.dist_id`",
    "Package002 scholarship": "`education_scheme_mapping.package002_record_id` → Package002 `scholarships.id`",
    "Package005 scheme": "`agriculture_scheme_mapping.package005_scheme_id` → Package005 `agriculture_schemes.scheme_id`",
    "Package005 crop": "`agriculture_scheme_mapping.package005_crop_id` → Package005 `crops.crop_id`",
    "Package006 scheme": "`skill_scheme_mapping.package006_scheme_id` → Package006 `government_skill_schemes.scheme_id`",
    "Package006 skill": "`skill_scheme_mapping.package006_skill_id` → Package006 `skills.skill_id`",
    "Package006 certification": "`skill_scheme_mapping.package006_certification_id` → Package006 `certifications.certification_id`",
    "Package006 provider": "`skill_scheme_mapping.package006_provider_id` → Package006 `training_providers.provider_id`",
    "Package004 opportunity": "`industry_scheme_mapping.package004_opportunity_name` → Package004 `name` / `scheme_name` / `adapted_indian_concept`",
}
for k, v in XF.items():
    vr.append(f"| {XLABEL.get(k, k)} | — | {v['resolved']} | {v['sentinel']} | **0** |")

vr += [
    "",
    "V9 also verifies the **denormalised upstream name** columns agree with the upstream record, "
    "not just that the id exists. A stale `package005_crop_name` against a valid `crop_id` fails.",
    "",
    "Sentinels here are honest absences, not failures:",
    "",
    "- **Package002 (3 sentinel)** — Samagra Shiksha and PM POSHAN are institutional and "
    "entitlement schemes with no scholarship record to point at; Skill Loan is education finance, "
    "which Package002 does not cover.",
    "- **Package005 (2 sentinel each side)** — PM-KUSUM and PMFME are not in Package005 v1.0.0; "
    "and crop-agnostic schemes (PM-KISAN, Soil Health Card) deliberately carry the crop sentinel "
    "because support is per landholding, not per crop.",
    "- **Package006 (3, 1, 8, 9 sentinel)** — PM Vishwakarma and PMEGP have no Package006 scheme "
    "counterpart. Certification and provider links are sparse because most scheme-to-skill "
    "relationships do not run through one named certificate or one named provider.",
    "",
    "## In-package foreign key integrity (V8)",
    "",
    "| Reference | Target | Rows checked | Result |",
    "|---|---|---|---|",
    f"| `government_schemes.category_id` | `scheme_categories.category_id` | {STATS['government_schemes.csv']['records']} | PASS |",
    f"| `eligibility_criteria.scheme_id` | `government_schemes.scheme_id` | {STATS['eligibility_criteria.csv']['records']} | PASS |",
    f"| `eligibility_criteria.verification_document_hint` | `required_documents.document_name` | {STATS['eligibility_criteria.csv']['records']} | PASS |",
    f"| `scheme_benefits.scheme_id` | `government_schemes.scheme_id` | {STATS['scheme_benefits.csv']['records']} | PASS |",
    f"| `application_process.scheme_id` | `government_schemes.scheme_id` | {STATS['application_process.csv']['records']} | PASS |",
    f"| `district_scheme_mapping.scheme_id` | `government_schemes.scheme_id` | {STATS['district_scheme_mapping.csv']['records']} | PASS |",
    f"| `scheme_ai_recommendations.scheme_id` | `government_schemes.scheme_id` | {STATS['scheme_ai_recommendations.csv']['records']} | PASS |",
    f"| `scheme_ai_recommendations.suggested_next_scheme_id` | `government_schemes.scheme_id` | {STATS['scheme_ai_recommendations.csv']['records']} | PASS |",
    f"| `scheme_ai_recommendations.related_scheme_ids` | `government_schemes.scheme_id` (semicolon-delimited members) | {STATS['scheme_ai_recommendations.csv']['records']} | PASS |",
    "",
    "## Issues found and resolved during validation",
    "",
    "Four real defects were caught by the checks before release. Three of the four were found by "
    "checks that exist specifically because earlier packages in this programme shipped without "
    "them:",
    "",
    "**1. Cross-package FK to a non-existent record (V9, caught at generation).** The skill "
    "mapping assumed Package006 held an entrepreneurship skill — a Package006 collection report "
    "describes one — but the released `skills.csv` does not contain it. The generator aborted "
    "rather than writing an unresolvable UUID. The PMEGP row now carries the sentinel on all four "
    "Package006 columns. **A collection report described data the dataset does not contain**; only "
    "reading the actual CSV surfaced it.",
    "",
    "**2. A second non-existent cross-package record (V9, caught at generation).** The industry "
    "mapping assumed Package004 held an AI opportunity. It does not. The row was repointed at the "
    "real `Small IT Services Firm / Software Development Startup` record.",
    "",
    "**3. Denormalised name drift (V8).** `government_schemes` recorded Stand-Up India's "
    "`short_name` as `SUI` while five child datasets used `Stand-Up India`. Every join would have "
    "worked — the ids were correct — but any display or grouping on the denormalised column would "
    "have split one scheme into two. The registry was corrected to the widely used form.",
    "",
    "**4. Document hint pointing at no document (V8).** Two eligibility rows cited "
    "`Bonafide Certificate` while `required_documents.csv` holds "
    "`Bonafide / Study Certificate`. Corrected to the actual document name.",
    "",
    "**5. Scheme coverage gaps (V11).** Four schemes — Soil Health Card, Samagra Shiksha, "
    "PM POSHAN and AB-HWC — had no eligibility rows at all, because they are universal, "
    "institutional or automatic-entitlement schemes with nothing to screen. Absence was the wrong "
    "representation: a consumer cannot distinguish 'no criteria exist' from 'criteria not yet "
    "collected'. Explicit rows were added stating the universality.",
    "",
    "## Confidence distribution",
    "",
    f"Package range **{SUMMARY['confidence_min']}–{SUMMARY['confidence_max']}**, ceiling **85** "
    "(never reached).",
    "",
    "The ceiling exists because WebFetch to `.gov.in` / `.nic.in` / `.ac.in` is blocked by this "
    "environment's egress policy, so no row rests on a primary-source page read. Ranked "
    "lowest-confidence first, since that is where a reviewer should look:",
    "",
    "| Dataset | Avg | Range | Why |",
    "|---|---|---|---|",
]
WHY = {
    "scheme_ai_recommendations.csv": "priority_score is a designed heuristic with no empirical calibration — a rule-engine seed, not evidence",
    "scheme_application_status.csv": "Generic reference workflow observed across portals, not any single portal's state machine",
    "skill_scheme_mapping.csv": "Four-way cross-package FK; several links have no upstream counterpart",
    "financial_institutions.csv": "Institution-type rows (RRBs, cooperatives, PACS) describe categories, not named entities",
    "implementing_agencies.csv": "District and local-body rows describe agency types present in every district",
    "application_process.csv": "Workflow steps from portal documentation; no published service standards for timelines",
    "industry_scheme_mapping.csv": "Scheme-to-opportunity fit is an analytical judgement over two released packages",
    "education_scheme_mapping.csv": "Reconciliation against Package002; three rows have no counterpart record",
    "agriculture_scheme_mapping.csv": "Reconciliation against Package005; crop-specific relevance is an agronomic judgement",
    "required_documents.csv": "Issuing authorities are Tier 1, but validity and route vary by state",
    "district_scheme_mapping.csv": "Package001 district master is Tier 1; the district-agency claim is structural",
    "eligibility_criteria.csv": "Scheme guidelines; thresholds stated qualitatively since figures are notification-driven",
    "scheme_benefits.csv": "Scheme guidelines; quantum unsourceable so scored on type, mode and frequency",
    "scheme_categories.csv": "Ministry attribution is Tier 1; cross-cutting categories are inherently fuzzy",
    "government_schemes.csv": "Each row attributed to the scheme's own portal — the strongest source class in the package",
}
for name in conf_sorted:
    st = STATS[name]
    vr.append(f"| `{name}` | {st['confidence_avg']} | {st['confidence_min']}–{st['confidence_max']} "
              f"| {WHY.get(name,'')} |")

vr += [
    "",
    "The floor of 60 is confined to `scheme_ai_recommendations`. That is deliberate: "
    "`priority_score` is a designed heuristic, and scoring those rows higher would imply empirical "
    "grounding the package does not have.",
    "",
    "## Sentinel distribution",
    "",
    f"**{SUMMARY['pending_verification_cells']} of {SUMMARY['total_cells']} cells "
    f"({SUMMARY['pending_verification_rate_pct']}%)** carry the bare sentinel, clustered in exactly "
    "the fields that could not be sourced without a primary page read:",
    "",
    "| Dataset | Column | Rows |",
    "|---|---|---|",
]
for name, col, n, tot in sent:
    vr.append(f"| `{name}` | `{col}` | {n} / {tot} |")

vr += [
    "",
    "Two clusters dominate. **Monetary quantum** — `financial_assistance`, `benefit_quantum` — is "
    "sentinelled because scheme amounts, premium rates, loan ceilings and subsidy percentages are "
    "revised by notification and budget cycle; a figure stated here would date badly in exactly "
    "the field applicants rely on most. **Timelines** — `typical_timeline` on all 43 process rows "
    "— is sentinelled because no published service standard was confirmable except MGNREGA's "
    "statutory period.",
    "",
    "## Verification status",
    "",
    f"**All {SUMMARY['total_records']} records are `VST-NEEDS_REVIEW`.** Nothing in this package "
    "has had human data-steward sign-off. Machine validation confirms structural integrity, "
    "referential integrity across five packages, provenance completeness and coverage; it does not "
    "confirm factual accuracy or currency. For a package whose subject matter changes with every "
    "budget, currency is the binding risk.",
    "",
    "## Reproducing this report",
    "",
    "```bash",
    "cd packages/Package007_Government_Schemes",
    "python3 validate.py       # writes validation_summary.json, exit 0 = clean",
    "python3 build_docs.py     # regenerates this report from that summary",
    "```",
    "",
    "Every figure above is derived from the released CSVs rather than hand-maintained, so this "
    "report cannot drift out of agreement with the data it describes.",
]
(PKG / "validation_report.md").write_text("\n".join(vr) + "\n")
print("validation_report.md")

# ------------------------------------------------------------- quality_report.md
sch_rows = rows_of("government_schemes.csv")
cat_counts = {}
for r in sch_rows:
    cat_counts[r["category_name"]] = cat_counts.get(r["category_name"], 0) + 1
overlap = sum(1 for r in sch_rows if r["also_in_package"] != PV)
elig_rows = rows_of("eligibility_criteria.csv")
ben_rows = rows_of("scheme_benefits.csv")
ctypes = {}
for r in elig_rows:
    ctypes[r["criterion_type"]] = ctypes.get(r["criterion_type"], 0) + 1
btypes = {}
for r in ben_rows:
    btypes[r["benefit_type"]] = btypes.get(r["benefit_type"], 0) + 1

qr = [
    f"# Quality Report — Package007_Government_Schemes v{VERSION}",
    "",
    "An assessment of what this package is fit for and where it is not. Read it before building "
    "on the data.",
    "",
    "## Headline",
    "",
    "| Dimension | Assessment |",
    "|---|---|",
    "| **Structural integrity** | Strong. 12 checks, 0 violations, 15/15 datasets clean. |",
    "| **Referential integrity** | Strong. 9 cross-package FK sets into 5 released packages, 0 unresolved. |",
    "| **Provenance completeness** | Strong. 6 mandatory columns on all "
    f"{SUMMARY['total_records']} rows; every row attributed to a named authority. |",
    "| **Coverage breadth** | Adequate. 40 schemes across 24 categories, all Central. |",
    "| **Coverage depth** | Mixed. Eligibility and benefits complete for all 40 schemes; process "
    "workflows for only 8. |",
    "| **Numeric completeness** | Weak by design. No monetary amount asserted anywhere. |",
    "| **Currency** | Unverified. Subject matter changes with every budget; no row re-checked "
    "against a live portal. |",
    "| **Human review** | None. All rows `VST-NEEDS_REVIEW`. |",
    "",
    "## What this package is fit for",
    "",
    "- **Eligibility screening logic.** `eligibility_criteria.csv` decomposes conditions into "
    f"{len(elig_rows)} typed rows across a closed vocabulary, which is what makes rule-based "
    "matching possible. Every scheme has at least one criterion row (V11).",
    "- **Scheme discovery and navigation.** Category, ministry, beneficiary group and application "
    "mode are populated throughout.",
    "- **Cross-domain recommendation.** The five mapping datasets connect schemes to crops, skills, "
    "business opportunities, education records and districts using real upstream ids.",
    "- **Document checklist generation.** `required_documents.csv` joined through "
    "`eligibility_criteria.verification_document_hint` produces a per-scheme document list.",
    "- **Process expectation setting.** `application_process.csv` names the actor and output of "
    "each step for 8 schemes — enough to tell an applicant what happens next, though not when.",
    "",
    "## What this package is NOT fit for",
    "",
    "- **Quoting benefit amounts to a citizen.** No amount is asserted. Every monetary field is "
    "the sentinel. Read the `official_portal` instead.",
    "- **Promising processing times.** `typical_timeline` is the sentinel on all 43 process rows.",
    "- **Determining actual eligibility.** Thresholds are stated qualitatively ('below the "
    "prescribed ceiling'), not numerically. This package narrows a candidate set; it cannot decide "
    "a case.",
    "- **State scheme discovery.** All 40 registry rows are Central. State schemes for Telangana "
    "and Andhra Pradesh live in Package002, Package003 and Package004.",
    "- **Ranking schemes by expected value.** `priority_score` is a designed heuristic with no "
    "outcome calibration.",
    "",
    "## Registry composition",
    "",
    f"**{len(sch_rows)} schemes** across **{len(cat_counts)} of 24 categories**. Categories with no "
    "scheme in v1.0.0 hold classification value for future additions but currently have no rows "
    "pointing at them.",
    "",
    "| Category | Schemes |",
    "|---|---|",
]
for k, v in sorted(cat_counts.items(), key=lambda kv: (-kv[1], kv[0])):
    qr.append(f"| {k} | {v} |")

qr += [
    "",
    f"**Overlap with domain packages:** {overlap} of {len(sch_rows)} schemes are also released in a "
    "domain package, declared in `also_in_package`. That column exists so the duplication is "
    "explicit and reconcilable. The remaining "
    f"{len(sch_rows) - overlap} are Package007-only.",
    "",
    "This overlap is the single most important governance question for the package. Five packages "
    "now hold scheme data. Either Package007 becomes the single source of truth and the domain "
    "packages reference it, or the two drift. `also_in_package` records the current state; it does "
    "not resolve it. See `codex_handoff.md`.",
    "",
    "## Eligibility criterion coverage",
    "",
    f"{len(elig_rows)} criterion rows across {len(ctypes)} criterion types:",
    "",
    "| Criterion type | Rows |",
    "|---|---|",
]
for k, v in sorted(ctypes.items(), key=lambda kv: (-kv[1], kv[0])):
    qr.append(f"| {k} | {v} |")

qr += [
    "",
    "## Benefit type coverage",
    "",
    f"{len(ben_rows)} benefit rows across {len(btypes)} benefit types. Multi-component schemes "
    "carry multiple rows — PM Vishwakarma has three (training, equipment, loan), which is the "
    "structure a recommender needs:",
    "",
    "| Benefit type | Rows |",
    "|---|---|",
]
for k, v in sorted(btypes.items(), key=lambda kv: (-kv[1], kv[0])):
    qr.append(f"| {k} | {v} |")

qr += [
    "",
    "## Risk register",
    "",
    "| Risk | Severity | Mitigation in place | Residual |",
    "|---|---|---|---|",
    "| Scheme amounts change by budget cycle | High | No amount asserted; `official_portal` on "
    "every row | Consumers must fetch live figures |",
    "| Scheme renamed, merged or subsumed | High | `status` enum includes Subsumed and Revised; "
    "`notes` records known renames | No automated currency check |",
    "| Domain-package duplication drifts | High | `also_in_package` declares overlap; V9 verifies "
    "linked records exist | Governance decision unresolved |",
    "| Upstream id renamed | Medium | V9 fails the build on any unresolved id | Requires "
    "`validate.py` to actually be run |",
    "| Eligibility thresholds misread as current | Medium | Thresholds stated qualitatively, never "
    "numerically | Consumer may still over-read |",
    "| `priority_score` mistaken for evidence | Medium | Confidence 60 on every row; caveat in "
    "notes, metadata, schema catalog and here | Depends on consumers reading docs |",
    "| No human review | Medium | Every row `VST-NEEDS_REVIEW`; stated in 6 places | Unresolved "
    "until a data steward signs off |",
    "",
    "## Recommended next actions, in priority order",
    "",
    "1. **Resolve the duplication governance question.** Decide whether Package007 is the single "
    "source of truth for schemes. Every release that passes without deciding makes the eventual "
    "reconciliation larger.",
    "2. **Human data-steward review of the 40 registry rows.** Highest value per hour spent, "
    "because the registry is what everything else hangs off.",
    "3. **Primary-source access for amounts and timelines.** Would clear the two dominant sentinel "
    "clusters and is the main thing standing between this package and citizen-facing use.",
    "4. **`health_scheme_mapping.csv`** to give Package003 a hard FK — the one released package "
    "with no structural link.",
    "5. **State scheme registry**, reconciled against the state slices already in Package002, "
    "Package003 and Package004.",
    "",
    "## Reproducing this report",
    "",
    "```bash",
    "python3 validate.py && python3 build_docs.py",
    "```",
    "",
    "Every count is computed from the released CSVs at generation time.",
]
(PKG / "quality_report.md").write_text("\n".join(qr) + "\n")
print("quality_report.md")

# ------------------------------------------------------------ VERSION_HISTORY.md
vh = f"""# Version History — Package007_Government_Schemes

Released versions are immutable. Corrections and additions ship as new versions under
`Package007_Government_Schemes_vMAJOR.MINOR.PATCH`.

| Version | Date | Status | Datasets | Records | Schemes | Validation | Summary |
|---|---|---|---|---|---|---|---|
| **1.0.0** | {CD} | Stable | {len(ORDER)} | {SUMMARY['total_records']} | {SUMMARY['schemes_registered']} | PASS (0 violations, 12 checks) | First release. Canonical scheme registry plus eligibility, benefits, process, institutions, five cross-package mappings and a recommendation layer. |
| 0.0.0 | 2026-07-20 | Placeholder | 0 | 0 | 0 | n/a | `README.md` reserving Package007 for government scheme assets. No data. |

## Semantic versioning policy

| Change class | Version bump | Examples |
|---|---|---|
| Correction with no structural or semantic change | **Patch** (1.0.x) | Fixing a typo in `objective`; correcting a `source_url` |
| Additive, backward-compatible | **Minor** (1.x.0) | New schemes; new datasets such as `health_scheme_mapping`; populating existing sentinels |
| Structural or breaking | **Major** (x.0.0) | Renaming or removing a column; changing a primary-key scheme; splitting the registry |

## v1.0.0 lineage notes

The package was built in four stages, each gated by validation:

1. **Core generation** (`gen_core.py`) — 7 scheme-intrinsic datasets
2. **Mapping generation** (`gen_mappings.py`) — 8 relational and workflow datasets, resolving
   cross-package foreign keys against the released upstream CSVs at generation time
3. **Validation** (`validate.py`) — 12 checks; 5 defect classes found and fixed before release
4. **Artifacts and documentation** (`build_artifacts.py`, `build_docs.py`) — generated from the
   CSVs plus the validation summary, so no count is hand-maintained

Two of the five defects were cross-package foreign keys pointing at upstream records that do not
exist. Both were caught because the generator resolves ids against the actual upstream CSVs and
aborts rather than writing an unresolvable reference. One of those cases is instructive: a
Package006 collection report describes an entrepreneurship skill that the released `skills.csv`
does not contain. Only reading the dataset — not its documentation — surfaced it.

## Upstream package versions this release was built against

| Package | Version | What Package007 references |
|---|---|---|
| Package001_Geography | 1.0.0 | `district.dist_id` (61 districts) |
| Package002_Education | 1.0.0 | `scholarships.id` |
| Package003_Healthcare | 1.0.0 | Declared in `also_in_package`; no hard FK yet |
| Package004_Industries | 1.0.0 | Opportunity names across 4 datasets |
| Package005_Agriculture | 1.0.0 | `agriculture_schemes.scheme_id`, `crops.crop_id` |
| Package006_Skills_and_Training | 1.0.0 | `government_skill_schemes.scheme_id`, `skills.skill_id`, `certifications.certification_id`, `training_providers.provider_id` |

If any upstream package issues a version that renames these ids, `validate.py` check V9 fails and
this package needs a corresponding release.
"""
(PKG / "VERSION_HISTORY.md").write_text(vh)
print("VERSION_HISTORY.md")

# ------------------------------------------------------------- RELEASE_NOTES.md
rn = f"""# Release Notes — Package007_Government_Schemes v{VERSION}

**Released {CD} · Stable · validation PASS (0 violations across 12 checks)**

## What this is

The Policy Intelligence Graph of the ValueWeave knowledge base: a canonical registry of
{SUMMARY['schemes_registered']} government schemes, surrounded by the structures that make schemes
actionable rather than merely listed — decomposed eligibility logic, itemised benefits, ordered
application workflows, document requirements, implementing agencies and financial institutions —
then bound outward to five released domain packages and upward into a profile-based recommendation
layer.

{len(ORDER)} datasets · {SUMMARY['total_records']} records · {SUMMARY['total_cells']} cells.

## The questions it answers

The package was built around the citizen questions in the specification. Each maps to a concrete
query — see `docs/USAGE.md` for the SQL:

| Question | Where it is answered |
|---|---|
| Which schemes am I eligible for? | `eligibility_criteria` joined to `government_schemes` |
| Which schemes are available for students / farmers / MSMEs? | `scheme_categories.category_group` = Sector or Beneficiary Group |
| Which subsidies and loans exist? | `scheme_benefits.benefit_type` |
| Which departments implement them? | `government_schemes.ministry` + `implementing_agencies` |
| Which documents are required? | `eligibility_criteria.verification_document_hint` → `required_documents` |
| How do I apply? | `application_process`, ordered by `step_number` |
| Which schemes are district-specific? | `district_scheme_mapping` (5 schemes × 61 districts) |
| Which agriculture / education / skill schemes are relevant? | the three domain mapping datasets |

## Cross-package integration

Nine distinct foreign key sets into five released packages — the widest cross-package surface in
the knowledge base. All resolved against the upstream CSVs at generation time and re-checked on
every validation run:

| Upstream | Resolved | Sentinel |
|---|---|---|
| Package001 `district.dist_id` | {XF['Package001 district']['resolved']} | {XF['Package001 district']['sentinel']} |
| Package002 `scholarships.id` | {XF['Package002 scholarship']['resolved']} | {XF['Package002 scholarship']['sentinel']} |
| Package004 opportunity names | {XF['Package004 opportunity']['resolved']} | {XF['Package004 opportunity']['sentinel']} |
| Package005 `agriculture_schemes.scheme_id` | {XF['Package005 scheme']['resolved']} | {XF['Package005 scheme']['sentinel']} |
| Package005 `crops.crop_id` | {XF['Package005 crop']['resolved']} | {XF['Package005 crop']['sentinel']} |
| Package006 `government_skill_schemes.scheme_id` | {XF['Package006 scheme']['resolved']} | {XF['Package006 scheme']['sentinel']} |
| Package006 `skills.skill_id` | {XF['Package006 skill']['resolved']} | {XF['Package006 skill']['sentinel']} |
| Package006 `certifications.certification_id` | {XF['Package006 certification']['resolved']} | {XF['Package006 certification']['sentinel']} |
| Package006 `training_providers.provider_id` | {XF['Package006 provider']['resolved']} | {XF['Package006 provider']['sentinel']} |

**Zero unresolved.** Sentinels are honest absences where the upstream package has no counterpart
record — documented row by row in `validation_report.md`.

## Read this before using the data

**No monetary amount is asserted anywhere in this package.** Every benefit quantum, premium rate,
loan ceiling and subsidy percentage is the bare `PENDING_VERIFICATION` sentinel. Scheme amounts
are revised by notification and budget cycle, and a figure stated here would date badly in
precisely the field applicants rely on most. Every row carries `official_portal` — fetch the
current figure there.

**No processing timeline is asserted.** `application_process.typical_timeline` is the sentinel on
all 43 rows; no published service standard was confirmable except MGNREGA's statutory period.

**`priority_score` in `scheme_ai_recommendations` is a designed heuristic, not evidence.** It is a
deterministic function of eligibility overlap and sequencing logic, intended as a rule-engine
seed. There is no uptake or approval-rate data behind it. Confidence is 60 on every row — the
lowest in the package, deliberately.

**Nothing has had human review.** All {SUMMARY['total_records']} rows are `VST-NEEDS_REVIEW`.
Machine validation confirms structure, references and provenance; it does not confirm currency,
and currency is the binding risk for scheme data.

## Scope boundaries

- **All 40 schemes are Central.** State schemes for Telangana and Andhra Pradesh already live in
  Package002, Package003 and Package004; a reconciled state registry is a v1.1.0 target.
- **8 of 40 schemes have modelled application workflows**; the rest are single-step or lack
  documented multi-stage processes.
- **5 of 40 schemes have a district-mediated application step.** The other 35 are nationally
  administered, and padding them across 61 districts would assert a district dimension that does
  not exist.
- **No hard foreign key into Package003_Healthcare.** AB PM-JAY declares the overlap in
  `also_in_package`, but `health_scheme_mapping.csv` is deferred to v1.1.0.

## Defects caught before release

Five classes, all by the validation checks. Two were cross-package foreign keys pointing at
upstream records that do not exist — including one case where a Package006 collection report
describes a skill the released dataset does not contain. Full detail in `validation_report.md`.

## Governance question this release surfaces

Five packages now hold scheme data: Package002 (25 scholarships), Package003 (9 health insurance),
Package004 (18 MSME support), Package005 (12 agriculture), Package006 (15 skill), and now
Package007 ({SUMMARY['schemes_registered']} cross-domain). `government_schemes.also_in_package`
declares every overlap so it is explicit and reconcilable — but declaring is not resolving. Either
Package007 becomes the single source of truth and the domain packages reference it, or the two
drift apart. See `quality_report.md` and `codex_handoff.md`.

## Files

```
Package007_Government_Schemes/
├── datasets/              15 released CSVs
├── metadata/              15 per-dataset metadata JSON files
├── reports/               15 per-dataset collection reports
├── schemas/               schema_catalog.json
├── registry/              dataset_registry.csv
├── docs/                  METHODOLOGY, USAGE, DATA_DICTIONARY, IMPORT_GUIDE
├── package_manifest.json
├── validation_report.md   validation_summary.json
├── quality_report.md
├── VERSION_HISTORY.md     RELEASE_NOTES.md  CHANGELOG.md  VERSION
├── codex_handoff.md
├── validate.py            12-check validation engine
└── gen_core.py  gen_mappings.py  build_artifacts.py  build_docs.py
```

Generator scripts ship with the package: the datasets are reproducible from source, and a reviewer
can see exactly what was asserted and what was left sentinelled.
"""
(PKG / "RELEASE_NOTES.md").write_text(rn)
print("RELEASE_NOTES.md")
print("\nDocumentation build complete.")
