#!/usr/bin/env python3
"""
The Electrician & Allied Trades career dataset, normalised.

WHAT THIS FILE IS
-----------------
A 36-page DeepSeek-generated PDF covering 20 skilled-trade careers, extracted
and turned into structured records. It is a RESEARCH SOURCE, not knowledge:
nothing here reaches a reader until a person has reviewed it.

WHY IT LIVES IN research/ AND NOT IN packages/
-----------------------------------------------
`packages/` is the source of truth and everything in it is published. This
document cannot go there directly, for three reasons the document states about
itself:

  · "Contacts replaced with placeholder XXXX; verify from official websites."
    Five training institutes are listed with literal `XXXX` phone numbers.
  · "Confidence is moderate for salary and fees, based on typical ranges."
    Every salary band and course fee is an estimate, not a citation.
  · It is LLM output. It contains its own meta-commentary — "I will now
    generate datasets for the remaining 18 roles", "Due to length constraints"
    — which is the author narrating, not a source reporting.

So it is treated the way the collection framework treats any feed: a source
that produces CANDIDATES. `collection.cli review/approve` is the only path from
here into a package, and `VST-NEEDS_REVIEW` is the only verification status
anything derived from it may carry.

THE TELUGU IN THE PDF IS DAMAGED AND IS NOT USED
------------------------------------------------
PDF text extraction dropped the conjunct clusters. The document's own Telugu
for "electrician" extracts as `ఎలక` — three characters of a nine-character
word. `టెక్నీషియన్` becomes `టెక`, `వ్యక్తి` becomes `వ్యక`. Copying any of it
into the search vocabulary would poison the index with strings no reader will
ever type.

Every Telugu string below is therefore either (a) already present and correct
in `frontend/lib/search/vocabulary/concepts.js`, or (b) one of the few phrases
that survived extraction intact, verified character by character. Where neither
holds, the field is absent rather than guessed. `tests/test_trade_vocabulary.py`
re-checks every one against the live transliteration layer.

CONFIDENCE
----------
`confidence` is per-record and follows the repository's existing scale. Nothing
here exceeds 60: the ceiling for a single uncorroborated secondary source. Role
names, alternative titles and career ladders are the most reliable content in
the document — they are trade vocabulary, checkable against DGT trade lists.
Salaries, fees and institute contacts are the least.
"""

#: What the document is, for provenance on every row derived from it.
SOURCE = {
    "source_id": "doc-electrician-trades-2026",
    "title": "Electrician and Similar Role Career Decision Dataset",
    "kind": "DATASET",
    "origin": "DeepSeek-generated research document, supplied by the maintainer",
    "pages": 36,
    "retrieved": "2026-08-07",
    "self_declared_limits": [
        "contacts replaced with placeholder XXXX",
        "confidence is moderate for salary and fees, based on typical ranges",
    ],
    #: No URL: this is a supplied file, not a fetched page. Rows carry
    #: PENDING_VERIFICATION for source_url rather than a fabricated link.
    "url": "",
}

#: Fields the document supplies but which no reader may see until researched
#: against a primary source. Named here so the promoter can blank them
#: mechanically rather than relying on anyone to remember.
UNVERIFIED_FIELDS = ("salary_range", "course_fees", "institute_contact",
                     "institute_website", "placement_claim")

# ─────────────────────────────────────────────────────────────────────────────
# The twenty roles.
#
# `existing` names the Skill entity in the graph this role maps to, or None if
# the role is new. Determined by reading knowledge_graph/entities/entities.csv,
# not by guessing from the name — `Painter` looked new and has a
# BusinessOpportunity but no Skill; `Tile & Marble Fixer` the same.
#
# `aliases`  — alternative job titles the document lists, plus employer terms.
# `te`       — Telugu, ONLY where verified (see the module docstring).
# `tools`    — extracted verbatim; these are the most reliable factual content
#              in the document after the role names, because a multimeter is a
#              multimeter regardless of who wrote the page.
# `relates`  — the document's own "Related Careers" list, which is the richest
#              connected-knowledge signal it carries.
# ─────────────────────────────────────────────────────────────────────────────

ROLES = [
    {
        "slug": "electrician",
        "title": "Electrician",
        "existing": "Electrician (Domestic Wiring)",
        "aliases": ["Wireman", "Electrical Technician", "Maintenance Electrician",
                    "Industrial Electrician", "Domestic Electrician", "House Wiring"],
        "te": ["ఎలక్ట్రిషియన్", "వైర్‌మ్యాన్"],
        "industries": ["Construction", "Manufacturing", "Facility Management",
                       "Power", "Real Estate"],
        "nature": "Field/on-site, indoors and outdoors, physically active, sometimes at height",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Insulated screwdriver set", "Combination pliers", "Wire stripper",
                  "Digital multimeter", "Voltage tester (neon)", "Electrician knife",
                  "Claw hammer", "Fish tape (cable puller)", "Tool bag"],
        "skills_beginner": ["Wire splicing", "Basic tool handling",
                            "Electrical safety (shock, fire)", "Reading simple diagrams"],
        "skills_intermediate": ["Single and three-phase wiring", "Conduit bending",
                                "Switchgear installation", "Fault troubleshooting"],
        "skills_advanced": ["Panel design", "Industrial motor control", "PLC basics",
                            "Earthing and lightning protection", "Energy auditing"],
        "future_tech": ["Smart home wiring (IoT switches)", "EV charging installation",
                        "Solar PV integration and battery storage",
                        "Building Energy Management Systems", "Prefabricated wiring systems"],
        "ladder": ["Class 10", "ITI Electrician (2 years)", "Apprentice/Trainee",
                   "Junior Electrician", "Electrician", "Senior Electrician / Supervisor",
                   "Electrical Contractor", "Business Owner"],
        "relates": ["Wireman", "Industrial Electrician", "Solar PV Installer",
                    "Electrical Supervisor", "Electronics Mechanic",
                    "AC & Refrigeration Technician", "Lift Technician", "Panel Builder",
                    "Instrumentation Technician", "Cable Jointer",
                    "Home Automation Technician", "Maintenance Technician",
                    "Power Line Technician", "UPS/Inverter Service Engineer",
                    "EV Charging Station Technician"],
        "licence": "Electrical contractor licence from the state Electrical Inspectorate",
        "confidence": 60,
    },
    {
        "slug": "ev-technician",
        "title": "EV Technician",
        "existing": "EV Technician",
        "aliases": ["EV Service Technician", "Electric Vehicle Mechanic",
                    "EV Repair Specialist", "Battery Technician"],
        "te": [],
        "industries": ["Automotive", "EV OEMs", "Fleet operators", "Charging networks"],
        "nature": "Workshop-based, some roadside assistance, high-voltage safety",
        "future_demand": "Very high",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Insulated tools (CAT III)", "High voltage gloves and gear",
                  "Digital multimeter (CAT III)", "Diagnostic scan tool (OBD-II/CAN)",
                  "Battery cell tester/balancer", "Torque wrench", "Scissor lift / jack"],
        "skills_beginner": ["EV high-voltage safety", "Basic CAN bus", "Multimeter use",
                            "Two-wheeler disassembly"],
        "skills_intermediate": ["Battery management system diagnostics",
                                "Motor controller troubleshooting", "Firmware updates"],
        "skills_advanced": ["Battery cell replacement", "CAN data analysis",
                            "Thermal management", "Powertrain calibration",
                            "Charging protocols (CCS, CHAdeMO)"],
        "future_tech": ["Solid-state battery repair", "Battery swapping station technology",
                        "Vehicle-to-grid (V2G) integration", "Over-the-air diagnostics",
                        "AI-based predictive battery health"],
        "ladder": ["ITI/Diploma (Automobile/Electrical)", "EV Technician Trainee",
                   "Junior EV Technician", "EV Diagnostic Technician",
                   "Senior EV Technician / Service Advisor", "Workshop Supervisor",
                   "Independent EV Garage Owner"],
        "relates": ["Automobile Technician", "Mechatronics Technician",
                    "Battery Manufacturing Technician", "Charging Station Technician",
                    "Electric Motor Rewinder", "Industrial Automation Technician",
                    "Solar EV Charging Installer", "Fleet Maintenance Manager",
                    "Electric Bus Technician", "Hybrid Vehicle Specialist",
                    "Battery Recycling Technician", "Electronics Repair (PCB) Technician",
                    "Robotics Service Engineer"],
        "licence": "No separate licence; OEM certification helps",
        "confidence": 60,
    },
    {
        "slug": "lift-technician",
        "title": "Lift Technician",
        "existing": None,
        "aliases": ["Elevator Mechanic", "Lift Engineer",
                    "Vertical Transportation Technician", "Escalator Technician"],
        "te": [],
        "industries": ["Real estate", "Infrastructure", "Metro rail", "Hospitality"],
        "nature": "Indoor and outdoor, mechanical and electrical, safety critical, work at height",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — annual maintenance contracts",
        "tools": ["Multimeter", "Wrench set", "Safety harness",
                  "Laptop with diagnostic software"],
        "skills_beginner": ["Basic tools", "Safety harness use", "Wiring"],
        "skills_intermediate": ["Controller logic", "Door operator repair"],
        "skills_advanced": ["VVVF drives", "CAN communication", "Hydraulic lifts",
                            "Lift modernisation"],
        "future_tech": ["IoT remote monitoring", "Destination control systems",
                        "Regenerative drives", "Touchless interfaces",
                        "Machine-room-less (MRL) lifts"],
        "ladder": ["ITI", "Apprentice", "Junior Technician", "Technician",
                   "Senior Technician / Supervisor", "AMC Contractor", "Business Owner"],
        "relates": ["Industrial Electrician", "Mechatronics Technician",
                    "Mechanical Fitter", "Industrial Automation Technician",
                    "Robotics Technician", "HVAC Technician",
                    "Building Maintenance Supervisor", "Metro Rail Technician",
                    "PLC Programmer", "Safety Inspector", "Welder", "Panel Builder",
                    "Field Service Engineer", "Smart Building Technician"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "solar-pv-installer",
        "title": "Solar PV Installer",
        "existing": "Solar Panel Installation & Maintenance",
        "aliases": ["Solar Technician", "Rooftop Solar Installer",
                    "PV System Integrator", "Suryamitra"],
        "te": [],
        "industries": ["Renewable Energy", "Construction", "EPC"],
        "nature": "Outdoor, at height, electrical and mechanical",
        "future_demand": "Very high",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Multimeter", "Crimping tool", "Torque wrench", "Drill machine",
                  "Safety belt", "MC4 tool kit"],
        "skills_beginner": ["Panel mounting", "Basic wiring", "Safety harness use"],
        "skills_intermediate": ["Inverter configuration", "String design", "Earthing",
                                "Net metering"],
        "skills_advanced": ["System design (PVsyst)", "Battery storage integration",
                            "Off-grid systems"],
        "future_tech": ["Bifacial panels", "Solar tracking",
                        "Building-integrated PV", "Battery storage",
                        "AI monitoring", "Floating solar"],
        "ladder": ["Suryamitra/ITI", "Installer Helper", "Solar Technician",
                   "Senior Technician", "Site Supervisor", "EPC Contractor",
                   "Business Owner"],
        "relates": ["Electrician", "Wireman", "Electronics Mechanic", "Energy Auditor",
                    "Solar Project Engineer", "Solar Panel Manufacturing Technician",
                    "Inverter Service Technician", "EV Solar Charger Installer",
                    "Solar Water Heater Technician", "Power System Technician",
                    "Maintenance Technician", "Grid Operator", "Battery Technician",
                    "Welder", "Roofer"],
        "licence": "PM Surya Ghar vendor registration for scheme work",
        "confidence": 60,
    },
    {
        "slug": "ac-refrigeration-technician",
        "title": "AC & Refrigeration Technician",
        "existing": "HVAC Technician",
        "aliases": ["HVAC Technician", "RAC Mechanic", "Cooling System Technician",
                    "AC Mechanic", "Fridge Mechanic"],
        "te": [],
        "industries": ["HVAC", "Appliances", "Facilities", "Cold Storage"],
        "nature": "Indoor and outdoor, mechanical and electrical, refrigerant handling",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Very high",
        "tools": ["Gauge manifold", "Vacuum pump", "Brazing torch", "Multimeter",
                  "Refrigerant scale"],
        "skills_beginner": ["Brazing", "Gas charging", "Basic electrical"],
        "skills_intermediate": ["Split AC installation", "Compressor replacement"],
        "skills_advanced": ["VRF systems", "Inverter AC", "Cold room design"],
        "future_tech": ["Inverter AC", "IoT predictive maintenance",
                        "Low-GWP refrigerants", "Solar hybrid AC"],
        "ladder": ["ITI RAC", "Apprentice", "Junior Technician", "Technician",
                   "Senior Technician / Supervisor", "AMC Contractor", "Owner"],
        "relates": ["Electrician", "Plumber", "Welder", "Facility Manager",
                    "Mechatronics Technician", "Solar Thermal Technician",
                    "Cold Chain Technician", "HVAC Design Engineer",
                    "Maintenance Technician", "Appliance Repair Technician",
                    "VRF/VRV Technician", "Building Automation Technician",
                    "Industrial Refrigeration Technician", "Energy Auditor"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "plumber",
        "title": "Plumber",
        "existing": "Plumbing",
        "aliases": ["Pipe Fitter", "Sanitary Installer", "Plumbing Technician"],
        "te": [],
        "industries": ["Construction", "Facilities", "Municipal"],
        "nature": "Indoor and outdoor, physical, wet conditions",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Very high",
        "tools": ["Pipe wrench set", "Pipe cutter", "Threading machine", "Blow torch"],
        "skills_beginner": ["Pipe cutting", "Threading", "Jointing"],
        "skills_intermediate": ["PPR and cPVC welding", "Drainage layout"],
        "skills_advanced": ["Plumbing system design", "Gas piping",
                            "Solar water heater installation"],
        "future_tech": ["Smart water meters", "Leak detection sensors", "PEX piping",
                        "Greywater recycling", "IoT in plumbing"],
        "ladder": ["Trainee Plumber", "Plumber", "Senior Plumber", "Contractor",
                   "Business Owner"],
        "relates": ["Pipe Fitter", "Fire Fighting Technician",
                    "Gas Pipeline Technician", "Water Treatment Plant Operator",
                    "Construction Supervisor", "Tile & Marble Fixer", "Mason",
                    "Facility Manager", "Solar Water Heater Installer", "Welder",
                    "HVAC Technician", "Steam Fitter"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "tile-marble-fixer",
        "title": "Tile & Marble Fixer",
        "existing": None,
        "aliases": ["Tile Setter", "Tile Mason", "Flooring Technician",
                    "Marble Polisher", "Tiles Fitter"],
        "te": [],
        "industries": ["Construction", "Interior fit-out"],
        "nature": "Physical, requires a design eye",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Trowel", "Spirit level", "Tile cutter", "Angle grinder"],
        "skills_beginner": ["Mixing mortar", "Levelling"],
        "skills_intermediate": ["Layout patterns", "Tile cutting"],
        "skills_advanced": ["Marble polishing", "Epoxy grouting",
                            "Large-format tiling"],
        "future_tech": ["Self-levelling compounds", "Digital layout tools",
                        "Large porcelain slabs"],
        "ladder": ["Helper", "Tile Fixer", "Senior Tile Fixer", "Contractor"],
        "relates": ["Mason", "Marble Polisher", "Carpenter", "Interior Fit-Out Technician",
                    "Plasterer", "Flooring Technician", "Waterproofing Technician",
                    "Granite Cutter"],
        "licence": "",
        "confidence": 50,
    },
    {
        "slug": "welder",
        "title": "Welder",
        "existing": "Welding (MIG/TIG/Arc)",
        "aliases": ["Fitter-Welder", "Arc Welder", "MIG Welder", "TIG Welder",
                    "Coded Welder"],
        "te": [],
        "industries": ["Manufacturing", "Construction", "Shipbuilding", "Oil and gas"],
        "nature": "Workshop and site, physical, heat and fumes",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Welding machine", "Welding helmet", "Gloves", "Angle grinder",
                  "Electrodes"],
        "skills_beginner": ["Arc welding", "Oxy-acetylene cutting"],
        "skills_intermediate": ["TIG welding", "MIG welding"],
        "skills_advanced": ["Pipe welding", "Underwater welding", "Robot welding"],
        "future_tech": ["Robotic welding operation", "Laser welding",
                        "Friction stir welding"],
        "ladder": ["ITI Welder", "Trainee", "Welder", "Coded Welder", "Supervisor",
                   "Fabrication Contractor"],
        "relates": ["Fabricator", "Fitter", "Sheet Metal Worker", "Pipe Fitter",
                    "Boilermaker", "CNC Operator", "Structural Erector",
                    "Welding Inspector", "Shipbuilding Technician"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "fabricator",
        "title": "Fabricator",
        "existing": None,
        "aliases": ["Structural Fabricator", "Sheet Metal Fabricator",
                    "Metal Fabricator"],
        "te": [],
        "industries": ["Construction", "Manufacturing"],
        "nature": "Workshop, physical, machine work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Cutting torch", "Welding machine", "Angle grinder",
                  "Bending machine"],
        "skills_beginner": ["Reading blueprints", "Gas cutting"],
        "skills_intermediate": ["Welding", "Sheet metal layout"],
        "skills_advanced": ["CNC press brake operation", "Laser cutting",
                            "CAD/CAM integration"],
        "future_tech": ["CNC press brake", "Laser cutting", "CAD/CAM integration"],
        "ladder": ["ITI Fitter/Welder", "Trainee", "Fabricator", "Supervisor",
                   "Unit Owner"],
        "relates": ["Welder", "Fitter", "CNC Operator", "Sheet Metal Worker",
                    "Machinist", "Pipe Fabricator", "Structural Erector",
                    "Boilermaker"],
        "licence": "",
        "confidence": 50,
    },
    {
        "slug": "carpenter",
        "title": "Carpenter",
        "existing": "Carpentry",
        "aliases": ["Woodworker", "Joiner", "Furniture Carpenter",
                    "Modular Kitchen Installer"],
        "te": ["వడ్రంగి"],
        "industries": ["Construction", "Interior fit-out", "Furniture"],
        "nature": "Workshop and site, physical, tool work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Hand saw", "Chisel set", "Plane", "Power drill", "Router"],
        "skills_beginner": ["Measuring", "Cutting", "Joinery"],
        "skills_intermediate": ["Power tool operation"],
        "skills_advanced": ["CAD design", "CNC wood router operation"],
        "future_tech": ["CNC machining", "Modular furniture", "Engineered wood"],
        "ladder": ["Helper", "Carpenter", "Master Carpenter", "Workshop Owner"],
        "relates": ["Furniture Designer", "Interior Fit-Out Technician", "Wood Turner",
                    "Plywood Technician", "Modular Kitchen Installer", "Joiner",
                    "Wood Carver"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "mason",
        "title": "Mason",
        "existing": "Masonry & Brickwork",
        "aliases": ["Brick Mason", "Construction Mason", "Mesthri", "Bricklayer"],
        "te": [],
        "industries": ["Construction", "Real estate", "Infrastructure"],
        "nature": "Site, outdoor, physical",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Trowel", "Plumb bob", "Spirit level"],
        "skills_beginner": ["Brick laying", "Plastering", "Levelling"],
        "skills_intermediate": ["Reading plans"],
        "skills_advanced": ["Concrete work supervision"],
        "future_tech": ["Autoclaved aerated concrete blocks", "Drywall",
                        "Prefabricated construction"],
        "ladder": ["Helper", "Mason", "Head Mason", "Contractor"],
        "relates": ["Concrete Worker", "Tile & Marble Fixer", "Plasterer",
                    "Steel Fixer", "Scaffolding Technician", "Building Supervisor"],
        "licence": "",
        "confidence": 50,
    },
    {
        "slug": "painter",
        "title": "Painter",
        "existing": None,
        "aliases": ["Building Painter", "Decorative Painter", "Industrial Painter",
                    "Wall Putty Applicator"],
        "te": [],
        "industries": ["Construction", "Facilities"],
        "nature": "Site, indoor and outdoor, at height",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "High",
        "tools": ["Brushes", "Rollers", "Spray gun", "Scaffolding"],
        "skills_beginner": ["Surface preparation", "Brush and roller work"],
        "skills_intermediate": ["Texture finishes", "Wood polish"],
        "skills_advanced": ["Industrial coatings", "Waterproofing"],
        "future_tech": ["Low-VOC paints", "Anti-bacterial coatings",
                        "Spray automation", "Electrostatic painting"],
        "ladder": ["Helper", "Painter", "Master Painter", "Contractor"],
        "relates": ["Wall Putty Applicator", "Waterproofing Technician", "Decorator",
                    "Polisher", "Sandblaster", "Industrial Coating Technician"],
        "licence": "",
        "confidence": 50,
    },
    {
        "slug": "steel-fixer",
        "title": "Steel Fixer",
        "existing": None,
        "aliases": ["Bar Bender", "Rebar Fixer", "Reinforcement Fixer"],
        "te": [],
        "industries": ["Construction", "Infrastructure"],
        "nature": "Site, outdoor, heavy physical",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium",
        "tools": ["Rebar cutter", "Rebar bender", "Tying hook"],
        "skills_beginner": ["Cutting", "Bending", "Tying"],
        "skills_intermediate": ["Reading bar bending schedules"],
        "skills_advanced": ["Cage assembly supervision"],
        "future_tech": ["Prefabricated reinforcement cages",
                        "Automated cutting and bending"],
        "ladder": ["Helper", "Steel Fixer", "Chargehand", "Contractor"],
        "relates": ["Mason", "Formwork Carpenter", "Welder", "Fabricator",
                    "Surveyor Assistant"],
        "licence": "",
        "confidence": 50,
    },
    {
        "slug": "scaffolding-technician",
        "title": "Scaffolding Technician",
        "existing": None,
        "aliases": ["Scaffolder", "Scaffold Erector"],
        "te": [],
        "industries": ["Construction", "Oil and gas", "Power plants", "Shipyards"],
        "nature": "Site, at height, safety critical",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — scaffolding rental and erection",
        "tools": ["Spanner set", "Spirit level", "Safety harness"],
        "skills_beginner": ["Assembly standards"],
        "skills_intermediate": ["Safe load calculation", "Tube and clamp systems"],
        "skills_advanced": ["Cuplock systems", "Complex access design"],
        "future_tech": ["Lightweight aluminium scaffolds", "Modular systems",
                        "Smart load sensors"],
        "ladder": ["Helper", "Scaffolder", "Advanced Scaffolder", "Supervisor",
                   "Contractor"],
        "relates": ["Rigger", "Construction Worker", "Steel Erector", "Painter",
                    "Insulator"],
        "licence": "CISRS-standard scaffolding certification for overseas work",
        "confidence": 50,
    },
    {
        "slug": "cnc-operator",
        "title": "CNC Machine Operator",
        "existing": "CNC Machine Operator",
        "aliases": ["CNC Machinist", "VMC Operator", "Turn-Mill Operator",
                    "CNC Programmer"],
        "te": [],
        "industries": ["Auto components", "Aerospace", "Die and mould",
                       "General engineering", "Defence PSUs"],
        "nature": "Workshop, machine-side, precision work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — CNC job shop, high capital",
        "tools": ["Employer-provided machine", "Measuring instruments"],
        "skills_beginner": ["G-code", "M-code", "Tool offsets"],
        "skills_intermediate": ["AutoCAD/CAM"],
        "skills_advanced": ["Five-axis programming", "Macro programming"],
        "future_tech": ["AI-based tool path optimisation", "Collaborative robots",
                        "Additive-subtractive hybrid machining", "Digital twin"],
        "ladder": ["ITI Machinist", "Operator", "Setup Programmer", "Supervisor",
                   "Unit Owner"],
        "relates": ["VMC Programmer", "Turn-Mill Operator", "Tool & Die Maker",
                    "Quality Inspector", "CAD/CAM Engineer", "Mechatronics Technician",
                    "Robotics Operator"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "machine-maintenance-technician",
        "title": "Machine Maintenance Technician",
        "existing": None,
        "aliases": ["Millwright", "Mechanical Fitter", "Maintenance Fitter",
                    "Plant Maintenance Technician"],
        "te": [],
        "industries": ["Manufacturing", "Process industries", "Pharma", "Cement"],
        "nature": "Plant floor, mechanical, shift work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — AMC services for small industry",
        "tools": ["Spanner set", "Dial gauge", "Hydraulic puller", "Multimeter"],
        "skills_beginner": ["Bearing fitting", "Shaft alignment"],
        "skills_intermediate": ["Hydraulics", "Pneumatics"],
        "skills_advanced": ["Vibration analysis", "Thermography"],
        "future_tech": ["Predictive maintenance with IoT sensors",
                        "AR-guided repair", "CMMS software"],
        "ladder": ["ITI Fitter", "Technician", "Senior Technician", "Planner",
                   "AMC Contractor"],
        "relates": ["Industrial Electrician", "Instrumentation Technician",
                    "Mechatronics Technician", "Welder", "Millwright",
                    "Plant Operator"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "industrial-electrician",
        "title": "Industrial Electrician",
        "existing": "Industrial Electrician",
        "aliases": ["Maintenance Electrician", "Electrical Fitter",
                    "Factory Electrician", "Plant Electrician"],
        "te": [],
        "industries": ["Steel", "Cement", "Pharma", "Auto", "Food processing"],
        "nature": "Plant floor, electrical, shift work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — industrial electrical AMC",
        "tools": ["Clamp meter", "Megger", "Phase sequence tester", "Tool kit"],
        "skills_beginner": ["Motor control", "Cable sizing"],
        "skills_intermediate": ["VFD configuration", "Earthing"],
        "skills_advanced": ["PLC wiring", "SCADA", "Switchgear"],
        "future_tech": ["Industrial IoT", "Energy management systems",
                        "Smart motor control centres"],
        "ladder": ["ITI Electrician", "Trainee", "Industrial Electrician",
                   "Senior Electrician", "Supervisor", "Contractor"],
        "relates": ["Industrial Automation Technician", "Instrumentation Technician",
                    "Panel Builder", "Solar PV Installer", "Lift Technician",
                    "HVAC Technician"],
        "licence": "",
        "confidence": 60,
    },
    {
        "slug": "industrial-automation-technician",
        "title": "Industrial Automation Technician (PLC)",
        "existing": "PLC Programming & Control Systems",
        "aliases": ["PLC Programmer", "Automation Technician", "SCADA Technician",
                    "Control Systems Technician"],
        "te": [],
        "industries": ["Auto", "Pharma", "FMCG", "System integrators"],
        "nature": "Plant floor and workshop, programming and wiring",
        "future_demand": "Very high",
        "automation_risk": "Low",
        "entrepreneurship": "High — automation project contracting, panel building",
        "tools": ["Laptop with PLC software", "Multimeter", "Communication cables"],
        "skills_beginner": ["Ladder logic", "Control wiring"],
        "skills_intermediate": ["HMI design"],
        "skills_advanced": ["SCADA", "VFD and servo drives", "Industrial IoT"],
        "future_tech": ["Edge computing", "AI in PLC", "OPC UA", "Digital twins",
                        "OT cybersecurity"],
        "ladder": ["ITI/Diploma", "Automation Technician", "PLC Programmer",
                   "Automation Engineer", "Project Lead", "Independent Integrator"],
        "relates": ["Robotics Technician", "Mechatronics Technician",
                    "Industrial Electrician", "Instrumentation Technician",
                    "Control System Engineer"],
        "licence": "",
        "confidence": 60,
    },
    {
        "slug": "mechatronics-technician",
        "title": "Mechatronics Technician",
        "existing": None,
        "aliases": ["Mechatronics Engineer (Technician)", "Multi-skilled Technician"],
        "te": [],
        "industries": ["Automotive", "Packaging", "FMCG", "Machine builders"],
        "nature": "Plant floor, combined mechanical/electrical/control work",
        "future_demand": "High",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — machine automation and maintenance service",
        "tools": ["Laptop with automation software", "Multimeter", "Tool kit"],
        "skills_beginner": ["Pneumatics", "Sensors"],
        "skills_intermediate": ["PLC", "Motor drives"],
        "skills_advanced": ["Robotics", "Machine vision", "IoT"],
        "future_tech": ["Digital twin", "Collaborative robots",
                        "Machine learning for predictive control"],
        "ladder": ["ITI/Diploma Mechatronics", "Technician", "Senior Technician",
                   "Engineer", "Integrator"],
        "relates": ["Industrial Automation Technician", "Robotics Technician",
                    "Machine Maintenance Technician", "Instrumentation Technician",
                    "CNC Machine Operator", "Industrial Electrician"],
        "licence": "",
        "confidence": 55,
    },
    {
        "slug": "robotics-technician",
        "title": "Robotics Technician",
        "existing": "Industrial Robotics",
        "aliases": ["Robot Programmer", "Robotics Service Engineer",
                    "Robot Maintenance Technician"],
        "te": [],
        "industries": ["Industry 4.0", "Automotive", "System integrators"],
        "nature": "Plant floor, programming and service",
        "future_demand": "Very high",
        "automation_risk": "Low",
        "entrepreneurship": "Medium — robot service and integration, high capital",
        "tools": ["Laptop", "Simulation software licence", "Basic tool kit"],
        "skills_beginner": ["Robot kinematics", "Teach pendant programming"],
        "skills_intermediate": ["Offline simulation (RoboDK)"],
        "skills_advanced": ["Vision integration", "AI path planning"],
        "future_tech": ["Collaborative robots (cobots)", "AI-based grasping",
                        "Mobile robots and AGVs", "Swarm robotics"],
        "ladder": ["ITI/Diploma", "Robotics Technician", "Robot Programmer",
                   "Application Engineer", "Integrator", "Owner"],
        "relates": ["Mechatronics Technician", "PLC Programmer", "Robot Welder",
                    "Industrial Automation Technician", "Machine Vision Technician"],
        "licence": "",
        "confidence": 55,
    },
]

#: Government schemes the document names for these trades. Every one of these
#: already exists in Package007 or is a well-known central scheme — they are
#: NOT new knowledge, they are EDGES: this trade connects to that scheme.
SCHEMES_NAMED = [
    "PMEGP", "Mudra Loan (PMMY)", "Stand-Up India", "PMKVY", "Skill India",
    "NSDC placement-linked training", "PM Surya Ghar: Muft Bijli Yojana",
    "PM-KUSUM", "FAME II", "NAPS (National Apprenticeship Promotion Scheme)",
    "T-PRIDE (Telangana)", "TS MSME schemes", "APSSDC", "YSR Navodayam",
    "Jal Jeevan Mission", "AMRUT", "Udyam registration",
]

#: Institutions named. Kept as NAMES ONLY — the document's contact numbers are
#: literal `XXXX` placeholders and its fee figures are self-declared estimates,
#: so a row here would be a fabricated directory entry.
PROVIDERS_NAMED = [
    "Government ITI (Telangana)", "Government ITI (Andhra Pradesh)",
    "Don Bosco Tech", "Nettur Technical Training Foundation (NTTF)",
    "TASK (Telangana Academy for Skill and Knowledge)", "APSSDC",
    "National Institute of Solar Energy (NISE)", "CITD Hyderabad",
    "Apollo MedSkills", "EV Tech Academy", "Autobot India",
]

#: Official references the document cites. These ARE verifiable — they are
#: well-known government domains — and are the right seeds for the RSS
#: collection framework.
OFFICIAL_REFERENCES = {
    "NSDC": "https://nsdcindia.org",
    "Skill India": "https://skillindia.gov.in",
    "PMKVY": "https://pmkvyofficial.org",
    "Ministry of Skill Development": "https://msde.gov.in",
    "Directorate General of Training": "https://dgt.gov.in",
    "ITI Telangana": "https://ititelangana.gov.in",
    "ITI Andhra Pradesh": "https://itiap.gov.in",
    "NAPS": "https://apprenticeshipindia.gov.in",
    "TSSPDCL": "https://tssouthernpower.com",
    "APEPDCL": "https://apeasternpower.com",
    "ASDC": "https://asdc.org.in",
    "TASK Telangana": "https://task.telangana.gov.in",
    "APSSDC": "https://apssdc.in",
    "MNRE": "https://mnre.gov.in",
    "NISE": "https://nise.res.in",
    "TSREDCO": "https://tsredco.telangana.gov.in",
    "NREDCAP": "https://nredcap.in",
}


def new_roles():
    """The seven roles with no Skill entity in the graph."""
    return [r for r in ROLES if r["existing"] is None]


def merge_roles():
    """The thirteen that map onto an existing Skill and must enrich, not replace."""
    return [r for r in ROLES if r["existing"] is not None]
