#!/usr/bin/env python3
"""
Generate the Supabase DDL from the table specs.

The schema is generated rather than hand-written for the same reason the packages
generate their artifacts: a hand-written migration and a spec drift apart, and the
drift is invisible until a sync fails at 3am. Here the spec is the single
declaration and the SQL is derived from it, so adding a column is one edit.

    python3 knowledge_sync/generate_migration.py            # write the file
    python3 knowledge_sync/generate_migration.py --check    # CI: exit 1 on drift
    python3 knowledge_sync/generate_migration.py --stdout
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from knowledge_sync.config import (SYNC_COLUMNS, TABLE_SPECS,        # noqa: E402
                                   TARGET_SCHEMA)
from knowledge_sync.transform import column_kind                     # noqa: E402

OUT = Path(__file__).resolve().parent / "migrations" / "001_knowledge_schema.sql"

PG_TYPE = {"integer": "integer", "numeric": "numeric", "date": "date", "text": "text"}


def column_ddl(spec, name):
    pg = PG_TYPE[column_kind(name)]
    not_null = " not null" if name in spec.required else ""
    return f"  {name:<28} {pg}{not_null}"


def table_ddl(spec):
    lines = [f"-- {spec.description}"]
    srcs = ", ".join(f"{s.package}/{s.dataset}" for s in spec.sources)
    lines.append(f"-- source: {srcs}")
    if spec.owner_package:
        lines.append(f"-- owner:  {spec.owner_package}")
    lines.append(f"create table if not exists {TARGET_SCHEMA}.{spec.name} (")

    body = ["  sync_row_key                 text primary key"]
    body += [column_ddl(spec, c) for c in spec.columns]
    body += [
        "  sync_source_package          text not null",
        "  sync_source_dataset          text not null",
        "  sync_source_row_id           text not null",
        "  sync_content_hash            text not null",
        "  sync_pending_fields          jsonb not null default '{}'::jsonb",
        "  sync_version                 text not null",
        "  sync_synced_at               timestamptz not null default now()",
        "  sync_deleted_at              timestamptz",
    ]
    lines.append(",\n".join(body))
    lines.append(");")

    # Live rows are what every application query wants; the partial index keeps
    # soft-deleted rows out of the common path without a second table.
    lines.append(f"create index if not exists {spec.name}_live_idx")
    lines.append(f"  on {TARGET_SCHEMA}.{spec.name} (sync_row_key)")
    lines.append("  where sync_deleted_at is null;")
    lines.append(f"create index if not exists {spec.name}_source_idx")
    lines.append(f"  on {TARGET_SCHEMA}.{spec.name} (sync_source_package, "
                 f"sync_source_dataset);")

    for column, target_table, target_column in spec.foreign_keys:
        lines.append(f"create index if not exists {spec.name}_{column}_idx")
        lines.append(f"  on {TARGET_SCHEMA}.{spec.name} ({column});")
    for column in ("entity_type", "canonical_name", "category_name", "district_name",
                   "skill_name", "scheme_name", "business_name", "crop_name",
                   "relationship_type", "st_id", "business_kind"):
        if column in spec.columns:
            lines.append(f"create index if not exists {spec.name}_{column}_idx")
            lines.append(f"  on {TARGET_SCHEMA}.{spec.name} ({column});")
    return "\n".join(lines)


def rls_ddl(spec):
    return f"""alter table {TARGET_SCHEMA}.{spec.name} enable row level security;

drop policy if exists "{spec.name} public read" on {TARGET_SCHEMA}.{spec.name};
create policy "{spec.name} public read"
  on {TARGET_SCHEMA}.{spec.name} for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention."""


def render():
    n_tables = len(TABLE_SPECS)
    parts = [f"""-- ValueWeave Knowledge Schema (Platform v3.0, Step 1)
-- GENERATED by knowledge_sync/generate_migration.py — do not edit by hand.
-- Re-generate after changing knowledge_sync/config.py; CI checks for drift.
--
-- WHY A SEPARATE SCHEMA
-- ---------------------
-- Three of the eight table names this framework needs — kg_skills, kg_schemes and
-- kg_relationships — already exist in `public` as admin-authored CMS tables with
-- different columns, different RLS and a different purpose. Putting the
-- projection in its own schema gives the tables their intended names while
-- guaranteeing that no existing application table is opened, and makes
--
--     drop schema {TARGET_SCHEMA} cascade;
--
-- a complete rollback that cannot reach user data.
--
-- WHAT IS IN EVERY TABLE
-- ----------------------
--   sync_row_key         stable key; the primary key
--   sync_source_*        the package, dataset and row this came from
--   sync_content_hash    change detection; excludes the sync_* columns
--   sync_pending_fields  {{column: sentinel}} — WHICH values are unknown and WHY
--   sync_deleted_at      soft delete; rows are never removed by a sync
--
-- {n_tables} tables. Git remains the single source of truth; this schema is a
-- read-optimised cache and may be dropped and rebuilt at any time.

create schema if not exists {TARGET_SCHEMA};
comment on schema {TARGET_SCHEMA} is
  'Read-only projection of the Git knowledge repository. Written only by '
  'knowledge_sync using the service role. Never edit rows here: Git is canonical.';

-- Read access for the application. Writes are not granted to anyone: the sync
-- uses the service role, which bypasses grants and RLS alike.
grant usage on schema {TARGET_SCHEMA} to anon, authenticated;
"""]

    for spec in TABLE_SPECS:
        parts.append("\n" + "-" * 74)
        parts.append(table_ddl(spec))

    parts.append("\n" + "-" * 74)
    parts.append("-- Row level security\n")
    for spec in TABLE_SPECS:
        parts.append(rls_ddl(spec) + "\n")

    parts.append("-" * 74)
    parts.append(f"""-- Default grants for tables created above, plus anything added later.
grant select on all tables in schema {TARGET_SCHEMA} to anon, authenticated;
alter default privileges in schema {TARGET_SCHEMA}
  grant select on tables to anon, authenticated;

-- Sync bookkeeping. One row per run, so an operator can answer "what happened on
-- the 14th" from SQL rather than from a log file on whichever machine ran it.
create table if not exists {TARGET_SCHEMA}.sync_runs (
  run_id            text primary key,
  mode              text not null,
  outcome           text not null,
  version           text,
  started_at        timestamptz not null,
  finished_at       timestamptz,
  duration_seconds  numeric,
  rows_inserted     integer not null default 0,
  rows_updated      integer not null default 0,
  rows_deleted      integer not null default 0,
  rows_skipped      integer not null default 0,
  validation_errors integer not null default 0,
  metrics           jsonb not null default '{{}}'::jsonb
);
create index if not exists sync_runs_started_idx
  on {TARGET_SCHEMA}.sync_runs (started_at desc);

alter table {TARGET_SCHEMA}.sync_runs enable row level security;
drop policy if exists "sync runs admin read" on {TARGET_SCHEMA}.sync_runs;
create policy "sync runs admin read"
  on {TARGET_SCHEMA}.sync_runs for select
  using (public.is_valueweave_admin());
""")
    return "\n".join(parts) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    sql = render()
    if args.stdout:
        print(sql)
        sys.exit(0)
    if args.check:
        if not OUT.exists():
            print(f"{OUT} is missing — run without --check", file=sys.stderr)
            sys.exit(1)
        if OUT.read_text(encoding="utf-8") != sql:
            print(f"{OUT.name} differs from a fresh generation. "
                  f"Run without --check to regenerate.", file=sys.stderr)
            sys.exit(1)
        print(f"  {OUT.name}: matches the specs")
        sys.exit(0)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path(__file__).resolve().parent.parent)} "
          f"({len(sql.splitlines())} lines, {len(TABLE_SPECS)} tables)")
