// ValueWeave — Static district profiles (District Intelligence).
// 14 districts: 8 Telangana + 6 Andhra Pradesh.
// `ideaSlug` values reference real entries in lib/idea-library/ideas.json so
// district pages deep-link into the existing Idea Library.
// `relatedArticleSlugs` reference content/research/*.mdx — unknown slugs are
// silently ignored, so future articles can be pre-wired here.

export const DISTRICTS = [
  // ─── TELANGANA ───
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    population: 10500000,
    populationLabel: "1.05 Cr",
    region: "Greater Hyderabad",
    headquartersCity: "Hyderabad",
    profileSummary:
      "Hyderabad is South India's technology and pharma powerhouse — HITEC City, Genome Valley, and a deep startup ecosystem. For builders, the play is services and supply chains that ride the city's growth: food, logistics, wellness, events, and B2B services for thousands of SMBs.",
    keyIndustries: [
      { name: "IT & Software Services", description: "HITEC City and the Financial District anchor 9 lakh+ tech jobs", employmentShare: "22%" },
      { name: "Pharmaceuticals & Life Sciences", description: "Genome Valley — Asia's largest pharma cluster", employmentShare: "12%" },
      { name: "Real Estate & Construction", description: "Sustained westward expansion and infrastructure spend", employmentShare: "14%" },
      { name: "Retail, Food & Hospitality", description: "India's fastest-growing food delivery and dining market", employmentShare: "18%" },
    ],
    emergingSectors: [
      { name: "AI & Digital Services for SMBs", growthSignal: "high", description: "Lakhs of undigitised businesses need websites, chatbots, and marketing", investmentRange: "₹1L–₹7L" },
      { name: "Corporate Wellness & Fitness", growthSignal: "high", description: "IT corridor employers buying wellness programmes for retention", investmentRange: "₹2L–₹6L" },
      { name: "EV Charging & Services", growthSignal: "high", description: "Highest EV registrations in the state, infrastructure lagging", investmentRange: "₹5L–₹20L" },
      { name: "Elder & Home Care", growthSignal: "medium", description: "NRI families paying for organised parent care back home", investmentRange: "₹2L–₹5L" },
    ],
    topOpportunities: [
      { title: "Vernacular AI Chatbot Agency", sector: "Digital Services", fitScore: 91, investmentRange: "₹3L–₹7L", demandScore: 90, teamSize: "2–4", ideaSlug: "vernacular-ai-chatbot-agency" },
      { title: "Corporate Wellness Programme Provider", sector: "Wellness", fitScore: 88, investmentRange: "₹2L–₹5L", demandScore: 87, teamSize: "2–4", ideaSlug: "corporate-wellness-programme-provider" },
      { title: "Elder Care Home Assistance", sector: "Healthcare", fitScore: 86, investmentRange: "₹2L–₹5L", demandScore: 89, teamSize: "4–8", ideaSlug: "elder-care-home-assistance-service" },
      { title: "EV Charging Hub", sector: "Energy", fitScore: 84, investmentRange: "₹5L–₹20L", demandScore: 88, teamSize: "2–5", ideaSlug: "ev-charging-hub" },
      { title: "Esports Café & Gaming Zone", sector: "Entertainment", fitScore: 81, investmentRange: "₹5L–₹15L", demandScore: 84, teamSize: "3–6", ideaSlug: "esports-caf-and-gaming-zone" },
    ],
    skillsDemand: [
      { skill: "AI / Web Development", demandLevel: "high", sector: "Technology" },
      { skill: "Digital Marketing", demandLevel: "high", sector: "Services" },
      { skill: "Caregiving (Trained)", demandLevel: "high", sector: "Healthcare" },
      { skill: "EV Technician", demandLevel: "medium", sector: "Automotive" },
      { skill: "Event Management", demandLevel: "medium", sector: "Hospitality" },
    ],
    governmentSchemes: [
      { name: "T-Hub / WE Hub Incubation", authority: "Telangana Govt", benefit: "Incubation, mentorship, and investor access for startups", eligibility: "Early-stage startups; WE Hub for women founders" },
      { name: "TS-iPASS", authority: "Telangana Govt", benefit: "Single-window industrial clearance in 15 days", eligibility: "All industries", url: "https://ipass.telangana.gov.in" },
      { name: "PMEGP", authority: "KVIC / DIC", benefit: "Margin money subsidy up to 35%", eligibility: "First-generation entrepreneurs" },
    ],
    demographics: { literacyRate: "83.3%", urbanRuralRatio: "100:0", youthPopulation: "35% under 25", mainLanguages: ["Telugu", "Urdu", "Hindi", "English"] },
    infrastructure: {
      connectivity: "ORR + NH-44/NH-65; metro rail; near-universal fibre broadband",
      nearestAirport: "Rajiv Gandhi International Airport (in-district)",
      nearestRailwayHub: "Secunderabad Junction (in-city)",
      industrialAreas: ["HITEC City", "Genome Valley", "Jeedimetla", "Patancheru"],
    },
    relatedArticleSlugs: ["ev-charging-business-telangana"],
  },
  {
    slug: "medak",
    name: "Medak",
    state: "Telangana",
    population: 769000,
    populationLabel: "7.69 Lakh",
    region: "North Telangana",
    headquartersCity: "Medak",
    profileSummary:
      "Medak district sits at the agricultural and industrial crossroads of Telangana, home to major pharmaceutical plants, a significant cement industry, and a rapidly growing dairy economy. Its proximity to Hyderabad (60 km) makes it a prime location for agro-processing, cold chain logistics, and contract manufacturing.",
    keyIndustries: [
      { name: "Pharmaceuticals", description: "Several large API and formulation units near Narsapur and Patancheru", employmentShare: "18%" },
      { name: "Cement & Construction", description: "Kesoram Cement and associated supply chain", employmentShare: "12%" },
      { name: "Agriculture", description: "Rice, maize, red gram, and floriculture exports", employmentShare: "55%" },
      { name: "Dairy", description: "Milk cooperatives and processing units supplying Hyderabad", employmentShare: "8%" },
    ],
    emergingSectors: [
      { name: "Cold Chain Logistics", growthSignal: "high", description: "Vegetable and flower supply chains to Hyderabad lack organized cold storage", investmentRange: "₹10L–₹50L" },
      { name: "Agro-Processing", growthSignal: "high", description: "Dal mills, rice bran oil, and value-added grain processing", investmentRange: "₹5L–₹30L" },
      { name: "Renewable Energy", growthSignal: "medium", description: "Solar irrigation pumps and rooftop solar for industries", investmentRange: "₹3L–₹20L" },
      { name: "Healthcare Services", growthSignal: "medium", description: "Diagnostic centres and pharmacy chains underserved in rural mandals", investmentRange: "₹5L–₹25L" },
    ],
    topOpportunities: [
      { title: "Micro Cold Storage as a Service", sector: "Logistics", fitScore: 88, investmentRange: "₹8L–₹15L", demandScore: 92, teamSize: "3–6", ideaSlug: "micro-cold-storage-as-a-service" },
      { title: "Premium Organic Produce Supply", sector: "Agriculture", fitScore: 85, investmentRange: "₹4L–₹10L", demandScore: 88, teamSize: "2–4", ideaSlug: "premium-organic-produce-store" },
      { title: "Diagnostic Sample Collection Hub", sector: "Healthcare", fitScore: 82, investmentRange: "₹1L–₹3L", demandScore: 86, teamSize: "2–3", ideaSlug: "diagnostic-sample-collection-hub" },
      { title: "Cold Chain Logistics for Pharma & Dairy", sector: "Logistics", fitScore: 80, investmentRange: "₹10L–₹20L", demandScore: 85, teamSize: "4–8", ideaSlug: "cold-chain-logistics-for-pharma-and-dairy" },
      { title: "Industrial Energy Audit Service", sector: "Energy", fitScore: 78, investmentRange: "₹2L–₹5L", demandScore: 80, teamSize: "2–3", ideaSlug: "industrial-energy-audit-service" },
    ],
    skillsDemand: [
      { skill: "Cold Chain Operations", demandLevel: "high", sector: "Logistics" },
      { skill: "Agricultural Extension", demandLevel: "high", sector: "Agriculture" },
      { skill: "Lab Technician", demandLevel: "medium", sector: "Healthcare" },
      { skill: "Solar Technician", demandLevel: "medium", sector: "Energy" },
      { skill: "Food Processing Operator", demandLevel: "medium", sector: "Manufacturing" },
    ],
    governmentSchemes: [
      { name: "PM Kisan Sampada Yojana", authority: "Ministry of Food Processing", benefit: "50% subsidy on agro-processing equipment", eligibility: "Food processing entrepreneurs", url: "https://pmksy.gov.in" },
      { name: "TS-iPASS", authority: "Telangana Government", benefit: "Single-window clearance for industrial units", eligibility: "All industries in Telangana", url: "https://ipass.telangana.gov.in" },
      { name: "PMEGP", authority: "KVIC / District Industries Centre", benefit: "Margin money subsidy up to 35%", eligibility: "SC/ST/Women/Rural entrepreneurs" },
      { name: "Rythu Bandhu", authority: "Telangana Govt", benefit: "₹5,000/acre/season investment support", eligibility: "Registered farmers in Telangana" },
    ],
    demographics: { literacyRate: "66.5%", urbanRuralRatio: "22:78", youthPopulation: "28% under 25", mainLanguages: ["Telugu", "Urdu"] },
    infrastructure: {
      connectivity: "NH-44 and NH-65 pass through district; broadband via BharatNet in 60% of GPs",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (65 km)",
      nearestRailwayHub: "Secunderabad (70 km)",
      industrialAreas: ["TSIIC Narsapur", "Patancheru Industrial Area"],
    },
    relatedArticleSlugs: ["rural-diagnostic-centers-india"],
  },
  {
    slug: "sangareddy",
    name: "Sangareddy",
    state: "Telangana",
    population: 1527000,
    populationLabel: "15.27 Lakh",
    region: "West Telangana",
    headquartersCity: "Sangareddy",
    profileSummary:
      "Sangareddy hosts Telangana's heaviest industrial belt — Patancheru, Bollaram, and IIT Hyderabad at Kandi. A rare mix of large-plant supply-chain demand, an educated young workforce, and an agricultural hinterland makes it ideal for industrial services, B2B supply, and skill businesses.",
    keyIndustries: [
      { name: "Heavy & Chemical Industry", description: "Patancheru–Bollaram belt: pharma, chemicals, engineering plants", employmentShare: "25%" },
      { name: "Education & Research", description: "IIT Hyderabad, GITAM, and a dense college cluster", employmentShare: "8%" },
      { name: "Agriculture", description: "Sugarcane, maize, vegetables for the Hyderabad market", employmentShare: "45%" },
      { name: "Logistics & Warehousing", description: "NH-65 corridor warehousing serving Hyderabad west", employmentShare: "10%" },
    ],
    emergingSectors: [
      { name: "Industrial B2B Services", growthSignal: "high", description: "Plant maintenance, safety audits, packaging, and staffing for 1,000+ units", investmentRange: "₹2L–₹10L" },
      { name: "Environmental Services", growthSignal: "high", description: "Effluent treatment, e-waste, and compliance services around the industrial belt", investmentRange: "₹3L–₹20L" },
      { name: "Student Economy", growthSignal: "medium", description: "Housing, food, and services around IIT-H and college campuses", investmentRange: "₹2L–₹8L" },
    ],
    topOpportunities: [
      { title: "Industrial Energy Audit Service", sector: "Energy", fitScore: 90, investmentRange: "₹2L–₹5L", demandScore: 88, teamSize: "2–3", ideaSlug: "industrial-energy-audit-service" },
      { title: "E-Waste Collection & Recycling Hub", sector: "Climate", fitScore: 86, investmentRange: "₹3L–₹8L", demandScore: 85, teamSize: "3–5", ideaSlug: "e-waste-collection-and-recycling-hub" },
      { title: "Custom Uniform Manufacturing", sector: "Textile", fitScore: 83, investmentRange: "₹5L–₹12L", demandScore: 84, teamSize: "5–10", ideaSlug: "custom-uniform-manufacturing" },
      { title: "Corporate Team Outing Organiser", sector: "Events", fitScore: 80, investmentRange: "₹2L–₹6L", demandScore: 79, teamSize: "2–4", ideaSlug: "corporate-team-outing-organiser" },
      { title: "Cloud Kitchen (Campus & Industrial)", sector: "Food", fitScore: 78, investmentRange: "₹3L–₹7L", demandScore: 82, teamSize: "3–5", ideaSlug: "cloud-kitchen-for-regional-cuisine" },
    ],
    skillsDemand: [
      { skill: "Industrial Electrician", demandLevel: "high", sector: "Manufacturing" },
      { skill: "EHS / Compliance", demandLevel: "high", sector: "Industry" },
      { skill: "Logistics Coordination", demandLevel: "medium", sector: "Warehousing" },
      { skill: "Tailoring (Industrial)", demandLevel: "medium", sector: "Textiles" },
    ],
    governmentSchemes: [
      { name: "TS-iPASS", authority: "Telangana Govt", benefit: "Fast-track industrial clearance", eligibility: "All enterprises", url: "https://ipass.telangana.gov.in" },
      { name: "MSME CGTMSE", authority: "SIDBI / Banks", benefit: "Collateral-free loans up to ₹2 Cr", eligibility: "Registered MSMEs" },
      { name: "PMEGP", authority: "KVIC / DIC", benefit: "Margin money subsidy up to 35%", eligibility: "New micro-enterprises" },
    ],
    demographics: { literacyRate: "64.0%", urbanRuralRatio: "30:70", youthPopulation: "30% under 25", mainLanguages: ["Telugu", "Urdu"] },
    infrastructure: {
      connectivity: "NH-65 (Hyderabad–Mumbai) spine; ORR access at Patancheru",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (70 km)",
      nearestRailwayHub: "Secunderabad (55 km)",
      industrialAreas: ["Patancheru", "Bollaram", "IDA Sangareddy"],
    },
    relatedArticleSlugs: [],
  },
  {
    slug: "siddipet",
    name: "Siddipet",
    state: "Telangana",
    population: 1012000,
    populationLabel: "10.12 Lakh",
    region: "North Telangana",
    headquartersCity: "Siddipet",
    profileSummary:
      "Siddipet is one of Telangana's fastest-improving agricultural districts — anchored by the Kaleshwaram irrigation network, a strong paddy and vegetable economy, and an administration known for civic execution. The opportunity is agri value-addition, rural services, and first-mover organised retail.",
    keyIndustries: [
      { name: "Agriculture & Irrigation", description: "Paddy, maize, vegetables on newly irrigated command areas", employmentShare: "60%" },
      { name: "Handlooms", description: "Siddipet gollabhama sarees — GI-tagged weaving tradition", employmentShare: "6%" },
      { name: "Trade & Services", description: "Mandal-town retail, transport, and government services", employmentShare: "20%" },
    ],
    emergingSectors: [
      { name: "Agri Value Addition", growthSignal: "high", description: "Paddy processing, vegetable grading, and packaging for Hyderabad", investmentRange: "₹4L–₹15L" },
      { name: "Rural Healthcare", growthSignal: "high", description: "Diagnostics and elder care for a dispersed rural population", investmentRange: "₹1L–₹5L" },
      { name: "Handloom D2C", growthSignal: "medium", description: "Gollabhama sarees barely visible on online channels", investmentRange: "₹2L–₹7L" },
    ],
    topOpportunities: [
      { title: "Farm Input Subscription Box", sector: "Agriculture", fitScore: 88, investmentRange: "₹2L–₹5L", demandScore: 87, teamSize: "2–4", ideaSlug: "farm-input-subscription-box" },
      { title: "Handloom Weaver Aggregation", sector: "Textile", fitScore: 85, investmentRange: "₹3L–₹7L", demandScore: 83, teamSize: "3–5", ideaSlug: "handloom-weaver-aggregation-platform" },
      { title: "Diagnostic Sample Collection Hub", sector: "Healthcare", fitScore: 83, investmentRange: "₹1L–₹3L", demandScore: 85, teamSize: "2–3", ideaSlug: "diagnostic-sample-collection-hub" },
      { title: "Agri Produce Transport Aggregator", sector: "Logistics", fitScore: 81, investmentRange: "₹2L–₹5L", demandScore: 82, teamSize: "2–4", ideaSlug: "agri-produce-transport-aggregator" },
      { title: "Stationery & Print Shop", sector: "Services", fitScore: 76, investmentRange: "₹1L–₹3L", demandScore: 78, teamSize: "2–3", ideaSlug: "stationery-and-print-shop" },
    ],
    skillsDemand: [
      { skill: "Agri Extension", demandLevel: "high", sector: "Agriculture" },
      { skill: "Handloom Weaving", demandLevel: "high", sector: "Textiles" },
      { skill: "Phlebotomy / Lab", demandLevel: "medium", sector: "Healthcare" },
      { skill: "Logistics Driver Network", demandLevel: "medium", sector: "Transport" },
    ],
    governmentSchemes: [
      { name: "Rythu Bandhu", authority: "Telangana Govt", benefit: "₹5,000/acre/season investment support", eligibility: "Registered farmers" },
      { name: "PM Kisan Sampada", authority: "MoFPI", benefit: "Subsidy on processing infrastructure", eligibility: "Food processing units" },
      { name: "Handloom Weavers Welfare", authority: "Telangana Govt", benefit: "Thrift fund, insurance, marketing support", eligibility: "Registered weavers" },
    ],
    demographics: { literacyRate: "63.5%", urbanRuralRatio: "20:80", youthPopulation: "27% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "Rajiv Rahadari (SH-1) to Hyderabad (100 km); new rail line via Gajwel",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (130 km)",
      nearestRailwayHub: "Secunderabad (100 km)",
      industrialAreas: ["IDA Siddipet", "Food processing cluster (proposed)"],
    },
    relatedArticleSlugs: ["rural-diagnostic-centers-india"],
  },
  {
    slug: "warangal",
    name: "Warangal",
    state: "Telangana",
    population: 3527000,
    populationLabel: "35.27 Lakh",
    region: "Central Telangana",
    headquartersCity: "Warangal",
    profileSummary:
      "Warangal is the second-largest urban agglomeration in Telangana and a historic commercial center. Home to NIT Warangal, a major textile tradition, and a young educated workforce, it combines a city-scale market with district-scale costs — ideal for education, EV services, and handloom commerce.",
    keyIndustries: [
      { name: "Handloom & Textiles", description: "Warangal durries and ikat traditions — GI-tagged exports", employmentShare: "25%" },
      { name: "Education", description: "NIT Warangal, KU campus, and a large coaching economy", employmentShare: "10%" },
      { name: "Agriculture", description: "Cotton, turmeric, and paddy", employmentShare: "40%" },
      { name: "Trade & Logistics", description: "Central Telangana's wholesale and transit hub", employmentShare: "15%" },
    ],
    emergingSectors: [
      { name: "Handloom Tech & E-Commerce", growthSignal: "high", description: "GI-tagged products underrepresented on D2C platforms", investmentRange: "₹2L–₹10L" },
      { name: "EV Service & Charging", growthSignal: "high", description: "Rising 2W EV adoption with minimal service infrastructure", investmentRange: "₹5L–₹20L" },
      { name: "Agri-Tech & Drone Services", growthSignal: "medium", description: "Drone crop monitoring and spraying gaining traction", investmentRange: "₹8L–₹30L" },
    ],
    topOpportunities: [
      { title: "Handloom Weaver Aggregation Platform", sector: "Textile", fitScore: 91, investmentRange: "₹3L–₹7L", demandScore: 89, teamSize: "3–5", ideaSlug: "handloom-weaver-aggregation-platform" },
      { title: "EV Charging Hub", sector: "Energy", fitScore: 87, investmentRange: "₹8L–₹20L", demandScore: 90, teamSize: "3–6", ideaSlug: "ev-charging-hub" },
      { title: "Drone Crop Spraying Service", sector: "AgriTech", fitScore: 84, investmentRange: "₹10L–₹20L", demandScore: 85, teamSize: "3–6", ideaSlug: "drone-spraying-service" },
      { title: "Competitive Exam Coaching Centre", sector: "Education", fitScore: 83, investmentRange: "₹2L–₹5L", demandScore: 87, teamSize: "3–6", ideaSlug: "competitive-exam-coaching-centre" },
      { title: "Coding Bootcamp for Rural Youth", sector: "Education", fitScore: 80, investmentRange: "₹2L–₹5L", demandScore: 82, teamSize: "2–4", ideaSlug: "coding-bootcamp-for-rural-youth" },
    ],
    skillsDemand: [
      { skill: "Handloom Weaving (Master Craftsman)", demandLevel: "high", sector: "Textiles" },
      { skill: "EV Technician", demandLevel: "high", sector: "Automotive" },
      { skill: "Digital Marketing", demandLevel: "medium", sector: "E-Commerce" },
      { skill: "Drone Pilot (DGCA Certified)", demandLevel: "medium", sector: "Agri-Tech" },
    ],
    governmentSchemes: [
      { name: "Handloom Weavers Welfare Trust", authority: "Telangana Govt", benefit: "Insurance, thrift fund, and marketing support for weavers", eligibility: "Registered handloom weavers" },
      { name: "FAME India Phase II", authority: "Ministry of Heavy Industries", benefit: "Subsidy on EV charging infrastructure", eligibility: "EV charging station operators" },
      { name: "TS-iPASS", authority: "Telangana Government", benefit: "Fast-track industrial clearance", eligibility: "All enterprises" },
    ],
    demographics: { literacyRate: "73.1%", urbanRuralRatio: "38:62", youthPopulation: "32% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "NH-163 and NH-563; Warangal railway junction (South Central Railway)",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (155 km)",
      nearestRailwayHub: "Warangal Junction (in-district)",
      industrialAreas: ["TSIIC Kazipet", "Madikonda IT Tower"],
    },
    relatedArticleSlugs: ["ev-charging-business-telangana"],
  },
  {
    slug: "karimnagar",
    name: "Karimnagar",
    state: "Telangana",
    population: 1005000,
    populationLabel: "10.05 Lakh",
    region: "North Telangana",
    headquartersCity: "Karimnagar",
    profileSummary:
      "Karimnagar is a granite, granary, and gold-work town on the Manair river — among Telangana's most urbanised non-capital districts. A strong trading culture, smart-city investments, and dense banking penetration make it fertile ground for retail, services, and agri-processing ventures.",
    keyIndustries: [
      { name: "Granite & Quarrying", description: "Major granite extraction and polishing cluster", employmentShare: "12%" },
      { name: "Agriculture", description: "Paddy bowl of Telangana; maize and cotton", employmentShare: "48%" },
      { name: "Gold & Silver Craft", description: "Famous silver filigree (GI) and jewellery trade", employmentShare: "8%" },
      { name: "Trade & Banking", description: "Dense commercial and cooperative banking network", employmentShare: "20%" },
    ],
    emergingSectors: [
      { name: "Rice Value Chain", growthSignal: "high", description: "Bran oil, fortified rice, and branded retail from surplus paddy", investmentRange: "₹5L–₹30L" },
      { name: "EV & Auto Services", growthSignal: "high", description: "Fast-growing two-wheeler market with thin service infrastructure", investmentRange: "₹3L–₹15L" },
      { name: "Event & Wedding Economy", growthSignal: "medium", description: "High-spend wedding market with few organised providers", investmentRange: "₹2L–₹7L" },
    ],
    topOpportunities: [
      { title: "Packaged Dry Snacks Brand", sector: "Food", fitScore: 86, investmentRange: "₹2L–₹6L", demandScore: 84, teamSize: "3–5", ideaSlug: "packaged-dry-snacks-brand" },
      { title: "Wedding Planning & Decoration", sector: "Events", fitScore: 85, investmentRange: "₹3L–₹7L", demandScore: 86, teamSize: "3–6", ideaSlug: "wedding-planning-and-decoration-service" },
      { title: "Competitive Exam Coaching Centre", sector: "Education", fitScore: 84, investmentRange: "₹2L–₹5L", demandScore: 88, teamSize: "3–6", ideaSlug: "competitive-exam-coaching-centre" },
      { title: "Sound & Lighting Equipment Rental", sector: "Events", fitScore: 80, investmentRange: "₹6L–₹15L", demandScore: 81, teamSize: "3–5", ideaSlug: "sound-and-lighting-equipment-rental" },
      { title: "Steel Gate & Grill Fabrication", sector: "Manufacturing", fitScore: 78, investmentRange: "₹3L–₹8L", demandScore: 80, teamSize: "3–4", ideaSlug: "steel-gate-and-grill-fabrication" },
    ],
    skillsDemand: [
      { skill: "Food Processing Operator", demandLevel: "high", sector: "Food" },
      { skill: "Event Management", demandLevel: "high", sector: "Events" },
      { skill: "Welding / Fabrication", demandLevel: "medium", sector: "Manufacturing" },
      { skill: "Teaching (Competitive Exams)", demandLevel: "high", sector: "Education" },
    ],
    governmentSchemes: [
      { name: "PMFME", authority: "MoFPI", benefit: "35% credit-linked subsidy for micro food units", eligibility: "Food micro-enterprises" },
      { name: "Mudra Loans", authority: "Banks / NBFCs", benefit: "Loans up to ₹10L without collateral", eligibility: "Micro-entrepreneurs" },
      { name: "TS-iPASS", authority: "Telangana Govt", benefit: "Single-window industrial clearance", eligibility: "All industries" },
    ],
    demographics: { literacyRate: "69.2%", urbanRuralRatio: "35:65", youthPopulation: "29% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "Rajiv Rahadari to Hyderabad (165 km); NH-563; Kazipet rail access",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (190 km)",
      nearestRailwayHub: "Kazipet Junction (70 km)",
      industrialAreas: ["IDA Karimnagar", "Granite cluster, Oddiraju"],
    },
    relatedArticleSlugs: ["ev-charging-business-telangana"],
  },
  {
    slug: "nizamabad",
    name: "Nizamabad",
    state: "Telangana",
    population: 2552000,
    populationLabel: "25.52 Lakh",
    region: "North Telangana",
    headquartersCity: "Nizamabad",
    profileSummary:
      "Nizamabad is the largest turmeric trading hub in Asia and a significant centre for steel furniture and sugar processing. Its fertile black cotton soils support diverse horticulture. Strong rail connectivity to Maharashtra and Andhra Pradesh makes it a natural logistics node.",
    keyIndustries: [
      { name: "Turmeric & Spice Trade", description: "Asia's largest turmeric auction market — APMC Nizamabad", employmentShare: "22%" },
      { name: "Sugar & Ethanol", description: "Several cooperative and private sugar mills", employmentShare: "10%" },
      { name: "Steel Furniture", description: "Cluster of steel furniture units selling pan-India", employmentShare: "8%" },
      { name: "Agriculture", description: "Turmeric, sugarcane, maize, soybean", employmentShare: "48%" },
    ],
    emergingSectors: [
      { name: "Turmeric Value Addition", growthSignal: "high", description: "Curcumin extract, capsules, and cosmetics — massive export potential", investmentRange: "₹5L–₹40L" },
      { name: "Ethanol & Biofuel", growthSignal: "high", description: "Government blending mandates creating local demand", investmentRange: "₹20L–₹1Cr" },
      { name: "Cold Logistics", growthSignal: "medium", description: "Spice and horticulture cold chain severely underdeveloped", investmentRange: "₹10L–₹50L" },
    ],
    topOpportunities: [
      { title: "District Spice Brand (Turmeric)", sector: "Food Processing", fitScore: 93, investmentRange: "₹2L–₹6L", demandScore: 95, teamSize: "3–6", ideaSlug: "packaged-dry-snacks-brand" },
      { title: "Micro Cold Storage as a Service", sector: "Logistics", fitScore: 87, investmentRange: "₹8L–₹15L", demandScore: 88, teamSize: "3–6", ideaSlug: "micro-cold-storage-as-a-service" },
      { title: "Agri Waste to Biochar Unit", sector: "Agriculture", fitScore: 84, investmentRange: "₹6L–₹12L", demandScore: 83, teamSize: "3–5", ideaSlug: "agri-waste-to-biochar-unit" },
      { title: "Agri Produce Transport Aggregator", sector: "Logistics", fitScore: 82, investmentRange: "₹2L–₹5L", demandScore: 84, teamSize: "2–4", ideaSlug: "agri-produce-transport-aggregator" },
      { title: "Agricultural Tool Fabrication", sector: "Manufacturing", fitScore: 79, investmentRange: "₹4L–₹10L", demandScore: 80, teamSize: "3–5", ideaSlug: "agricultural-tool-fabrication-workshop" },
    ],
    skillsDemand: [
      { skill: "Quality Control (Spices)", demandLevel: "high", sector: "Food Processing" },
      { skill: "Export Documentation", demandLevel: "high", sector: "Logistics" },
      { skill: "Lab Testing (FSSAI)", demandLevel: "medium", sector: "Healthcare" },
      { skill: "Cold Chain Technician", demandLevel: "medium", sector: "Logistics" },
    ],
    governmentSchemes: [
      { name: "APEDA Export Promotion", authority: "APEDA / Ministry of Commerce", benefit: "Freight subsidy and export marketing support for agricultural products", eligibility: "Registered exporters" },
      { name: "PM Kisan Sampada", authority: "MoFPI", benefit: "Subsidy on processing infrastructure", eligibility: "Food processing units" },
      { name: "TS-iPASS", authority: "Telangana Govt", benefit: "Single-window industrial clearance", eligibility: "All industries" },
    ],
    demographics: { literacyRate: "67.7%", urbanRuralRatio: "28:72", youthPopulation: "30% under 25", mainLanguages: ["Telugu", "Urdu", "Marathi"] },
    infrastructure: {
      connectivity: "NH-44 (Mumbai–Chennai); Nizamabad junction on Secunderabad–Manmad line",
      nearestAirport: "Rajiv Gandhi International Airport, Hyderabad (175 km)",
      nearestRailwayHub: "Nizamabad Junction (in-district)",
      industrialAreas: ["TSIIC Nizamabad", "Dichpally Industrial Node"],
    },
    relatedArticleSlugs: ["ev-charging-business-telangana"],
  },
  {
    slug: "khammam",
    name: "Khammam",
    state: "Telangana",
    population: 1402000,
    populationLabel: "14.02 Lakh",
    region: "East Telangana",
    headquartersCity: "Khammam",
    profileSummary:
      "Khammam sits between Telangana's coal belt and Andhra's coastal plains — a chilli, mango, and oil-palm powerhouse with strong rail freight links. Granite, agro-trade, and a fast-urbanising headquarters town create openings in agri-processing, logistics, and rural services.",
    keyIndustries: [
      { name: "Agriculture & Horticulture", description: "Chilli, mango, oil palm, and paddy", employmentShare: "52%" },
      { name: "Granite & Mining", description: "Black granite quarrying and export units", employmentShare: "10%" },
      { name: "Trade & Transport", description: "Agro-commodity trade on the TS–AP corridor", employmentShare: "18%" },
    ],
    emergingSectors: [
      { name: "Mango & Chilli Processing", growthSignal: "high", description: "Pulp, pickles, and dried-chilli grading for export buyers", investmentRange: "₹5L–₹25L" },
      { name: "Oil Palm Services", growthSignal: "high", description: "Telangana's #1 oil-palm district — harvesting and logistics services", investmentRange: "₹3L–₹15L" },
      { name: "Rural Healthcare", growthSignal: "medium", description: "Diagnostics and telehealth for dispersed mandals", investmentRange: "₹1L–₹5L" },
    ],
    topOpportunities: [
      { title: "Organic Honey Processing & Branding", sector: "Food", fitScore: 86, investmentRange: "₹3L–₹8L", demandScore: 84, teamSize: "3–5", ideaSlug: "organic-honey-processing-and-branding" },
      { title: "Micro Cold Storage as a Service", sector: "Logistics", fitScore: 85, investmentRange: "₹8L–₹15L", demandScore: 88, teamSize: "3–6", ideaSlug: "micro-cold-storage-as-a-service" },
      { title: "Tele-health Facilitation Centre", sector: "Healthcare", fitScore: 83, investmentRange: "₹2L–₹5L", demandScore: 86, teamSize: "2–4", ideaSlug: "tele-health-facilitation-centre" },
      { title: "Wooden Furniture Manufacturing", sector: "Manufacturing", fitScore: 80, investmentRange: "₹5L–₹12L", demandScore: 79, teamSize: "4–8", ideaSlug: "wooden-furniture-manufacturing" },
      { title: "Rural Micro-Fulfilment Centre", sector: "Logistics", fitScore: 78, investmentRange: "₹8L–₹18L", demandScore: 81, teamSize: "5–8", ideaSlug: "rural-micro-fulfilment-centre" },
    ],
    skillsDemand: [
      { skill: "Food Processing", demandLevel: "high", sector: "Agro-Processing" },
      { skill: "Cold Chain Operations", demandLevel: "high", sector: "Logistics" },
      { skill: "Health Worker (ANM/GNM)", demandLevel: "medium", sector: "Healthcare" },
      { skill: "Carpentry", demandLevel: "medium", sector: "Manufacturing" },
    ],
    governmentSchemes: [
      { name: "Oil Palm Mission", authority: "NMEO-OP / Telangana Govt", benefit: "Planting subsidy and assured procurement for oil palm", eligibility: "Farmers and service providers" },
      { name: "PMFME", authority: "MoFPI", benefit: "35% subsidy for micro food processing", eligibility: "Food micro-enterprises" },
      { name: "Rythu Bandhu", authority: "Telangana Govt", benefit: "Per-acre investment support", eligibility: "Registered farmers" },
    ],
    demographics: { literacyRate: "65.0%", urbanRuralRatio: "25:75", youthPopulation: "28% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "NH-365; Khammam on Kazipet–Vijayawada trunk rail line",
      nearestAirport: "Vijayawada International Airport (120 km)",
      nearestRailwayHub: "Khammam Junction (in-district)",
      industrialAreas: ["IDA Khammam", "Granite cluster Sathupalli"],
    },
    relatedArticleSlugs: ["rural-diagnostic-centers-india"],
  },

  // ─── ANDHRA PRADESH ───
  {
    slug: "vijayawada",
    name: "Vijayawada",
    state: "Andhra Pradesh",
    population: 4200000,
    populationLabel: "42 Lakh",
    region: "Krishna District, Coastal Andhra",
    headquartersCity: "Vijayawada",
    profileSummary:
      "Vijayawada is the commercial capital of Andhra Pradesh — a bustling river-port city with the state's largest wholesale markets, a booming retail corridor, and rapid infrastructure growth following the Amaravati capital development. A strong logistics spine connects it to Hyderabad, Chennai, and Krishnapatnam port.",
    keyIndustries: [
      { name: "Wholesale & Retail Trade", description: "Besant Road and Governorpet — major commercial hubs", employmentShare: "30%" },
      { name: "Real Estate", description: "Growth driven by capital development and infra projects", employmentShare: "12%" },
      { name: "Food & FMCG Distribution", description: "Gateway for AP food products to national markets", employmentShare: "15%" },
      { name: "Education & Healthcare", description: "Medical colleges, corporate hospitals, large student population", employmentShare: "15%" },
    ],
    emergingSectors: [
      { name: "Logistics & Warehousing", growthSignal: "high", description: "AP Capital Region needs organized 3PL and last-mile delivery", investmentRange: "₹10L–₹75L" },
      { name: "EV Charging Corridor", growthSignal: "high", description: "NH-16 corridor has minimal charging infrastructure", investmentRange: "₹8L–₹30L" },
      { name: "EdTech & Coaching", growthSignal: "medium", description: "Competitive exam coaching demand from large student inflows", investmentRange: "₹3L–₹15L" },
    ],
    topOpportunities: [
      { title: "Rural Micro-Fulfilment Centre", sector: "Logistics", fitScore: 91, investmentRange: "₹8L–₹18L", demandScore: 93, teamSize: "5–8", ideaSlug: "rural-micro-fulfilment-centre" },
      { title: "EV Charging Hub", sector: "Energy", fitScore: 88, investmentRange: "₹8L–₹20L", demandScore: 90, teamSize: "2–5", ideaSlug: "ev-charging-hub" },
      { title: "Competitive Exam Coaching Centre", sector: "Education", fitScore: 84, investmentRange: "₹2L–₹5L", demandScore: 87, teamSize: "3–8", ideaSlug: "competitive-exam-coaching-centre" },
      { title: "Cloud Kitchen — AP Cuisine", sector: "Food", fitScore: 82, investmentRange: "₹3L–₹7L", demandScore: 85, teamSize: "3–6", ideaSlug: "cloud-kitchen-for-regional-cuisine" },
      { title: "Hyperlocal Grocery Delivery", sector: "Commerce", fitScore: 80, investmentRange: "₹3L–₹8L", demandScore: 83, teamSize: "4–8", ideaSlug: "hyperlocal-grocery-delivery" },
    ],
    skillsDemand: [
      { skill: "Supply Chain & Logistics", demandLevel: "high", sector: "Logistics" },
      { skill: "Real Estate Sales", demandLevel: "high", sector: "Real Estate" },
      { skill: "EV Technician", demandLevel: "medium", sector: "Automotive" },
      { skill: "Digital Marketing", demandLevel: "medium", sector: "E-Commerce" },
    ],
    governmentSchemes: [
      { name: "APSIDC Schemes", authority: "AP State Industrial Dev Corp", benefit: "Land allotment and infrastructure support for industries", eligibility: "Manufacturing and service enterprises" },
      { name: "FAME India Phase II", authority: "Ministry of Heavy Industries", benefit: "EV charging station subsidy", eligibility: "EV operators" },
      { name: "PMEGP", authority: "KVIC / DIC", benefit: "Margin money subsidy up to 35%", eligibility: "New micro-enterprises" },
    ],
    demographics: { literacyRate: "74.6%", urbanRuralRatio: "62:38", youthPopulation: "34% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "NH-16 (Chennai–Kolkata); Vijayawada Junction — one of India's busiest rail nodes",
      nearestAirport: "Vijayawada International Airport (12 km)",
      nearestRailwayHub: "Vijayawada Junction (in-city)",
      industrialAreas: ["Kondapalli Industrial Area", "Auto Nagar Industrial Estate"],
    },
    relatedArticleSlugs: ["battery-recycling-business-india", "ev-charging-business-telangana"],
  },
  {
    slug: "guntur",
    name: "Guntur",
    state: "Andhra Pradesh",
    population: 4888000,
    populationLabel: "48.88 Lakh",
    region: "Coastal Andhra",
    headquartersCity: "Guntur",
    profileSummary:
      "Guntur is India's chilli capital — home to the world's largest red chilli market — as well as a dominant player in cotton, tobacco, and lemon exports. Its strong agricultural base and industrial heritage make it ideal for agro-processing, packaging, and export-oriented businesses.",
    keyIndustries: [
      { name: "Chilli & Spice Trade", description: "Guntur APMC — India's largest chilli market by volume", employmentShare: "28%" },
      { name: "Cotton & Textiles", description: "Large cotton belt with ginning and pressing units", employmentShare: "18%" },
      { name: "Tobacco Processing", description: "Virginia tobacco processing and export hub", employmentShare: "10%" },
      { name: "Agriculture", description: "Chilli, cotton, tobacco, maize, lemon", employmentShare: "38%" },
    ],
    emergingSectors: [
      { name: "Chilli Value-Added Products", growthSignal: "high", description: "Chilli powder, capsaicin extract, hot sauce, and oleoresin for export", investmentRange: "₹5L–₹50L" },
      { name: "Battery Recycling", growthSignal: "medium", description: "Growing EV and electronics waste needing organized recycling", investmentRange: "₹15L–₹60L" },
      { name: "Agri-Input Retail", growthSignal: "medium", description: "Organized seed and fertilizer retail underserved in rural mandals", investmentRange: "₹3L–₹10L" },
    ],
    topOpportunities: [
      { title: "Cold-Pressed Oil Unit", sector: "Food Processing", fitScore: 90, investmentRange: "₹5L–₹12L", demandScore: 92, teamSize: "4–6", ideaSlug: "cold-pressed-oil-unit" },
      { title: "Farm Input Subscription Box", sector: "Agriculture", fitScore: 87, investmentRange: "₹2L–₹5L", demandScore: 88, teamSize: "2–4", ideaSlug: "farm-input-subscription-box" },
      { title: "Micro Cold Storage as a Service", sector: "Logistics", fitScore: 86, investmentRange: "₹8L–₹15L", demandScore: 89, teamSize: "3–6", ideaSlug: "micro-cold-storage-as-a-service" },
      { title: "Paper Bag & Eco-Packaging Unit", sector: "Manufacturing", fitScore: 82, investmentRange: "₹4L–₹10L", demandScore: 83, teamSize: "4–6", ideaSlug: "paper-bag-and-eco-packaging-unit" },
      { title: "District B2B Wholesale Aggregator", sector: "Commerce", fitScore: 80, investmentRange: "₹5L–₹12L", demandScore: 82, teamSize: "3–6", ideaSlug: "district-b2b-wholesale-aggregator" },
    ],
    skillsDemand: [
      { skill: "Quality Control (Spices/FSSAI)", demandLevel: "high", sector: "Food Processing" },
      { skill: "Export Documentation", demandLevel: "high", sector: "Logistics" },
      { skill: "Battery Disassembly Technician", demandLevel: "medium", sector: "Recycling" },
      { skill: "Agri-Input Sales", demandLevel: "medium", sector: "Agriculture" },
    ],
    governmentSchemes: [
      { name: "APEDA Spice Export Support", authority: "APEDA", benefit: "Freight and quality certification subsidies for spice exports", eligibility: "Registered exporters" },
      { name: "PLI Scheme — Food Processing", authority: "Ministry of Food Processing", benefit: "Production-linked incentive for processed food manufacturers", eligibility: "MSME food processors" },
      { name: "Battery Waste Management Rules", authority: "MoEF&CC", benefit: "EPR framework and collection support for battery recyclers", eligibility: "Registered recyclers" },
    ],
    demographics: { literacyRate: "67.5%", urbanRuralRatio: "35:65", youthPopulation: "29% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "NH-16 and NH-65; strong rail links to Vijayawada and Chennai",
      nearestAirport: "Vijayawada International Airport (60 km)",
      nearestRailwayHub: "Guntur Junction (in-city)",
      industrialAreas: ["Naidupeta Industrial Area", "Tadepalli Industrial Node"],
    },
    relatedArticleSlugs: ["battery-recycling-business-india"],
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    population: 4288000,
    populationLabel: "42.88 Lakh",
    region: "North Coastal Andhra",
    headquartersCity: "Visakhapatnam",
    profileSummary:
      "Visakhapatnam is AP's largest city — a deep-water port, steel city, and emerging IT destination wrapped around beaches and the Eastern Ghats. The port economy, naval presence, pharma SEZs, and tourism create a uniquely diversified opportunity base.",
    keyIndustries: [
      { name: "Port & Logistics", description: "One of India's busiest cargo ports plus Gangavaram", employmentShare: "15%" },
      { name: "Steel & Heavy Industry", description: "Vizag Steel Plant and ancillary fabrication economy", employmentShare: "12%" },
      { name: "Pharma & Chemicals", description: "JNPC Parawada — one of Asia's biggest pharma SEZs", employmentShare: "10%" },
      { name: "IT & Fintech", description: "Growing IT/fintech corridor; AP's designated fintech hub", employmentShare: "6%" },
      { name: "Fisheries & Tourism", description: "Major fishing harbour; beach and Araku tourism", employmentShare: "18%" },
    ],
    emergingSectors: [
      { name: "Port-Linked Services", growthSignal: "high", description: "Customs documentation, container services, export packaging", investmentRange: "₹2L–₹20L" },
      { name: "Coastal & Eco Tourism", growthSignal: "high", description: "Araku, Lambasingi, and beach circuits underserved by organised operators", investmentRange: "₹2L–₹8L" },
      { name: "Marine Food Processing", growthSignal: "high", description: "Seafood value-addition for export markets", investmentRange: "₹10L–₹50L" },
      { name: "E-Waste & Battery Recycling", growthSignal: "medium", description: "Port access makes recovered-material exports viable", investmentRange: "₹3L–₹60L" },
    ],
    topOpportunities: [
      { title: "Adventure & Trek Tourism Operator", sector: "Tourism", fitScore: 89, investmentRange: "₹3L–₹8L", demandScore: 88, teamSize: "3–5", ideaSlug: "adventure-and-trek-tourism-operator" },
      { title: "E-Waste Collection & Recycling Hub", sector: "Climate", fitScore: 86, investmentRange: "₹3L–₹8L", demandScore: 85, teamSize: "3–5", ideaSlug: "e-waste-collection-and-recycling-hub" },
      { title: "HR & Payroll SaaS for Local Firms", sector: "Technology", fitScore: 84, investmentRange: "₹5L–₹12L", demandScore: 83, teamSize: "3–5", ideaSlug: "hr-and-payroll-saas-for-local-firms" },
      { title: "Heritage Homestay Network", sector: "Tourism", fitScore: 83, investmentRange: "₹3L–₹7L", demandScore: 84, teamSize: "3–5", ideaSlug: "heritage-homestay-network" },
      { title: "Cybersecurity Audit for SMBs", sector: "Technology", fitScore: 80, investmentRange: "₹2L–₹5L", demandScore: 79, teamSize: "2–4", ideaSlug: "cybersecurity-audit-for-smbs" },
    ],
    skillsDemand: [
      { skill: "Logistics & EXIM Documentation", demandLevel: "high", sector: "Port Services" },
      { skill: "Tour Operations", demandLevel: "high", sector: "Tourism" },
      { skill: "Software Development", demandLevel: "high", sector: "IT" },
      { skill: "Seafood Quality Control", demandLevel: "medium", sector: "Marine" },
    ],
    governmentSchemes: [
      { name: "Sagarmala", authority: "Ministry of Ports & Shipping", benefit: "Port-linked industrialisation and logistics support", eligibility: "Port-ecosystem businesses" },
      { name: "PM Matsya Sampada Yojana", authority: "Dept of Fisheries", benefit: "Up to 60% subsidy on fisheries infrastructure", eligibility: "Fisheries entrepreneurs" },
      { name: "APSIDC", authority: "AP Govt", benefit: "Industrial land and incentives", eligibility: "Manufacturing units" },
    ],
    demographics: { literacyRate: "81.8%", urbanRuralRatio: "58:42", youthPopulation: "33% under 25", mainLanguages: ["Telugu"] },
    infrastructure: {
      connectivity: "NH-16 coastal corridor; major port + Gangavaram; metro planned",
      nearestAirport: "Visakhapatnam International Airport (in-city)",
      nearestRailwayHub: "Visakhapatnam Junction (in-city)",
      industrialAreas: ["JNPC Parawada", "Autonagar", "APSEZ Atchutapuram"],
    },
    relatedArticleSlugs: ["battery-recycling-business-india"],
  },
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    population: 2197000,
    populationLabel: "21.97 Lakh",
    region: "Rayalaseema",
    headquartersCity: "Tirupati",
    profileSummary:
      "Tirupati hosts the world's most-visited religious site — 60,000 to 100,000 pilgrims daily — alongside an electronics manufacturing cluster (Sri City proximity) and a dense university belt. Pilgrim services, hospitality, and education are perennial high-demand sectors.",
    keyIndustries: [
      { name: "Pilgrimage & Hospitality", description: "TTD ecosystem: hotels, food, transport, and services", employmentShare: "35%" },
      { name: "Electronics Manufacturing", description: "Mobile and electronics assembly cluster nearby", employmentShare: "10%" },
      { name: "Education", description: "SVU, IIT Tirupati, IISER, and a large student population", employmentShare: "12%" },
      { name: "Agriculture & Horticulture", description: "Mango, sugarcane, and floriculture for temple demand", employmentShare: "30%" },
    ],
    emergingSectors: [
      { name: "Pilgrim Tech & Services", growthSignal: "high", description: "Queue management, bookings, multilingual guidance, and senior assistance", investmentRange: "₹2L–₹10L" },
      { name: "Hospitality Upgrades", growthSignal: "high", description: "Quality budget stays and food for family pilgrims", investmentRange: "₹3L–₹15L" },
      { name: "Floriculture Supply Chain", growthSignal: "medium", description: "Daily tonnes of flowers for temple demand need organised supply", investmentRange: "₹2L–₹8L" },
    ],
    topOpportunities: [
      { title: "Temple Town Tour Guide App", sector: "Tourism", fitScore: 91, investmentRange: "₹4L–₹10L", demandScore: 92, teamSize: "3–5", ideaSlug: "temple-town-tour-guide-app" },
      { title: "Medical Escort & Hospital Support", sector: "Healthcare", fitScore: 86, investmentRange: "₹1L–₹3L", demandScore: 87, teamSize: "3–5", ideaSlug: "medical-escort-and-hospital-support" },
      { title: "Cloud Kitchen for Regional Cuisine", sector: "Food", fitScore: 84, investmentRange: "₹3L–₹7L", demandScore: 86, teamSize: "3–5", ideaSlug: "cloud-kitchen-for-regional-cuisine" },
      { title: "Heritage Homestay Network", sector: "Tourism", fitScore: 83, investmentRange: "₹3L–₹7L", demandScore: 85, teamSize: "3–5", ideaSlug: "heritage-homestay-network" },
      { title: "Yoga & Meditation Studio", sector: "Wellness", fitScore: 80, investmentRange: "₹2L–₹5L", demandScore: 81, teamSize: "2–3", ideaSlug: "yoga-and-meditation-studio" },
    ],
    skillsDemand: [
      { skill: "Hospitality Operations", demandLevel: "high", sector: "Tourism" },
      { skill: "Multilingual Guides", demandLevel: "high", sector: "Tourism" },
      { skill: "Electronics Assembly", demandLevel: "medium", sector: "Manufacturing" },
      { skill: "App Development", demandLevel: "medium", sector: "Technology" },
    ],
    governmentSchemes: [
      { name: "PRASHAD Scheme", authority: "Ministry of Tourism", benefit: "Pilgrimage destination infrastructure funding", eligibility: "Tourism infrastructure projects" },
      { name: "Mudra Loans", authority: "Banks", benefit: "Collateral-free loans up to ₹10L", eligibility: "Micro-entrepreneurs" },
      { name: "APSIDC Electronics Policy", authority: "AP Govt", benefit: "Capital and power subsidies for electronics units", eligibility: "Electronics manufacturers" },
    ],
    demographics: { literacyRate: "72.4%", urbanRuralRatio: "45:55", youthPopulation: "31% under 25", mainLanguages: ["Telugu", "Tamil", "Hindi"] },
    infrastructure: {
      connectivity: "NH-71/NH-140; Renigunta junction; daily trains from every metro",
      nearestAirport: "Tirupati International Airport (15 km)",
      nearestRailwayHub: "Tirupati / Renigunta Junction (in-district)",
      industrialAreas: ["Sri City (45 km)", "Renigunta Industrial Estate"],
    },
    relatedArticleSlugs: [],
  },
  {
    slug: "kurnool",
    name: "Kurnool",
    state: "Andhra Pradesh",
    population: 4053000,
    populationLabel: "40.53 Lakh",
    region: "Rayalaseema",
    headquartersCity: "Kurnool",
    profileSummary:
      "Kurnool — the former capital of Andhra State — anchors Rayalaseema's farm economy: groundnut, cotton, and onion at scale, plus mineral wealth and India's largest solar park at Orvakal. Low service penetration means first-movers in healthcare, agri-services, and energy win fast.",
    keyIndustries: [
      { name: "Agriculture", description: "Groundnut, cotton, onion, and millets across dryland belts", employmentShare: "58%" },
      { name: "Minerals & Cement", description: "Limestone, iron ore, and major cement plants", employmentShare: "12%" },
      { name: "Solar Energy", description: "Orvakal ultra-mega solar park (1,000 MW+)", employmentShare: "4%" },
      { name: "Trade & Services", description: "Rayalaseema's commercial gateway on NH-44", employmentShare: "18%" },
    ],
    emergingSectors: [
      { name: "Solar O&M and Services", growthSignal: "high", description: "Panel cleaning, maintenance, and rooftop installation services", investmentRange: "₹2L–₹15L" },
      { name: "Dryland Agri Value Chain", growthSignal: "high", description: "Groundnut oil, millet products, and onion dehydration", investmentRange: "₹5L–₹25L" },
      { name: "Rural Healthcare", growthSignal: "high", description: "Severe diagnostic and specialist deficit across mandals", investmentRange: "₹1L–₹8L" },
    ],
    topOpportunities: [
      { title: "Solar Installation Service", sector: "Energy", fitScore: 90, investmentRange: "₹2L–₹8L", demandScore: 91, teamSize: "3–6", ideaSlug: "solar-installation-service" },
      { title: "Cold-Pressed Oil Unit (Groundnut)", sector: "Food", fitScore: 88, investmentRange: "₹5L–₹12L", demandScore: 89, teamSize: "4–6", ideaSlug: "cold-pressed-oil-unit" },
      { title: "Tele-health Facilitation Centre", sector: "Healthcare", fitScore: 86, investmentRange: "₹2L–₹5L", demandScore: 90, teamSize: "2–4", ideaSlug: "tele-health-facilitation-centre" },
      { title: "Ready-to-Cook Millet Products", sector: "Food", fitScore: 84, investmentRange: "₹4L–₹10L", demandScore: 85, teamSize: "3–6", ideaSlug: "ready-to-cook-millet-products" },
      { title: "Water Quality Testing Service", sector: "Services", fitScore: 80, investmentRange: "₹2L–₹5L", demandScore: 82, teamSize: "2–3", ideaSlug: "water-quality-testing-service" },
    ],
    skillsDemand: [
      { skill: "Solar Technician", demandLevel: "high", sector: "Energy" },
      { skill: "Food Processing Operator", demandLevel: "high", sector: "Agro-Processing" },
      { skill: "Health Worker (ANM/GNM)", demandLevel: "high", sector: "Healthcare" },
      { skill: "Water Analyst", demandLevel: "medium", sector: "Services" },
    ],
    governmentSchemes: [
      { name: "PM Surya Ghar", authority: "MNRE", benefit: "Rooftop solar subsidy up to ₹78,000", eligibility: "Households; installers benefit from demand" },
      { name: "NMEO Oilseeds Mission", authority: "Ministry of Agriculture", benefit: "Support for oilseed processing", eligibility: "Oil processing units" },
      { name: "Ayushman Bharat PMJAY", authority: "NHA / AP SHA", benefit: "Empanelment gives guaranteed patient volumes", eligibility: "Diagnostic and care providers" },
    ],
    demographics: { literacyRate: "61.1%", urbanRuralRatio: "28:72", youthPopulation: "30% under 25", mainLanguages: ["Telugu", "Urdu"] },
    infrastructure: {
      connectivity: "NH-44 north–south spine; Kurnool City station; Orvakal airport",
      nearestAirport: "Kurnool (Orvakal) Airport (25 km)",
      nearestRailwayHub: "Kurnool City (in-district)",
      industrialAreas: ["Orvakal Industrial Hub", "APIIC Kallur"],
    },
    relatedArticleSlugs: ["rural-diagnostic-centers-india"],
  },
  {
    slug: "nellore",
    name: "Nellore",
    state: "Andhra Pradesh",
    population: 2964000,
    populationLabel: "29.64 Lakh",
    region: "South Coastal Andhra",
    headquartersCity: "Nellore",
    profileSummary:
      "Nellore is India's aquaculture heartland — shrimp and fish farming at export scale — alongside Krishnapatnam port, mica heritage, and the famous Nellore paddy belt. Aqua value chains, port services, and rural commerce are the standout plays.",
    keyIndustries: [
      { name: "Aquaculture", description: "Shrimp and fish ponds feeding a multi-billion export trade", employmentShare: "25%" },
      { name: "Port & Logistics", description: "Krishnapatnam — one of India's deepest private ports", employmentShare: "10%" },
      { name: "Agriculture", description: "Premium paddy (Nellore Sona), lemon, and sugarcane", employmentShare: "42%" },
      { name: "Energy & Industry", description: "Thermal cluster and upcoming industrial corridors", employmentShare: "8%" },
    ],
    emergingSectors: [
      { name: "Aqua Inputs & Services", growthSignal: "high", description: "Feed supply, water testing, disease diagnostics for thousands of ponds", investmentRange: "₹2L–₹15L" },
      { name: "Seafood Processing", growthSignal: "high", description: "Value-added shrimp products for export premiums", investmentRange: "₹10L–₹50L" },
      { name: "Port-Linked Commerce", growthSignal: "medium", description: "Container services and EXIM facilitation around Krishnapatnam", investmentRange: "₹3L–₹20L" },
    ],
    topOpportunities: [
      { title: "Water Quality Testing Service (Aqua)", sector: "Services", fitScore: 92, investmentRange: "₹2L–₹5L", demandScore: 93, teamSize: "2–4", ideaSlug: "water-quality-testing-service" },
      { title: "Agri Produce Transport Aggregator", sector: "Logistics", fitScore: 86, investmentRange: "₹2L–₹5L", demandScore: 87, teamSize: "2–4", ideaSlug: "agri-produce-transport-aggregator" },
      { title: "Cold Chain Logistics (Aqua & Dairy)", sector: "Logistics", fitScore: 85, investmentRange: "₹10L–₹20L", demandScore: 88, teamSize: "4–8", ideaSlug: "cold-chain-logistics-for-pharma-and-dairy" },
      { title: "GST Filing & Compliance Service", sector: "Finance", fitScore: 81, investmentRange: "₹1L–₹3L", demandScore: 80, teamSize: "2–3", ideaSlug: "gst-filing-and-compliance-service" },
      { title: "Sports Equipment Rental & Retail", sector: "Retail", fitScore: 76, investmentRange: "₹3L–₹8L", demandScore: 75, teamSize: "2–4", ideaSlug: "sports-equipment-rental-and-retail" },
    ],
    skillsDemand: [
      { skill: "Aqua Lab Technician", demandLevel: "high", sector: "Aquaculture" },
      { skill: "Cold Chain Operations", demandLevel: "high", sector: "Logistics" },
      { skill: "EXIM Documentation", demandLevel: "medium", sector: "Port Services" },
      { skill: "Accounting / GST", demandLevel: "medium", sector: "Finance" },
    ],
    governmentSchemes: [
      { name: "PM Matsya Sampada Yojana", authority: "Dept of Fisheries", benefit: "Up to 60% subsidy on aqua infrastructure", eligibility: "Aqua entrepreneurs, SC/ST/Women priority" },
      { name: "MPEDA Export Support", authority: "MPEDA", benefit: "Quality certification and export market support", eligibility: "Seafood exporters" },
      { name: "Mudra Loans", authority: "Banks", benefit: "Collateral-free micro-loans", eligibility: "Micro-entrepreneurs" },
    ],
    demographics: { literacyRate: "68.9%", urbanRuralRatio: "30:70", youthPopulation: "29% under 25", mainLanguages: ["Telugu", "Tamil"] },
    infrastructure: {
      connectivity: "NH-16 Chennai–Kolkata; Krishnapatnam port; Nellore on Chennai trunk rail",
      nearestAirport: "Tirupati International Airport (130 km)",
      nearestRailwayHub: "Nellore (in-district)",
      industrialAreas: ["Krishnapatnam Industrial Node", "APIIC Nellore"],
    },
    relatedArticleSlugs: [],
  },
];

export function getDistrictBySlug(slug) {
  return DISTRICTS.find((d) => d.slug === slug) || null;
}

export function getAllDistrictSlugs() {
  return DISTRICTS.map((d) => d.slug);
}
