// ValueWeave Idea Library — static dataset (v1).
// Modular so migration to Supabase tables later is easy.
// 30 balanced ideas: 12 local-physical · 9 hybrid · 6 pure-digital · 3 future.

export const SECTORS = [
  { id: "agriculture",      label: "Agriculture",        emoji: "🌾" },
  { id: "local-services",   label: "Local Services",     emoji: "🏪" },
  { id: "repair-economy",   label: "Repair Economy",     emoji: "🔧" },
  { id: "women-led",        label: "Women-Led",          emoji: "💐" },
  { id: "food-business",    label: "Food Business",      emoji: "🍱" },
  { id: "manufacturing",    label: "Manufacturing",      emoji: "🏭" },
  { id: "education",        label: "Education",          emoji: "🎓" },
  { id: "logistics",        label: "Logistics",          emoji: "🚚" },
  { id: "digital-services", label: "Digital Services",   emoji: "📱" },
  { id: "creator-economy",  label: "Creator Economy",    emoji: "🎬" },
  { id: "agritech",         label: "AgriTech",           emoji: "🤖" },
  { id: "ev-energy",        label: "EV & Energy",        emoji: "⚡" },
  { id: "drone-tech",       label: "Drone Tech",         emoji: "🚁" },
  { id: "climate-tech",     label: "Climate Tech",       emoji: "♻️" },
];

export const BUCKETS = [
  { id: "local-physical", label: "Local Physical",      emoji: "🏪" },
  { id: "hybrid",         label: "Hybrid Tech + Local", emoji: "🔗" },
  { id: "digital",        label: "Pure Digital",        emoji: "💻" },
  { id: "future",         label: "Future Economy",      emoji: "🚀" },
];

export const PRIORITY_STATES = ["Telangana", "Andhra Pradesh"];

// Priority districts shown first in chips (Telangana → AP → others)
export const PRIORITY_DISTRICTS = [
  // Telangana
  "Hyderabad", "Medak", "Sangareddy", "Siddipet", "Warangal",
  "Karimnagar", "Nizamabad", "Khammam", "Mahabubnagar", "Nalgonda",
  // Andhra Pradesh
  "Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Nellore",
  "Kurnool", "East Godavari", "West Godavari", "Anantapur",
];

export const ALL_TAGS = [
  "AI-Proof", "Low Investment", "Women-Led", "Student Friendly", "Remote Possible",
  "Rural Opportunity", "Urban Opportunity", "Semi-Urban Opportunity", "High Growth",
  "Evergreen", "Sustainable", "Tech Enabled", "Local Service", "Community Driven",
  "Field Intensive", "Export Potential", "Village Scale", "District Scale",
  "Part-Time Friendly", "Family Business Friendly", "Skill-Based",
  "High Trust Required", "Relationship Driven",
];

export const IDEAS = [
  // ───────── LOCAL PHYSICAL (12) ─────────
  {
    id: "idea_001", slug: "soil-testing-micro-lab", title: "Soil Testing Micro Lab", emoji: "🌱",
    sector: "agriculture", bucket: "local-physical",
    short_description: "Mobile soil & water testing for farmers, agri shops, and FPOs across your district.",
    problem_solved: "Most small farmers don't know their soil's nutrient profile, leading to wrong fertilizer use and poor yield.",
    investment_min: 200000, investment_med: 500000, investment_adv: 800000,
    monthly_revenue_min: 25000, monthly_revenue_max: 100000,
    team_roles: ["Agriculture Expert", "Field Coordinator", "Lab Technician"],
    skills_needed: ["Soil Testing", "Lab Operations", "Field Marketing", "Customer Handling"],
    ideal_for: ["Agriculture graduates", "Rural youth", "Small teams"],
    district_fit: ["Warangal", "Nizamabad", "Guntur", "Karimnagar", "Anantapur"],
    tags: ["Rural Opportunity", "Low Investment", "Skill-Based", "Field Intensive", "Tech Enabled"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_002", slug: "ro-water-service", title: "RO Water Service", emoji: "💧",
    sector: "local-services", bucket: "local-physical",
    short_description: "Install community RO plants and run a subscription-based clean-water delivery network.",
    problem_solved: "Tier-2/3 households lack consistent clean drinking water; bottled water is expensive and wasteful.",
    investment_min: 300000, investment_med: 800000, investment_adv: 1500000,
    monthly_revenue_min: 40000, monthly_revenue_max: 150000,
    team_roles: ["Operations Coordinator", "Field Support", "Local Sales Partner"],
    skills_needed: ["Plumbing", "Customer Handling", "Inventory Management", "Field Marketing"],
    ideal_for: ["Local entrepreneurs", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Khammam", "Tirupati"],
    tags: ["Semi-Urban Opportunity", "Evergreen", "Local Service", "Family Business Friendly"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_003", slug: "mobile-repair-network", title: "Mobile Repair Network", emoji: "📱",
    sector: "repair-economy", bucket: "local-physical",
    short_description: "Trained technicians + branded counters offering same-day mobile, laptop & TV repair.",
    problem_solved: "Smartphone failures are universal; trustworthy local repair is rare and unbranded.",
    investment_min: 100000, investment_med: 300000, investment_adv: 700000,
    monthly_revenue_min: 30000, monthly_revenue_max: 120000,
    team_roles: ["Technical", "Field Support", "Customer Handling"],
    skills_needed: ["Mobile Repair", "AC Repair", "Customer Handling", "Inventory Management"],
    ideal_for: ["Working professionals", "Rural youth", "ITI graduates"],
    district_fit: ["Tirupati", "Khammam", "Karimnagar", "Nellore", "Mahabubnagar"],
    tags: ["AI-Proof", "Low Investment", "Local Service", "Skill-Based", "Evergreen"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_004", slug: "bike-repair-workshop", title: "Two-Wheeler Repair Workshop", emoji: "🛵",
    sector: "repair-economy", bucket: "local-physical",
    short_description: "Modern, clean two-wheeler service center with doorstep pickup-drop in semi-urban areas.",
    problem_solved: "Local mechanic shops feel unsafe and unhygienic; servicing quality varies wildly.",
    investment_min: 250000, investment_med: 600000, investment_adv: 1200000,
    monthly_revenue_min: 50000, monthly_revenue_max: 180000,
    team_roles: ["Technical", "Operations Coordinator", "Field Support"],
    skills_needed: ["Bike Repair", "Mechanical Work", "Customer Handling", "Sales"],
    ideal_for: ["ITI graduates", "Family-run businesses", "Small teams"],
    district_fit: ["Sangareddy", "Medak", "Anantapur", "Kurnool", "Guntur"],
    tags: ["AI-Proof", "Local Service", "Family Business Friendly", "Field Intensive"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_005", slug: "tailoring-cluster", title: "Tailoring Cluster (Women-led)", emoji: "🧵",
    sector: "women-led", bucket: "local-physical",
    short_description: "Cluster of 5–15 home-based tailors taking volume orders from boutiques, schools, NGOs.",
    problem_solved: "Skilled tailors at home earn poorly because they can't access bulk orders.",
    investment_min: 50000, investment_med: 200000, investment_adv: 500000,
    monthly_revenue_min: 30000, monthly_revenue_max: 100000,
    team_roles: ["Community Manager", "Operations Coordinator", "Local Sales Partner"],
    skills_needed: ["Tailoring", "Team Management", "Sales", "Customer Handling"],
    ideal_for: ["Women entrepreneurs", "Self-help groups", "Local business owners"],
    district_fit: ["Warangal", "Nizamabad", "Karimnagar", "Nellore", "Kurnool"],
    tags: ["Women-Led", "Low Investment", "Community Driven", "Rural Opportunity", "Family Business Friendly"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_006", slug: "pickle-papad-brand", title: "Pickle & Papad Brand", emoji: "🥒",
    sector: "food-business", bucket: "local-physical",
    short_description: "Regional flavor pickle brand sold via WhatsApp, local kirana stores, and Instagram orders.",
    problem_solved: "Authentic homemade pickles have no shelf presence; urban diaspora misses regional flavors.",
    investment_min: 80000, investment_med: 250000, investment_adv: 600000,
    monthly_revenue_min: 20000, monthly_revenue_max: 90000,
    team_roles: ["Operations Coordinator", "Local Sales Partner", "Marketing"],
    skills_needed: ["Food Processing", "Packaging", "Digital Marketing", "Sales"],
    ideal_for: ["Women entrepreneurs", "Family-run businesses", "Rural youth"],
    district_fit: ["Guntur", "Vijayawada", "Khammam", "Warangal", "East Godavari"],
    tags: ["Women-Led", "Low Investment", "Family Business Friendly", "Evergreen", "Export Potential"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_007", slug: "solar-installation-service", title: "Solar Panel Installation Service", emoji: "☀️",
    sector: "ev-energy", bucket: "local-physical",
    short_description: "Residential & SMB rooftop solar installation with maintenance contracts.",
    problem_solved: "Power cuts in tier-2 cities are common; solar is affordable but installers are scarce.",
    investment_min: 300000, investment_med: 700000, investment_adv: 1500000,
    monthly_revenue_min: 60000, monthly_revenue_max: 250000,
    team_roles: ["Technical", "Field Support", "Operations Coordinator"],
    skills_needed: ["Electrical Work", "Field Marketing", "Customer Handling", "Vendor Management"],
    ideal_for: ["ITI graduates", "Electricians", "Small teams"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Tirupati", "Anantapur"],
    tags: ["Sustainable", "High Growth", "Skill-Based", "Tech Enabled", "Semi-Urban Opportunity"],
    beginner_friendly: false, remote_possible: false,
  },
  {
    id: "idea_008", slug: "dairy-collection-network", title: "Dairy Collection Network", emoji: "🥛",
    sector: "agriculture", bucket: "local-physical",
    short_description: "Village-level milk collection points feeding a chilled-transport route to a regional dairy.",
    problem_solved: "Small dairy farmers get exploited by middlemen; quality milk doesn't reach urban demand.",
    investment_min: 250000, investment_med: 700000, investment_adv: 1500000,
    monthly_revenue_min: 50000, monthly_revenue_max: 200000,
    team_roles: ["Field Support", "Logistics Coordinator", "Local Sales Partner"],
    skills_needed: ["Dairy Management", "Logistics", "Vendor Management", "Customer Handling"],
    ideal_for: ["Rural youth", "Agriculture graduates", "Local business owners"],
    district_fit: ["Medak", "Nizamabad", "Karimnagar", "Anantapur", "Kurnool"],
    tags: ["Rural Opportunity", "Village Scale", "Field Intensive", "Family Business Friendly", "Relationship Driven"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_009", slug: "local-delivery-fleet", title: "Local Delivery Fleet", emoji: "🛵",
    sector: "logistics", bucket: "local-physical",
    short_description: "Asset-light delivery fleet for D2C brands, restaurants, and kirana stores in your city.",
    problem_solved: "Local sellers can't afford Zomato/Dunzo style logistics for non-food daily deliveries.",
    investment_min: 150000, investment_med: 400000, investment_adv: 900000,
    monthly_revenue_min: 35000, monthly_revenue_max: 130000,
    team_roles: ["Operations Coordinator", "Field Support", "Logistics Coordinator"],
    skills_needed: ["Operations Coordination", "Customer Handling", "Vendor Management", "Digital Marketing"],
    ideal_for: ["Working professionals", "Small teams", "Local entrepreneurs"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Nellore"],
    tags: ["Semi-Urban Opportunity", "High Growth", "Tech Enabled", "Skill-Based"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_010", slug: "cctv-installation-service", title: "CCTV & Security Installation", emoji: "🎥",
    sector: "repair-economy", bucket: "local-physical",
    short_description: "Residential, retail & farmland CCTV install + AMC; expanding to smart-home gadgets.",
    problem_solved: "Crime concern drives demand, but trained, trustworthy installers are scarce in tier-2 cities.",
    investment_min: 100000, investment_med: 250000, investment_adv: 600000,
    monthly_revenue_min: 25000, monthly_revenue_max: 100000,
    team_roles: ["Technical", "Field Support", "Local Sales Partner"],
    skills_needed: ["CCTV Installation", "Electrical Work", "Customer Handling", "Sales"],
    ideal_for: ["ITI graduates", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Warangal", "Vijayawada", "Visakhapatnam", "Karimnagar"],
    tags: ["Semi-Urban Opportunity", "Skill-Based", "High Growth", "Local Service", "AI-Proof"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_011", slug: "tuition-hub", title: "Tuition & Coaching Hub", emoji: "🎓",
    sector: "education", bucket: "local-physical",
    short_description: "Neighborhood after-school coaching for grades 6–12 with project labs and parent app.",
    problem_solved: "Quality tuition is concentrated in metros; tier-2 students fall behind in concepts.",
    investment_min: 80000, investment_med: 300000, investment_adv: 800000,
    monthly_revenue_min: 30000, monthly_revenue_max: 150000,
    team_roles: ["Trainer/Educator", "Operations Coordinator", "Community Manager"],
    skills_needed: ["Teaching", "Team Management", "Sales", "Content Writing"],
    ideal_for: ["Students", "Working professionals", "Women entrepreneurs"],
    district_fit: ["Medak", "Sangareddy", "Khammam", "Nizamabad", "Guntur"],
    tags: ["Evergreen", "Low Investment", "Community Driven", "Family Business Friendly", "Skill-Based"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_012", slug: "homemade-tiffin-brand", title: "Homemade Tiffin Brand", emoji: "🍱",
    sector: "food-business", bucket: "local-physical",
    short_description: "Subscription home-cooked tiffins for working professionals, students & hostels.",
    problem_solved: "Hostel & PG food is unhealthy; working singles in tier-2 cities miss home-style meals.",
    investment_min: 50000, investment_med: 200000, investment_adv: 500000,
    monthly_revenue_min: 25000, monthly_revenue_max: 90000,
    team_roles: ["Operations Coordinator", "Local Sales Partner", "Logistics Coordinator"],
    skills_needed: ["Food Processing", "Customer Handling", "Digital Marketing", "Packaging"],
    ideal_for: ["Women entrepreneurs", "Family-run businesses", "Local entrepreneurs"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Warangal"],
    tags: ["Women-Led", "Low Investment", "Evergreen", "Family Business Friendly", "Urban Opportunity"],
    beginner_friendly: true, remote_possible: false,
  },

  // ───────── HYBRID TECH + LOCAL (9) ─────────
  {
    id: "idea_013", slug: "whatsapp-commerce-setup", title: "WhatsApp Commerce Setup Service", emoji: "💬",
    sector: "digital-services", bucket: "hybrid",
    short_description: "Onboard kirana, boutique & restaurant owners onto WhatsApp Business with catalogs & payments.",
    problem_solved: "Lakhs of small businesses run on WhatsApp manually; they need setup, catalog & payment automation.",
    investment_min: 30000, investment_med: 100000, investment_adv: 300000,
    monthly_revenue_min: 20000, monthly_revenue_max: 100000,
    team_roles: ["Technical", "Marketing", "Field Support"],
    skills_needed: ["Digital Marketing", "Customer Handling", "Web Development", "Sales"],
    ideal_for: ["Students", "Working professionals", "Local entrepreneurs"],
    district_fit: ["Hyderabad", "Vijayawada", "Warangal", "Visakhapatnam", "Tirupati"],
    tags: ["Low Investment", "Tech Enabled", "High Growth", "Skill-Based", "Part-Time Friendly"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_014", slug: "local-business-digitalization", title: "Local Business Digitalization Agency", emoji: "🏪",
    sector: "digital-services", bucket: "hybrid",
    short_description: "Take local shops, clinics & restaurants online — websites, Google profile, Instagram, ads.",
    problem_solved: "Tier-2 SMBs miss the entire digital economy because they don't know where to start.",
    investment_min: 30000, investment_med: 150000, investment_adv: 400000,
    monthly_revenue_min: 25000, monthly_revenue_max: 150000,
    team_roles: ["Technical", "Creative", "Marketing"],
    skills_needed: ["SEO", "Social Media Management", "Graphic Design", "Web Development"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Karimnagar"],
    tags: ["Tech Enabled", "High Growth", "Skill-Based", "Remote Possible", "Student Friendly"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_015", slug: "district-marketplace-platform", title: "District Marketplace Platform", emoji: "🛒",
    sector: "digital-services", bucket: "hybrid",
    short_description: "Hyperlocal classifieds + commerce app for a single district (rentals, services, used goods).",
    problem_solved: "Generic apps don't capture district-specific demand; OLX/Quikr aren't truly local.",
    investment_min: 200000, investment_med: 600000, investment_adv: 1500000,
    monthly_revenue_min: 30000, monthly_revenue_max: 200000,
    team_roles: ["Technical", "Marketing", "Community Manager", "Local Sales Partner"],
    skills_needed: ["Mobile App Development", "UI/UX Design", "Digital Marketing", "Operations Coordination"],
    ideal_for: ["Small teams", "Student entrepreneurs", "Working professionals"],
    district_fit: ["Khammam", "Warangal", "Karimnagar", "Guntur", "Nellore"],
    tags: ["District Scale", "Tech Enabled", "High Growth", "Community Driven"],
    beginner_friendly: false, remote_possible: true,
  },
  {
    id: "idea_016", slug: "drone-spraying-service", title: "Drone Spraying for Farms", emoji: "🚁",
    sector: "agritech", bucket: "hybrid",
    short_description: "Licensed drone fleet for pesticide spraying, fertilizer broadcast, crop monitoring.",
    problem_solved: "Manual spraying is slow, expensive, and unsafe; drone services boost yields and save labor.",
    investment_min: 500000, investment_med: 1500000, investment_adv: 3000000,
    monthly_revenue_min: 80000, monthly_revenue_max: 350000,
    team_roles: ["Technical", "Agriculture Expert", "Field Support"],
    skills_needed: ["Drone Piloting", "Agriculture", "Customer Handling", "Field Marketing"],
    ideal_for: ["Rural youth", "Agriculture graduates", "Small teams"],
    district_fit: ["Guntur", "Warangal", "Nizamabad", "Karimnagar", "Anantapur"],
    tags: ["Tech Enabled", "High Growth", "Rural Opportunity", "Skill-Based", "Sustainable"],
    beginner_friendly: false, remote_possible: false,
  },
  {
    id: "idea_017", slug: "hyperlocal-food-brand", title: "Hyperlocal Cloud Kitchen Brand", emoji: "🍛",
    sector: "food-business", bucket: "hybrid",
    short_description: "Specialty regional cuisine cloud kitchen on Zomato/Swiggy/own WhatsApp orders.",
    problem_solved: "Diaspora and locals crave regional dishes (Hyderabadi, Andhra, Telangana) that delivery apps under-serve.",
    investment_min: 150000, investment_med: 400000, investment_adv: 1000000,
    monthly_revenue_min: 40000, monthly_revenue_max: 200000,
    team_roles: ["Operations Coordinator", "Marketing", "Logistics Coordinator"],
    skills_needed: ["Food Processing", "Digital Marketing", "Customer Handling", "Sales"],
    ideal_for: ["Women entrepreneurs", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Warangal"],
    tags: ["Urban Opportunity", "High Growth", "Tech Enabled", "Family Business Friendly"],
    beginner_friendly: false, remote_possible: false,
  },
  {
    id: "idea_018", slug: "ai-content-studio", title: "AI Content Studio for SMBs", emoji: "🎨",
    sector: "creator-economy", bucket: "hybrid",
    short_description: "Use AI tools to produce social posts, reels, ads & catalogs for local SMBs on subscription.",
    problem_solved: "Small businesses can't afford agencies; AI lets a 2-person team serve 20+ clients/month.",
    investment_min: 30000, investment_med: 100000, investment_adv: 300000,
    monthly_revenue_min: 25000, monthly_revenue_max: 150000,
    team_roles: ["Creative", "Technical", "Marketing"],
    skills_needed: ["Graphic Design", "Video Editing", "AI Engineering", "Content Writing"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Tirupati", "Warangal"],
    tags: ["Tech Enabled", "Student Friendly", "Remote Possible", "Low Investment", "High Growth"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_019", slug: "local-event-media-crew", title: "Local Event Media Crew", emoji: "🎥",
    sector: "creator-economy", bucket: "hybrid",
    short_description: "Wedding, festival & corporate event coverage with reels-first deliverables in 48 hours.",
    problem_solved: "Traditional wedding photographers deliver slowly; clients want Instagram-ready reels fast.",
    investment_min: 150000, investment_med: 400000, investment_adv: 900000,
    monthly_revenue_min: 30000, monthly_revenue_max: 200000,
    team_roles: ["Creative", "Technical", "Operations Coordinator"],
    skills_needed: ["Photography", "Video Editing", "Event Management", "Customer Handling"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Tirupati", "Guntur", "Warangal"],
    tags: ["Skill-Based", "Student Friendly", "High Growth", "Relationship Driven", "Urban Opportunity"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_020", slug: "smart-farm-monitoring", title: "Smart Farm Sensor Monitoring", emoji: "📡",
    sector: "agritech", bucket: "hybrid",
    short_description: "Affordable IoT soil + weather sensors with WhatsApp alerts for irrigation & disease.",
    problem_solved: "Farmers over-water or react late to crop disease; sensors cut input cost 20–30%.",
    investment_min: 200000, investment_med: 600000, investment_adv: 1500000,
    monthly_revenue_min: 30000, monthly_revenue_max: 180000,
    team_roles: ["Technical", "Agriculture Expert", "Field Support"],
    skills_needed: ["AI Engineering", "Mobile App Development", "Agriculture", "Field Marketing"],
    ideal_for: ["Agriculture graduates", "Engineering graduates", "Small teams"],
    district_fit: ["Warangal", "Nizamabad", "Karimnagar", "Anantapur", "Guntur"],
    tags: ["AgriTech", "Tech Enabled", "Sustainable", "Rural Opportunity", "High Growth"],
    beginner_friendly: false, remote_possible: false,
  },
  {
    id: "idea_021", slug: "beauty-training-center", title: "Beauty Training Center + Online Booking", emoji: "💄",
    sector: "women-led", bucket: "hybrid",
    short_description: "Govt-recognized beauty/wellness training + paid placement + booking app for graduates.",
    problem_solved: "Women want stable income from skills; existing parlors hire informally and pay low.",
    investment_min: 200000, investment_med: 500000, investment_adv: 1000000,
    monthly_revenue_min: 35000, monthly_revenue_max: 150000,
    team_roles: ["Trainer/Educator", "Community Manager", "Marketing"],
    skills_needed: ["Beautician Services", "Teaching", "Sales", "Digital Marketing"],
    ideal_for: ["Women entrepreneurs", "Working professionals", "Local entrepreneurs"],
    district_fit: ["Hyderabad", "Vijayawada", "Warangal", "Visakhapatnam", "Karimnagar"],
    tags: ["Women-Led", "Skill-Based", "Community Driven", "High Growth", "Semi-Urban Opportunity"],
    beginner_friendly: false, remote_possible: false,
  },

  // ───────── PURE DIGITAL (6) ─────────
  {
    id: "idea_022", slug: "uiux-freelance-agency", title: "UI/UX Freelance Agency", emoji: "🎨",
    sector: "digital-services", bucket: "digital",
    short_description: "3–5 person remote UI/UX team taking startup, agency & SMB website + product design work.",
    problem_solved: "Demand for crisp UI/UX is exploding; well-trained tier-2 designers compete globally on quality + price.",
    investment_min: 20000, investment_med: 80000, investment_adv: 200000,
    monthly_revenue_min: 50000, monthly_revenue_max: 300000,
    team_roles: ["Creative", "Technical", "Marketing"],
    skills_needed: ["UI/UX Design", "Graphic Design", "Web Development", "Sales"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Tirupati", "Warangal"],
    tags: ["Remote Possible", "Student Friendly", "High Growth", "Export Potential", "Skill-Based"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_023", slug: "seo-local-marketing-agency", title: "SEO & Local Marketing Agency", emoji: "📈",
    sector: "digital-services", bucket: "digital",
    short_description: "Help dentists, clinics, schools, real-estate get found on Google Maps & local search.",
    problem_solved: "Local businesses know Google matters but don't have anyone who'll do GMB + reviews + SEO.",
    investment_min: 20000, investment_med: 100000, investment_adv: 300000,
    monthly_revenue_min: 30000, monthly_revenue_max: 200000,
    team_roles: ["Marketing", "Creative", "Technical"],
    skills_needed: ["SEO", "Digital Marketing", "Content Writing", "Customer Handling"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Karimnagar", "Nellore"],
    tags: ["Remote Possible", "Student Friendly", "Low Investment", "High Growth", "Skill-Based"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_024", slug: "ai-voiceover-studio", title: "AI Voice-Over & Dubbing Studio", emoji: "🎙️",
    sector: "creator-economy", bucket: "digital",
    short_description: "Multilingual AI-assisted voice-over + dubbing for ed-tech, YouTube channels, ads.",
    problem_solved: "Telugu/Hindi/Tamil content is exploding; quality affordable dubbing is scarce.",
    investment_min: 30000, investment_med: 150000, investment_adv: 400000,
    monthly_revenue_min: 30000, monthly_revenue_max: 200000,
    team_roles: ["Creative", "Technical", "Marketing"],
    skills_needed: ["Voice Over", "Video Editing", "AI Engineering", "Content Writing"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Warangal"],
    tags: ["Remote Possible", "Tech Enabled", "Student Friendly", "High Growth", "Skill-Based"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_025", slug: "mobile-app-dev-studio", title: "Mobile App Development Studio", emoji: "📱",
    sector: "digital-services", bucket: "digital",
    short_description: "Lean studio building MVPs and white-label apps for startups, SMBs, and local commerce platforms.",
    problem_solved: "Tier-2 founders need affordable, quick MVPs; metro agencies are too expensive.",
    investment_min: 30000, investment_med: 150000, investment_adv: 400000,
    monthly_revenue_min: 50000, monthly_revenue_max: 300000,
    team_roles: ["Technical", "Creative", "Marketing"],
    skills_needed: ["Mobile App Development", "Web Development", "UI/UX Design", "Sales"],
    ideal_for: ["Students", "Working professionals", "Small teams"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Tirupati", "Warangal"],
    tags: ["Remote Possible", "High Growth", "Skill-Based", "Export Potential"],
    beginner_friendly: false, remote_possible: true,
  },
  {
    id: "idea_026", slug: "edu-youtube-channel", title: "Educational YouTube Channel", emoji: "📺",
    sector: "creator-economy", bucket: "digital",
    short_description: "Regional-language YouTube channel for board exams, skills, entrepreneurship, or local jobs.",
    problem_solved: "Quality Telugu/regional educational content is undersupplied vs. demand from millions of students.",
    investment_min: 20000, investment_med: 80000, investment_adv: 250000,
    monthly_revenue_min: 10000, monthly_revenue_max: 200000,
    team_roles: ["Creative", "Technical", "Trainer/Educator"],
    skills_needed: ["Video Editing", "Content Writing", "Teaching", "SEO"],
    ideal_for: ["Students", "Working professionals", "Trainers"],
    district_fit: ["Hyderabad", "Vijayawada", "Khammam", "Warangal", "Guntur"],
    tags: ["Remote Possible", "Student Friendly", "Part-Time Friendly", "Low Investment", "Skill-Based"],
    beginner_friendly: true, remote_possible: true,
  },
  {
    id: "idea_027", slug: "campus-merch-pod", title: "Campus Merch Print-on-Demand", emoji: "👕",
    sector: "creator-economy", bucket: "digital",
    short_description: "Custom tees, hoodies, bottles for colleges, fests, and clubs — drop-shipped from a partner printer.",
    problem_solved: "Every college fest reinvents merch from scratch; students want quality + speed.",
    investment_min: 15000, investment_med: 80000, investment_adv: 250000,
    monthly_revenue_min: 15000, monthly_revenue_max: 100000,
    team_roles: ["Creative", "Marketing", "Operations Coordinator"],
    skills_needed: ["Graphic Design", "Digital Marketing", "Sales", "Vendor Management"],
    ideal_for: ["Students", "Small teams"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Tirupati", "Warangal"],
    tags: ["Student Friendly", "Low Investment", "Part-Time Friendly", "Remote Possible"],
    beginner_friendly: true, remote_possible: true,
  },

  // ───────── FUTURE ECONOMY (3) ─────────
  {
    id: "idea_028", slug: "ev-charging-hub", title: "EV Charging Hub for Tier-2 Cities", emoji: "🔌",
    sector: "ev-energy", bucket: "future",
    short_description: "Multi-port EV charging station at petrol pumps, malls & highway dhabas with subscription app.",
    problem_solved: "EV adoption is rising but charging infrastructure outside metros is patchy.",
    investment_min: 800000, investment_med: 2000000, investment_adv: 5000000,
    monthly_revenue_min: 60000, monthly_revenue_max: 350000,
    team_roles: ["Technical", "Operations Coordinator", "Investor/Capital Partner"],
    skills_needed: ["Electrical Work", "Operations Coordination", "Vendor Management", "Sales"],
    ideal_for: ["Small teams", "Local entrepreneurs", "Family-run businesses"],
    district_fit: ["Hyderabad", "Vijayawada", "Visakhapatnam", "Tirupati", "Warangal"],
    tags: ["Sustainable", "High Growth", "Tech Enabled", "Semi-Urban Opportunity"],
    beginner_friendly: false, remote_possible: false,
  },
  {
    id: "idea_029", slug: "vermicompost-unit", title: "Vermicompost & Bio-Fertilizer Unit", emoji: "♻️",
    sector: "climate-tech", bucket: "future",
    short_description: "Convert farm & municipal organic waste into vermicompost + bio-fertilizer for FPOs & gardens.",
    problem_solved: "Chemical fertilizers degrade soil; demand for organic inputs is rising 25% YoY.",
    investment_min: 150000, investment_med: 500000, investment_adv: 1200000,
    monthly_revenue_min: 25000, monthly_revenue_max: 150000,
    team_roles: ["Agriculture Expert", "Operations Coordinator", "Field Support"],
    skills_needed: ["Organic Farming", "Operations Coordination", "Vendor Management", "Field Marketing"],
    ideal_for: ["Agriculture graduates", "Rural youth", "Women entrepreneurs"],
    district_fit: ["Warangal", "Nizamabad", "Karimnagar", "Guntur", "Anantapur"],
    tags: ["Sustainable", "Rural Opportunity", "Low Investment", "Family Business Friendly", "Export Potential"],
    beginner_friendly: true, remote_possible: false,
  },
  {
    id: "idea_030", slug: "drone-mapping-realestate", title: "Drone Mapping for Real Estate & Civil", emoji: "🛰️",
    sector: "drone-tech", bucket: "future",
    short_description: "Aerial mapping, photogrammetry & site surveys for real estate, mining, infrastructure projects.",
    problem_solved: "Tier-2 builders pay metro consultants for surveys; local DGCA-licensed pilots can serve faster + cheaper.",
    investment_min: 400000, investment_med: 1200000, investment_adv: 2500000,
    monthly_revenue_min: 50000, monthly_revenue_max: 300000,
    team_roles: ["Technical", "Operations Coordinator", "Marketing"],
    skills_needed: ["Drone Piloting", "UI/UX Design", "Customer Handling", "Sales"],
    ideal_for: ["Engineering graduates", "Small teams", "Working professionals"],
    district_fit: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Warangal", "Tirupati"],
    tags: ["Tech Enabled", "High Growth", "Skill-Based", "Export Potential"],
    beginner_friendly: false, remote_possible: false,
  },
];

// Helpers
export function getIdea(slug) {
  return IDEAS.find((i) => i.slug === slug) || null;
}
export function getSector(id) {
  return SECTORS.find((s) => s.id === id) || { id, label: id, emoji: "🌐" };
}
export function getBucket(id) {
  return BUCKETS.find((b) => b.id === id) || { id, label: id, emoji: "🌐" };
}
export function formatINR(n) {
  if (n >= 100000) return `₹${(n / 100000).toFixed(n % 100000 === 0 ? 0 : 1)}L`;
  if (n >= 1000) return `₹${Math.round(n / 1000)}k`;
  return `₹${n}`;
}
