#!/usr/bin/env python3
"""
ValueWeave knowledge operations — command line.

    python3 -m ops.cli status                    the one-screen answer
    python3 -m ops.cli quality                   the seven dimensions
    python3 -m ops.cli integrity                 what is broken
    python3 -m ops.cli entities --stale          operational metadata per entity
    python3 -m ops.cli snapshot --write          the artifact the dashboard reads
    python3 -m ops.cli report --write            the weekly report
    python3 -m ops.cli report --events x.json    …including search demand

Reads Git and nothing else. Live signals — page views, search counts — are
supplied with `--events` and `--popularity` rather than fetched, so every number
is reproducible offline and "we have no data" stays visible as UNKNOWN instead
of becoming a zero that looks like a measurement.

`--write` is required to write, everywhere, matching knowledge_sync,
stewardship and collection.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ops import integrity as integrity_module      # noqa: E402
from ops import metrics, quality as quality_module, report as report_module  # noqa: E402

#: Inside frontend/lib, and deliberately so. The admin dashboard imports this
#: file, so webpack inlines it at build and it ships with every deployment —
#: whereas a path outside the Next project root would work under `next start`
#: from a checkout and be missing the moment the app is deployed anywhere else.
#: One file, one writer, committed to Git, regenerated by `snapshot --write`.
SNAPSHOT_PATH = (Path(__file__).resolve().parent.parent
                 / "frontend" / "lib" / "ops" / "snapshot.json")

MARK = {"CRITICAL": "✗", "WARN": "!", "OK": "✓", "UNKNOWN": "?"}


def _load(path):
    return json.loads(Path(path).read_text(encoding="utf-8")) if path else None


def _emit(payload, as_json):
    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=False, default=str))
        return True
    return False


def _bar(value, width=24):
    if value is None:
        return "?" * 3 + " " * (width - 3)
    filled = int(round(width * value / 100))
    return "█" * filled + "·" * (width - filled)


def cmd_status(args):
    snapshot = metrics.snapshot(search_events=_load(args.events))
    if _emit(snapshot, args.json):
        return 0

    overview = snapshot["overview"]
    quality = snapshot["quality"]
    collection = snapshot["collection"]
    integrity = snapshot["integrity"]

    print(f"\n  ValueWeave knowledge operations — {snapshot['generated_at']}\n")
    print(f"  quality      {quality['overall']} ({quality['grade']})  "
          f"over {quality['dimensions_scored']} dimensions"
          + (f", {quality['dimensions_unknown']} unknown" if quality['dimensions_unknown'] else ""))
    print(f"  integrity    {integrity['status']}")
    print(f"  feeds        {collection.get('feed_status', 'unknown')}")
    print()
    print(f"  {overview['entities']} entities · {overview['relationships']} relationships · "
          f"{overview['packages']} packages · {overview['entity_types_populated']} types")
    print(f"  {snapshot['connectivity']['connected_pct']}% connected · "
          f"{snapshot['connectivity']['isolated']} isolated · "
          f"{snapshot['freshness']['stale']} stale")
    queue = (collection.get("queue") or {}).get("by_state", {})
    print(f"  {queue.get('NEEDS_REVIEW', 0)} awaiting review · "
          f"{(collection.get('sources') or {}).get('active', 0)} active sources")
    print()

    findings = integrity.get("findings", []) + collection.get("findings", [])
    if not findings:
        print("  ✓ nothing to report\n")
        return 0
    for finding in findings[:12]:
        print(f"    {MARK.get(finding['severity'], '·')} {finding['check']}: "
              f"{finding['detail'][:96]}")
    print()
    return 2 if integrity["status"] == "critical" else 0


def cmd_quality(args):
    result = quality_module.score()
    if _emit(result.as_dict(), args.json):
        return 0
    print(f"\n  knowledge quality  {result.overall}  ({result.grade})\n")
    for dimension in result.dimensions:
        value = f"{dimension.value:5.1f}" if dimension.known else "    ?"
        print(f"  {dimension.name.replace('_', ' '):<22} {value}  {_bar(dimension.value)}")
        print(f"  {'':<22}        {dimension.detail}")
        if args.verbose:
            print(f"  {'':<22}        formula: {dimension.formula}")
    unknown = [d.name for d in result.dimensions if not d.known]
    if unknown:
        print(f"\n  not scored: {', '.join(unknown)} — excluded from the mean rather "
              f"than counted as zero")
    print()
    return 0


def cmd_integrity(args):
    result = integrity_module.check()
    if _emit(result.as_dict(), args.json):
        return 2 if result.status == "critical" else 0
    print(f"\n  integrity: {result.status.upper()}")
    print(f"  {json.dumps(result.counts)}\n")
    for finding in result.findings:
        print(f"    {MARK[finding.severity]} {finding.check}")
        print(f"      {finding.detail}")
    if not result.findings:
        print("    ✓ no operational findings")
    print()
    return 2 if result.status == "critical" else 0


def cmd_entities(args):
    rows = metrics.entity_operations(popularity=_load(args.popularity))
    if args.stale:
        rows = [r for r in rows if r["freshness"] == "STALE"]
    if args.isolated:
        rows = [r for r in rows if r["connected_entities"] == 0]
    if args.type:
        rows = [r for r in rows if r["entity_type"] == args.type]
    rows.sort(key=lambda r: (r["connected_entities"], -(r["age_days"] or 0)))
    rows = rows[:args.limit]

    if _emit(rows, args.json):
        return 0
    if not rows:
        print("nothing matches.")
        return 0
    print(f"\n  {'type':<22} {'deg':>4} {'conf':>5} {'fresh':<8} {'research':<12} name")
    print("  " + "-" * 108)
    for row in rows:
        print(f"  {row['entity_type']:<22} {row['connected_entities']:>4} "
              f"{row['confidence']:>5} {row['freshness']:<8} {row['research_status']:<12} "
              f"{row['canonical_name'][:40]}")
    print(f"\n  {len(rows)} shown. Admin metadata — none of this is a public claim.\n")
    return 0


def cmd_snapshot(args):
    snapshot = metrics.snapshot(search_events=_load(args.events),
                               popularity=_load(args.popularity))
    rendered = json.dumps(snapshot, indent=2, ensure_ascii=False, default=str) + "\n"

    if args.check:
        # For CI. The snapshot is committed, so a pull request that changes the
        # graph and not the snapshot leaves the dashboard showing yesterday's
        # numbers — which is worse than showing none, because it looks current.
        # `generated_at` is excluded: it differs on every run by construction.
        current = SNAPSHOT_PATH.read_text(encoding="utf-8") if SNAPSHOT_PATH.exists() else ""
        if _without_timestamp(current) != _without_timestamp(rendered):
            print("ops snapshot is stale — run `python3 -m ops.cli snapshot --write`",
                  file=sys.stderr)
            return 1
        print("ops snapshot is up to date")
        return 0

    if args.write:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {SNAPSHOT_PATH.relative_to(metrics.ROOT)}")
        return 0
    return 0 if _emit(snapshot, True) else 0


def _without_timestamp(text):
    """Everything except the fields that differ on every run by construction."""
    try:
        payload = json.loads(text or "{}")
    except json.JSONDecodeError:
        return text
    payload.pop("generated_at", None)
    for section in ("collection", "sync"):
        if isinstance(payload.get(section), dict):
            payload[section].pop("last_run", None)
    return json.dumps(payload, sort_keys=True, default=str)


def cmd_report(args):
    snapshot = metrics.snapshot(search_events=_load(args.events),
                               popularity=_load(args.popularity))
    if args.write:
        path = report_module.write(snapshot)
        print(f"wrote {path.relative_to(metrics.ROOT)}")
        return 0
    print(report_module.render(snapshot, previous=report_module.previous_snapshot()))
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ops", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--json", action="store_true", help="machine-readable output")
    common.add_argument("--events", help="JSON export of search_events")
    common.add_argument("--popularity", help="JSON map of entity id or name -> view count")

    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("status", help="the one-screen answer", parents=[common])
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("quality", help="the seven dimensions", parents=[common])
    p.add_argument("--verbose", action="store_true", help="show each formula")
    p.set_defaults(func=cmd_quality)

    p = sub.add_parser("integrity", help="what is broken", parents=[common])
    p.set_defaults(func=cmd_integrity)

    p = sub.add_parser("entities", help="operational metadata per entity", parents=[common])
    p.add_argument("--stale", action="store_true")
    p.add_argument("--isolated", action="store_true")
    p.add_argument("--type")
    p.add_argument("--limit", type=int, default=30)
    p.set_defaults(func=cmd_entities)

    p = sub.add_parser("snapshot", help="the artifact the dashboard reads", parents=[common])
    p.add_argument("--write", action="store_true")
    p.add_argument("--check", action="store_true",
                   help="CI: exit 1 if the committed snapshot is stale")
    p.set_defaults(func=cmd_snapshot)

    p = sub.add_parser("report", help="the weekly report", parents=[common])
    p.add_argument("--write", action="store_true")
    p.set_defaults(func=cmd_report)

    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
