import AdminShell from "@/components/admin/AdminShell";
import { createClient } from "@/lib/supabase-server";
import Link from "next/link";
import { Bell, Users, UserCheck, Briefcase, TrendingUp, MessageSquare, GitMerge, BookOpen, Filter } from "lucide-react";
import { NotificationRowActions, MarkAllRead } from "./NotificationActions";

export const dynamic = "force-dynamic";
export const metadata = {
  title: "Notifications | ValueWeave Admin",
  robots: { index: false, follow: false },
};

const TYPE_META = {
  new_user:          { label: "New User",        icon: Users,        color: "bg-blue-50 text-blue-700 border-blue-200" },
  new_collaborator:  { label: "Collaborator",    icon: UserCheck,    color: "bg-teal-50 text-teal-700 border-teal-200" },
  new_interest:      { label: "Opp. Interest",   icon: Briefcase,    color: "bg-amber-50 text-amber-700 border-amber-200" },
  new_request:       { label: "Request",         icon: TrendingUp,   color: "bg-purple-50 text-purple-700 border-purple-200" },
  new_feedback:      { label: "Feedback",        icon: MessageSquare,color: "bg-rose-50 text-rose-700 border-rose-200" },
  new_match:         { label: "Founder Match",   icon: GitMerge,     color: "bg-green-50 text-green-700 border-green-200" },
  article_published: { label: "Article",         icon: BookOpen,     color: "bg-stone-100 text-stone-600 border-stone-200" },
};

const PRIORITY_CHIP = {
  high:   "bg-red-50 text-red-600 border border-red-200",
  normal: "bg-stone-100 text-stone-500",
  low:    "bg-stone-50 text-stone-400",
};

function timeAgo(dateStr) {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

async function fetchNotifications(filterStatus) {
  try {
    const sb = createClient();
    let q = sb
      .from("admin_notifications")
      .select("id,type,title,body,entity_type,status,priority,created_at")
      .order("created_at", { ascending: false })
      .limit(100);

    if (filterStatus && filterStatus !== "all") q = q.eq("status", filterStatus);

    const [{ data: notifications }, { count: unread }, { count: total }] = await Promise.all([
      q,
      sb.from("admin_notifications").select("*", { count: "exact", head: true }).eq("status", "unread"),
      sb.from("admin_notifications").select("*", { count: "exact", head: true }),
    ]);

    const byType = {};
    (notifications || []).forEach(({ type }) => {
      byType[type] = (byType[type] || 0) + 1;
    });

    return { notifications: notifications || [], unreadCount: unread || 0, total: total || 0, byType };
  } catch {
    return { notifications: [], unreadCount: 0, total: 0, byType: {} };
  }
}

const STATUS_FILTERS = ["all", "unread", "read", "archived"];

export default async function NotificationsPage({ searchParams }) {
  const filterStatus = searchParams?.status || "unread";
  const { notifications, unreadCount, total, byType } = await fetchNotifications(filterStatus);

  return (
    <AdminShell>
      <div className="p-6 max-w-4xl space-y-6">

        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
          <div>
            <span className="chip bg-red-100 text-red-700 border border-red-200">NOTIFICATIONS</span>
            <h1 className="font-display font-extrabold text-2xl text-ink mt-2 flex items-center gap-2">
              <Bell size={22} className="text-red-500" />
              Notification Center
              {unreadCount > 0 && (
                <span className="bg-red-500 text-white text-[11px] font-bold px-2 py-0.5 rounded-full">
                  {unreadCount}
                </span>
              )}
            </h1>
            <p className="text-stone-500 text-sm mt-1">
              All platform events — auto-generated by Supabase triggers
            </p>
          </div>
          {unreadCount > 0 && <MarkAllRead />}
        </div>

        {/* Summary Row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { label: "Total", value: total, color: "bg-stone-50 text-stone-700" },
            { label: "Unread", value: unreadCount, color: "bg-red-50 text-red-700" },
            { label: "High Priority", value: (notifications).filter(n => n.priority === "high").length, color: "bg-amber-50 text-amber-700" },
            { label: "Types Active", value: Object.keys(byType).length, color: "bg-blue-50 text-blue-700" },
          ].map(({ label, value, color }) => (
            <div key={label} className="card-base p-4 text-center">
              <div className={`text-2xl font-display font-extrabold rounded-lg px-2 py-1 inline-block ${color}`}>{value}</div>
              <div className="text-[10px] text-stone-400 uppercase tracking-widest font-semibold mt-1">{label}</div>
            </div>
          ))}
        </div>

        {/* Filter Tabs */}
        <div className="flex items-center gap-2">
          <Filter size={13} className="text-stone-400" />
          {STATUS_FILTERS.map((s) => (
            <Link
              key={s}
              href={`?status=${s}`}
              className={`px-3 py-1.5 rounded-full text-[12px] font-semibold capitalize transition-colors ${
                filterStatus === s
                  ? "bg-amber-500 text-white"
                  : "bg-white border border-stone-200 text-stone-500 hover:border-amber-400 hover:text-amber-700"
              }`}
            >
              {s}
            </Link>
          ))}
        </div>

        {/* Type Breakdown */}
        {Object.keys(byType).length > 0 && (
          <div className="flex flex-wrap gap-2">
            {Object.entries(byType).map(([type, count]) => {
              const meta = TYPE_META[type] || { label: type, color: "bg-stone-100 text-stone-500 border-stone-200" };
              return (
                <span key={type} className={`chip border text-[11px] ${meta.color}`}>
                  {meta.label}: {count}
                </span>
              );
            })}
          </div>
        )}

        {/* Notification List */}
        {notifications.length === 0 ? (
          <div className="card-base p-12 text-center">
            <Bell size={32} className="text-stone-200 mx-auto mb-3" />
            <p className="text-stone-400 text-sm">
              {filterStatus === "unread" ? "No unread notifications." : "No notifications found."}
            </p>
            <p className="text-stone-300 text-xs mt-1">
              Notifications auto-populate when users register, request content, submit feedback, or match with founders.
            </p>
            <p className="text-stone-300 text-xs mt-1 font-semibold">
              Requires: migration 005_growth_intelligence.sql run in Supabase.
            </p>
          </div>
        ) : (
          <div className="card-base overflow-hidden">
            {notifications.map((n, i) => {
              const meta = TYPE_META[n.type] || { label: n.type, icon: Bell, color: "bg-stone-100 text-stone-500 border-stone-200" };
              const Icon = meta.icon;
              return (
                <div
                  key={n.id}
                  className={`flex items-start gap-4 px-5 py-4 border-b border-stone-100 last:border-0 transition-colors ${
                    n.status === "unread" ? "bg-amber-50/30" : ""
                  }`}
                >
                  {/* Icon */}
                  <div className={`shrink-0 p-2 rounded-xl border ${meta.color} mt-0.5`}>
                    <Icon size={14} />
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-0.5">
                      <span className={`font-display font-bold text-[13px] ${n.status === "unread" ? "text-ink" : "text-stone-500"}`}>
                        {n.title}
                      </span>
                      {n.priority === "high" && (
                        <span className={`chip text-[9px] ${PRIORITY_CHIP.high}`}>HIGH</span>
                      )}
                      {n.status === "unread" && (
                        <span className="w-2 h-2 bg-red-500 rounded-full shrink-0" />
                      )}
                    </div>
                    {n.body && <p className="text-[12px] text-stone-500 line-clamp-2">{n.body}</p>}
                    <p className="text-[11px] text-stone-400 mt-1">{timeAgo(n.created_at)}</p>
                  </div>

                  {/* Actions */}
                  <NotificationRowActions id={n.id} initialStatus={n.status} />
                </div>
              );
            })}
          </div>
        )}
      </div>
    </AdminShell>
  );
}
