-- ValueWeave — consolidated knowledge deployment
--
-- GENERATED FILE. Do not edit.
--   source: scripts/build_deployment_sql.py
--   regenerate: python3 scripts/build_deployment_sql.py
--
-- Paste the whole thing into the Supabase SQL Editor and run it once.
--
-- SAFE TO RE-RUN. Every object is `if not exists` or `create or replace`, every
-- policy is dropped before it is created, and the whole script is ONE
-- TRANSACTION — if any statement fails, nothing is applied and the database is
-- exactly as it was.
--
-- SAFE ON A NON-EMPTY DATABASE. It creates only objects in the `knowledge` and
-- `user_intelligence` schemas, plus one `create or replace` on an existing
-- application function. It touches no application table and deletes nothing.
--
-- WHAT IT DOES NOT DO. Exposing the schemas is a Supabase Dashboard action and
-- no SQL can perform it — Project Settings -> API -> Exposed schemas. Until
-- `knowledge` is listed there, PostgREST refuses every request naming it,
-- INCLUDING requests carrying the service-role key, because that is a server
-- config and not a permission check. The sync will keep failing without it.
--
-- Verify before and after with sql/verify_knowledge_schema.sql.

begin;


-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 0 · Preflight — refuse to run against the wrong database
-- ══════════════════════════════════════════════════════════════════════════

-- Two things must already be true. Both are checked before anything is created,
-- so a database that fails either is left completely untouched.
do $$
begin
  -- (a) This must be the ValueWeave application database.
  if to_regclass('public.profiles') is null then
    raise exception using
      message = 'public.profiles does not exist in this database.',
      hint    = 'This script extends an existing ValueWeave application schema. '
                'Either you are connected to the wrong project, or the base '
                'migrations have never been applied. Do not create a stand-in '
                'profiles table — apply frontend/supabase_schema.sql first.';
  end if;

  -- (b) PHASE 1 creates public.is_valueweave_admin(), whose body reads
  --     p.is_admin. PostgreSQL validates a `language sql` body at CREATE time,
  --     so a missing column fails there, not at first call. The column comes
  --     from frontend/migrations/001_research_articles.sql, which is a separate
  --     migration and may not have been applied.
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'profiles'
      and column_name  = 'is_admin'
  ) then
    raise exception using
      message = 'public.profiles exists but has no is_admin column.',
      hint    = 'public.is_valueweave_admin() reads it, and one policy '
                '(knowledge.sync_runs admin read) depends on that function. '
                'Apply frontend/migrations/001_research_articles.sql, or add '
                'just the column: alter table public.profiles add column if '
                'not exists is_admin boolean not null default false;';
  end if;
end $$;


-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 1 · Prerequisite — public.is_valueweave_admin()
--  source: supabase/migrations/202606200002_entrepreneurship_knowledge_graph.sql
-- ══════════════════════════════════════════════════════════════════════════

-- PHASE 2's final statement (the policy on knowledge.sync_runs) calls this.
-- `create or replace`, so this is a no-op if the CMS migration already ran.
create or replace function public.is_valueweave_admin()
returns boolean language sql stable as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and coalesce(p.is_admin, false) = true
  );
$$;


-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 2 · Knowledge schema — 9 tables, 34 indexes, 9 read policies
--  source: knowledge_sync/migrations/001_knowledge_schema.sql
-- ══════════════════════════════════════════════════════════════════════════
-- ValueWeave Knowledge Schema (Platform v3.0, Step 1)
-- GENERATED by knowledge_sync/generate_migration.py — do not edit by hand.
-- Re-generate after changing knowledge_sync/config.py; CI checks for drift.
--
-- WHY A SEPARATE SCHEMA
-- ---------------------
-- Three of the eight table names this framework needs — kg_skills, kg_schemes and
-- kg_relationships — already exist in `public` as admin-authored CMS tables with
-- different columns, different RLS and a different purpose. Putting the
-- projection in its own schema gives the tables their intended names while
-- guaranteeing that no existing application table is opened, and makes
--
--     drop schema knowledge cascade;
--
-- a complete rollback that cannot reach user data.
--
-- WHAT IS IN EVERY TABLE
-- ----------------------
--   sync_row_key         stable key; the primary key
--   sync_source_*        the package, dataset and row this came from
--   sync_content_hash    change detection; excludes the sync_* columns
--   sync_pending_fields  {column: sentinel} — WHICH values are unknown and WHY
--   sync_deleted_at      soft delete; rows are never removed by a sync
--
-- 8 tables. Git remains the single source of truth; this schema is a
-- read-optimised cache and may be dropped and rebuilt at any time.

create schema if not exists knowledge;
comment on schema knowledge is
  'Read-only projection of the Git knowledge repository. Written only by '
  'knowledge_sync using the service role. Never edit rows here: Git is canonical.';

-- Read access for the application.
grant usage on schema knowledge to anon, authenticated;

-- Write access for the sync, and nothing else.
--
-- An earlier version of this file said the service role "bypasses grants and RLS
-- alike" and granted it nothing. Half of that is true. Supabase's `service_role`
-- has BYPASSRLS, so it is not stopped by row-level security — but BYPASSRLS is
-- not superuser, and GRANT checks still apply. Without the line below the sync
-- fails on its first statement with
--
--     permission denied for schema knowledge
--
-- on SELECT as well as INSERT. PostgreSQL only exempts superusers from privilege
-- checks, and Supabase's service role is deliberately not one. Supabase's own
-- default grants cover `public`; a schema created by a migration gets none.
grant usage on schema knowledge to service_role;


--------------------------------------------------------------------------
-- Global entity registry — every node in the knowledge graph.
-- source: knowledge_graph/entities.csv
-- owner:  knowledge_graph
create table if not exists knowledge.kg_entities (
  sync_row_key                 text primary key,
  global_entity_id             text not null,
  entity_type                  text not null,
  canonical_name               text not null,
  source_package               text not null,
  package_local_id             text,
  status                       text,
  lifecycle_state              text,
  created_at                   date,
  updated_at                   date,
  confidence_score             integer,
  verification_status          text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_entities_live_idx
  on knowledge.kg_entities (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_entities_source_idx
  on knowledge.kg_entities (sync_source_package, sync_source_dataset);
create index if not exists kg_entities_entity_type_idx
  on knowledge.kg_entities (entity_type);
create index if not exists kg_entities_canonical_name_idx
  on knowledge.kg_entities (canonical_name);

--------------------------------------------------------------------------
-- Typed, provenance-carrying edges between entities.
-- source: knowledge_graph/relationships.csv
-- owner:  knowledge_graph
create table if not exists knowledge.kg_relationships (
  sync_row_key                 text primary key,
  relationship_id              text not null,
  from_entity                  text not null,
  relationship_type            text not null,
  to_entity                    text not null,
  confidence                   integer,
  provenance_package           text not null,
  provenance_dataset           text not null,
  provenance_row_id            text not null,
  derived_at                   date,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_relationships_live_idx
  on knowledge.kg_relationships (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_relationships_source_idx
  on knowledge.kg_relationships (sync_source_package, sync_source_dataset);
create index if not exists kg_relationships_from_entity_idx
  on knowledge.kg_relationships (from_entity);
create index if not exists kg_relationships_to_entity_idx
  on knowledge.kg_relationships (to_entity);
create index if not exists kg_relationships_relationship_type_idx
  on knowledge.kg_relationships (relationship_type);

--------------------------------------------------------------------------
-- Districts of Telangana and Andhra Pradesh.
-- source: Package001_Geography/district.csv
-- owner:  Package001_Geography
create table if not exists knowledge.kg_districts (
  sync_row_key                 text primary key,
  dist_id                      text not null,
  district_name                text not null,
  st_id                        text not null,
  district_headquarters        text,
  area_sq_km                   numeric,
  population                   integer,
  mandal_count                 integer,
  density_per_sq_km            numeric,
  urban_pct                    numeric,
  literacy_rate_pct            numeric,
  sex_ratio                    numeric,
  latitude                     numeric,
  longitude                    numeric,
  govt_district_code           text,
  lgd_district_code            text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_districts_live_idx
  on knowledge.kg_districts (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_districts_source_idx
  on knowledge.kg_districts (sync_source_package, sync_source_dataset);
create index if not exists kg_districts_district_name_idx
  on knowledge.kg_districts (district_name);
create index if not exists kg_districts_st_id_idx
  on knowledge.kg_districts (st_id);

--------------------------------------------------------------------------
-- Skills with NSQF level, demand and automation risk.
-- source: Package006_Skills_and_Training/skills.csv
-- owner:  Package006_Skills_and_Training
create table if not exists knowledge.kg_skills (
  sync_row_key                 text primary key,
  skill_id                     text not null,
  skill_name                   text not null,
  category_id                  text,
  category_name                text,
  description                  text,
  difficulty_level             text,
  nsqf_level                   integer,
  learning_duration            text,
  demand_level                 text,
  automation_risk              text,
  ai_augmentation_level        text,
  future_demand                text,
  self_employment_score        integer,
  startup_opportunity          text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_skills_live_idx
  on knowledge.kg_skills (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_skills_source_idx
  on knowledge.kg_skills (sync_source_package, sync_source_dataset);
create index if not exists kg_skills_category_name_idx
  on knowledge.kg_skills (category_name);
create index if not exists kg_skills_skill_name_idx
  on knowledge.kg_skills (skill_name);

--------------------------------------------------------------------------
-- Government schemes — Package007 is the authoritative owner (ADR-003).
-- source: Package007_Government_Schemes/government_schemes.csv
-- owner:  Package007_Government_Schemes
create table if not exists knowledge.kg_schemes (
  sync_row_key                 text primary key,
  scheme_id                    text not null,
  scheme_name                  text not null,
  short_name                   text,
  category_id                  text,
  category_name                text,
  ministry                     text,
  department                   text,
  government_level             text,
  launch_year                  integer,
  objective                    text,
  benefit_summary              text,
  financial_assistance         text,
  subsidy_component            text,
  loan_support                 text,
  coverage                     text,
  application_mode             text,
  official_portal              text,
  status                       text,
  also_in_package              text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_schemes_live_idx
  on knowledge.kg_schemes (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_schemes_source_idx
  on knowledge.kg_schemes (sync_source_package, sync_source_dataset);
create index if not exists kg_schemes_category_name_idx
  on knowledge.kg_schemes (category_name);
create index if not exists kg_schemes_scheme_name_idx
  on knowledge.kg_schemes (scheme_name);

--------------------------------------------------------------------------
-- MSME businesses and business opportunities. Unions Package008's researched MSMEs with Package004's four opportunity datasets.
-- source: Package008_MSME/msme_businesses.csv, Package004_Industries/food_agro_processing_micro_enterprises.csv, Package004_Industries/construction_skilled_trade_services.csv, Package004_Industries/digital_technology_livelihoods.csv, Package004_Industries/china_inspired_adapted_opportunities.csv
-- owner:  Package008_MSME
create table if not exists knowledge.kg_businesses (
  sync_row_key                 text primary key,
  business_id                  text,
  id                           text,
  business_kind                text not null,
  business_name                text,
  name                         text,
  category_id                  text,
  category_name                text,
  description                  text,
  udyam_classification         text,
  investment_range             text,
  minimum_investment           text,
  working_capital_need         text,
  employment_generation        text,
  difficulty                   text,
  risk_level                   text,
  technology_level             text,
  automation_level             text,
  ai_readiness                 text,
  profitability_outlook        text,
  ideal_target_audience        text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_businesses_live_idx
  on knowledge.kg_businesses (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_businesses_source_idx
  on knowledge.kg_businesses (sync_source_package, sync_source_dataset);
create index if not exists kg_businesses_category_name_idx
  on knowledge.kg_businesses (category_name);
create index if not exists kg_businesses_business_name_idx
  on knowledge.kg_businesses (business_name);
create index if not exists kg_businesses_business_kind_idx
  on knowledge.kg_businesses (business_kind);

--------------------------------------------------------------------------
-- MSME sector taxonomy. Package004 has no standalone industry dataset — its industries are embedded in opportunity rows — so the graph's 78 Industry nodes stay in kg_entities and this table is the browsable sector list.
-- source: Package008_MSME/msme_categories.csv
-- owner:  Package008_MSME
create table if not exists knowledge.kg_industries (
  sync_row_key                 text primary key,
  category_id                  text not null,
  category_name                text not null,
  category_group               text,
  description                  text,
  nic_section_hint             text,
  capital_intensity            text,
  skill_intensity              text,
  typical_udyam_class          text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_industries_live_idx
  on knowledge.kg_industries (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_industries_source_idx
  on knowledge.kg_industries (sync_source_package, sync_source_dataset);
create index if not exists kg_industries_category_name_idx
  on knowledge.kg_industries (category_name);

--------------------------------------------------------------------------
-- Crops with agronomic attributes (Package005).
-- source: Package005_Agriculture/crops.csv
-- owner:  Package005_Agriculture
create table if not exists knowledge.kg_agriculture (
  sync_row_key                 text primary key,
  crop_id                      text not null,
  crop_name                    text not null,
  scientific_name              text,
  category_id                  text,
  category_name                text,
  season                       text,
  duration_days                integer,
  water_requirement_mm         integer,
  soil_type_preferred          text,
  rainfall_mm                  integer,
  temperature_min_c            numeric,
  temperature_max_c            numeric,
  avg_yield_tons_per_ha        numeric,
  major_states                 text,
  major_districts              text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_agriculture_live_idx
  on knowledge.kg_agriculture (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_agriculture_source_idx
  on knowledge.kg_agriculture (sync_source_package, sync_source_dataset);
create index if not exists kg_agriculture_category_name_idx
  on knowledge.kg_agriculture (category_name);
create index if not exists kg_agriculture_crop_name_idx
  on knowledge.kg_agriculture (crop_name);

--------------------------------------------------------------------------
-- Row level security

alter table knowledge.kg_entities enable row level security;

drop policy if exists "kg_entities public read" on knowledge.kg_entities;
create policy "kg_entities public read"
  on knowledge.kg_entities for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_relationships enable row level security;

drop policy if exists "kg_relationships public read" on knowledge.kg_relationships;
create policy "kg_relationships public read"
  on knowledge.kg_relationships for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_districts enable row level security;

drop policy if exists "kg_districts public read" on knowledge.kg_districts;
create policy "kg_districts public read"
  on knowledge.kg_districts for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_skills enable row level security;

drop policy if exists "kg_skills public read" on knowledge.kg_skills;
create policy "kg_skills public read"
  on knowledge.kg_skills for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_schemes enable row level security;

drop policy if exists "kg_schemes public read" on knowledge.kg_schemes;
create policy "kg_schemes public read"
  on knowledge.kg_schemes for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_businesses enable row level security;

drop policy if exists "kg_businesses public read" on knowledge.kg_businesses;
create policy "kg_businesses public read"
  on knowledge.kg_businesses for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_industries enable row level security;

drop policy if exists "kg_industries public read" on knowledge.kg_industries;
create policy "kg_industries public read"
  on knowledge.kg_industries for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_agriculture enable row level security;

drop policy if exists "kg_agriculture public read" on knowledge.kg_agriculture;
create policy "kg_agriculture public read"
  on knowledge.kg_agriculture for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

--------------------------------------------------------------------------
-- Default grants for tables created above, plus anything added later.
grant select on all tables in schema knowledge to anon, authenticated;
alter default privileges in schema knowledge
  grant select on tables to anon, authenticated;

-- The sync writes with select/insert/update and nothing more. It upserts rows
-- and it soft-deletes by setting sync_deleted_at — see knowledge_sync/adapters.py,
-- which contains no hard delete at all. DELETE and TRUNCATE are therefore withheld
-- on purpose: a bug in the sync cannot destroy the projection, only mark it.
grant select, insert, update on all tables in schema knowledge to service_role;
grant usage on all sequences in schema knowledge to service_role;
alter default privileges in schema knowledge
  grant select, insert, update on tables to service_role;
alter default privileges in schema knowledge
  grant usage on sequences to service_role;

-- Sync bookkeeping. One row per run, so an operator can answer "what happened on
-- the 14th" from SQL rather than from a log file on whichever machine ran it.
create table if not exists knowledge.sync_runs (
  run_id            text primary key,
  mode              text not null,
  outcome           text not null,
  version           text,
  started_at        timestamptz not null,
  finished_at       timestamptz,
  duration_seconds  numeric,
  rows_inserted     integer not null default 0,
  rows_updated      integer not null default 0,
  rows_deleted      integer not null default 0,
  rows_skipped      integer not null default 0,
  validation_errors integer not null default 0,
  metrics           jsonb not null default '{}'::jsonb
);
create index if not exists sync_runs_started_idx
  on knowledge.sync_runs (started_at desc);

alter table knowledge.sync_runs enable row level security;
drop policy if exists "sync runs admin read" on knowledge.sync_runs;
create policy "sync runs admin read"
  on knowledge.sync_runs for select
  using (public.is_valueweave_admin());


-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 3 · Vocabulary crosswalk repair — the table 009 could not create
--  source: frontend/migrations/011_repair_vocabulary_crosswalk.sql
-- ══════════════════════════════════════════════════════════════════════════
-- ValueWeave — migration 011: repair the vocabulary crosswalk table.
--
-- WHAT THIS REPAIRS
-- -----------------
-- `009_vocabulary_crosswalk.sql` declares
--
--     global_entity_id text references public.kg_entity_registry(global_entity_id)
--
-- and `public.kg_entity_registry` is created by no migration in this repository. It
-- was to come from the planned `008_knowledge_platform_projection.sql`; Platform v3.0
-- Step 1 replaced that plan with the dedicated `knowledge` schema, and 009 kept a
-- reference to a table that was never built. Applying the migrations in order fails:
--
--     ERROR:  relation "public.kg_entity_registry" does not exist
--
-- Migration 009 is NOT modified. It stays in history exactly as it shipped, and this
-- migration moves forward from whatever state the database is actually in.
--
-- THE SECOND DEFECT, FIXED HERE TOO
-- ---------------------------------
-- 009 creates the table in `public`. `frontend/lib/knowledge.js` queries it through a
-- client scoped to the `knowledge` schema, so even a successfully applied 009 would
-- have produced a table nothing could read. Vocabulary resolution is the only bridge
-- from a user's typed skill to a graph entity, so this is not cosmetic: without it
-- every district and skill silently fails to resolve.
--
-- The table belongs in `knowledge` — it is derived from `governance/vocabulary/*.csv`
-- by the same generate-and-project pipeline as the rest of that schema.
--
-- FOUR STATES THIS MUST HANDLE
-- ----------------------------
--   A  fresh database, 009 failed        -> create in `knowledge`
--   B  009 applied (pre-existing DB)     -> drop the FK, move to `knowledge`
--   C  011 already applied               -> do nothing
--   D  both `public` and `knowledge` copies exist -> keep `knowledge`, leave `public`
--
-- Every statement is guarded, so this file is safe to run repeatedly. It is written
-- as one transaction: a half-repaired crosswalk resolves some terms and not others,
-- which is worse than none resolving, because the failure looks like missing data.
--
-- NO FOREIGN KEY IS RE-ADDED, DELIBERATELY
-- ----------------------------------------
-- The referent is `knowledge.kg_entities`, which `knowledge_sync` soft-deletes from
-- (`sync_deleted_at`), never hard-deletes. A real FK would therefore never fire in
-- normal operation, and on the one path where it could — `sync --full` after a
-- restore — it would block a legitimate rebuild.
--
-- Integrity is enforced where it can be, and it is enough:
--   * `kg_vocab_resolution_is_coherent` CHECK — a resolved row must name an entity,
--     an unresolved row must not. Carried over from 009.
--   * `tests/test_vocabulary.py` — every resolved row points at a real entity of the
--     right type, checked against `entities.csv` on every test run.
--   * `scripts/health_check.sh` — reports crosswalk rows whose entity is missing
--     from the projection, so drift is visible rather than silently blocking writes.

-- [consolidated] removed `begin;` — the whole script runs in one transaction

create schema if not exists knowledge;

-- ── State A · the table does not exist anywhere ────────────────────────────
create table if not exists knowledge.kg_vocabulary_map (
  id               bigserial   primary key,
  term_kind        text        not null check (term_kind in ('skill','sector','district','tag')),
  source_vocab     text        not null,
  source_term      text        not null,
  normalised_term  text        not null,

  -- No FK. See the header.
  global_entity_id text,
  entity_type      text,
  canonical_name   text,

  match_method     text        not null check (match_method in
                     ('EXACT_NAME','ALIAS','PREFIX','FUZZY','CURATED','NO_COUNTERPART')),
  match_score      numeric(6,4),
  notes            text,

  synced_at        timestamptz not null default now(),

  -- Carried over from 009. The invariant the dropped FK was reaching for:
  -- a resolved row points somewhere, an unresolved row points nowhere.
  constraint kg_vocab_resolution_is_coherent check (
    (match_method = 'NO_COUNTERPART' and global_entity_id is null)
    or (match_method <> 'NO_COUNTERPART' and global_entity_id is not null)
  ),

  unique (term_kind, source_vocab, normalised_term)
);

-- ── State B · 009 applied, so a `public` copy exists ───────────────────────
do $$
declare
  has_public   boolean;
  moved_rows   bigint;
begin
  select exists (
    select 1 from information_schema.tables
     where table_schema = 'public' and table_name = 'kg_vocabulary_map'
  ) into has_public;

  if not has_public then
    raise notice '011: no public.kg_vocabulary_map — nothing to migrate (state A or C)';
    return;
  end if;

  -- Drop the unbuildable foreign key wherever it landed. Named dynamically
  -- because Postgres generates the constraint name.
  execute (
    select coalesce(string_agg(
      format('alter table public.kg_vocabulary_map drop constraint %I;', conname), ' '), '')
      from pg_constraint
     where conrelid = 'public.kg_vocabulary_map'::regclass
       and contype = 'f'
  );

  -- Copy rows across. `on conflict do nothing` makes state D safe: if a
  -- `knowledge` copy already holds a term, the projected row wins.
  insert into knowledge.kg_vocabulary_map
        (term_kind, source_vocab, source_term, normalised_term,
         global_entity_id, entity_type, canonical_name,
         match_method, match_score, notes)
  select term_kind, source_vocab, source_term, normalised_term,
         global_entity_id, entity_type, canonical_name,
         match_method, match_score, notes
    from public.kg_vocabulary_map
      on conflict (term_kind, source_vocab, normalised_term) do nothing;

  get diagnostics moved_rows = row_count;
  raise notice '011: migrated % row(s) from public to knowledge', moved_rows;

  -- The `public` table is left in place, empty of purpose but not dropped.
  --
  -- Dropping a table in a repair migration is how a rollback becomes
  -- irreversible. Anything still reading `public.kg_vocabulary_map` keeps
  -- working, and retiring it is a separate, reviewable decision.
  comment on table public.kg_vocabulary_map is
    'SUPERSEDED by knowledge.kg_vocabulary_map (migration 011). Retained for '
    'rollback safety; no application code reads this table. Safe to drop once '
    '011 is confirmed in every environment.';
end $$;

-- ── Indexes ────────────────────────────────────────────────────────────────
-- `resolveTerms()` looks up by (term_kind, normalised_term) and by nothing else,
-- so that index is the one that matters. The entity index serves the reverse
-- question — "what did users call this?" — used by the health check.
create index if not exists kg_vocab_lookup_idx
  on knowledge.kg_vocabulary_map (term_kind, normalised_term);
create index if not exists kg_vocab_entity_idx
  on knowledge.kg_vocabulary_map (global_entity_id)
  where global_entity_id is not null;
create index if not exists kg_vocab_method_idx
  on knowledge.kg_vocabulary_map (match_method);

-- ── RLS ────────────────────────────────────────────────────────────────────
-- Same posture as the rest of the `knowledge` schema: public reference data,
-- readable by anyone, writable by nobody. The crosswalk is derived from Git, so a
-- hand-edit would be reverted by the next load and lost from source control. No
-- write policy exists, which makes that impossible rather than discouraged.
alter table knowledge.kg_vocabulary_map enable row level security;

drop policy if exists kg_vocabulary_map_read on knowledge.kg_vocabulary_map;
create policy kg_vocabulary_map_read
  on knowledge.kg_vocabulary_map for select
  using (true);

grant usage on schema knowledge to anon, authenticated;
grant select on knowledge.kg_vocabulary_map to anon, authenticated;

-- The sync writes this table too, and Supabase's service_role is not a superuser:
-- BYPASSRLS exempts it from row-level security, not from GRANT checks. Without
-- these it fails with `permission denied for schema knowledge`. Same posture as
-- the rest of the schema — no DELETE, because the sync soft-deletes.
grant usage on schema knowledge to service_role;
grant select, insert, update on knowledge.kg_vocabulary_map to service_role;
grant usage on all sequences in schema knowledge to service_role;

-- [consolidated] removed `commit;` — the whole script runs in one transaction

-- ── Verify ─────────────────────────────────────────────────────────────────
--   select count(*) from knowledge.kg_vocabulary_map;            -- 202 after load
--   select term_kind, count(*) from knowledge.kg_vocabulary_map  -- 33 / 22 / 147
--    group by 1 order by 1;
--   select count(*) from pg_constraint                           -- 0
--    where conrelid = 'knowledge.kg_vocabulary_map'::regclass and contype = 'f';
--
-- Rollback: `drop table knowledge.kg_vocabulary_map;`. The `public` copy is intact,
-- so this migration is reversible without data loss.

-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 4 · User intelligence — 5 tables, RLS scoped to auth.uid()
--  source: user_intelligence/migrations/001_user_intelligence.sql
-- ══════════════════════════════════════════════════════════════════════════
-- ValueWeave User Intelligence (Platform v3.0, Step 1.5)
-- GENERATED by user_intelligence/generate_migration.py — do not edit by hand.
--
-- Five derived tables, one per output the brief specifies. Everything here is
-- recomputable from `profiles` plus a knowledge snapshot, so the whole schema is
-- disposable:
--
--     drop schema user_intelligence cascade;
--
-- A separate schema means this migration cannot reach profiles, connections,
-- opportunities or any other application table — by construction rather than by
-- care.
--
-- EVERY ROW CARRIES ITS PROVENANCE
--   rules_version   which logic produced it
--   result_hash     proves two runs over the same input agree
--   generated_at    when
--   reason          why, in words
--   evidence        which entities and edges, as jsonb
--
-- Rows are keyed on (user_id, rules_version): a recommendation a user acted on
-- must remain explainable after the rules change.

create schema if not exists user_intelligence;
comment on schema user_intelligence is
  'Derived per-user intelligence. Recomputable from profiles + the knowledge '
  'graph; safe to drop and rebuild. Written only by the intelligence engine.';

grant usage on schema user_intelligence to authenticated;

-- ─────────────────────────────────────────────────────── user_skill_profile
create table if not exists user_intelligence.user_skill_profile (
  user_id                uuid        not null references public.profiles(id) on delete cascade,
  rules_version          text        not null,
  score                  numeric(5,2),
  status                 text        not null,
  confidence             smallint    not null default 0,
  reason                 text        not null,
  claimed_skill_count    integer     not null default 0,
  resolved_skill_count   integer     not null default 0,
  resolve_rate_pct       numeric(5,2),
  resolved_skills        jsonb       not null default '[]'::jsonb,
  -- The honest half. Skills the user claims that the knowledge base has no
  -- researched counterpart for: 50 such skills exist today (Step 0).
  unresolved_skills      jsonb       not null default '[]'::jsonb,
  categories             jsonb       not null default '[]'::jsonb,
  evidence               jsonb       not null default '[]'::jsonb,
  generated_at           timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ──────────────────────────────────────────────────── user_business_profile
-- One row per user holding the five business-facing scores as jsonb. Separate
-- columns would need a migration every time a score is added; the score keys are
-- constrained by the engine, which is where they are declared.
create table if not exists user_intelligence.user_business_profile (
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  business_readiness   jsonb       not null default '{}'::jsonb,
  district_opportunity jsonb       not null default '{}'::jsonb,
  ai_readiness         jsonb       not null default '{}'::jsonb,
  funding_readiness    jsonb       not null default '{}'::jsonb,
  startup_readiness    jsonb       not null default '{}'::jsonb,
  generated_at         timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ──────────────────────────────────────────────────── user_learning_profile
create table if not exists user_intelligence.user_learning_profile (
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  score                numeric(5,2),
  status               text        not null,
  confidence           smallint    not null default 0,
  reason               text        not null,
  distinct_gaps        integer     not null default 0,
  steps_with_provider  integer     not null default 0,
  roadmap              jsonb       not null default '[]'::jsonb,
  recommended_courses  jsonb       not null default '[]'::jsonb,
  generated_at         timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ───────────────────────────────────────────────────── user_recommendations
-- One row per recommendation. The four fields the brief requires are all NOT
-- NULL: a recommendation without a reason, evidence, confidence or timestamp is
-- not a recommendation this engine is willing to store.
create table if not exists user_intelligence.user_recommendations (
  id                   bigserial   primary key,
  user_id              uuid        not null references public.profiles(id) on delete cascade,
  rules_version        text        not null,
  category             text        not null check (category in ('business_ideas', 'government_schemes', 'courses', 'research', 'mentors', 'collaborators', 'events', 'markets', 'msmes', 'industries')),
  category_status      text        not null,
  rank                 integer     not null,
  item_id              text        not null,
  item_label           text        not null,
  item_type            text        not null,
  match_score          numeric(5,2) not null,
  confidence           smallint    not null,
  confidence_band      text        not null,
  reason               text        not null,
  rule                 text        not null,
  supporting_entities  jsonb       not null default '[]'::jsonb,
  detail               jsonb       not null default '{}'::jsonb,
  unverified_notice    text        not null,
  generated_at         timestamptz not null default now(),
  unique (user_id, rules_version, category, item_id)
);

-- ─────────────────────────────────────────────────── user_activity_summary
create table if not exists user_intelligence.user_activity_summary (
  user_id                  uuid        not null references public.profiles(id) on delete cascade,
  rules_version            text        not null,
  engine_version           text        not null,
  scores                   jsonb       not null default '{}'::jsonb,
  recommendations_by_category jsonb    not null default '{}'::jsonb,
  total_recommendations    integer     not null default 0,
  -- Which scores could not be computed, and which categories have no data at all
  -- (mentors, events). Stored so a UI can explain a gap instead of rendering a blank.
  scores_unavailable       jsonb       not null default '[]'::jsonb,
  categories_without_data  jsonb       not null default '[]'::jsonb,
  inputs_unavailable       jsonb       not null default '[]'::jsonb,
  accepted_connections     integer     not null default 0,
  pending_connections      integer     not null default 0,
  profile_complete         boolean     not null default false,
  knowledge_snapshot_hash  text        not null,
  result_hash              text        not null,
  generated_at             timestamptz not null default now(),
  primary key (user_id, rules_version)
);

-- ───────────────────────────────────────────────────────────────── indexes
create index if not exists user_recs_user_idx
  on user_intelligence.user_recommendations (user_id, category, rank);
create index if not exists user_recs_item_idx
  on user_intelligence.user_recommendations (item_id);
create index if not exists user_recs_generated_idx
  on user_intelligence.user_recommendations (generated_at desc);
create index if not exists user_summary_hash_idx
  on user_intelligence.user_activity_summary (result_hash);

-- ───────────────────────────────────────────────── row level security
-- A user reads their own intelligence and nobody else's. `auth.uid() = user_id`
-- is the whole policy, and there is deliberately no admin-read exception: these
-- rows are derived from a profile and describe that person.

alter table user_intelligence.user_skill_profile enable row level security;
drop policy if exists "user_skill_profile own read" on user_intelligence.user_skill_profile;
create policy "user_skill_profile own read"
  on user_intelligence.user_skill_profile for select
  using (auth.uid() = user_id);

alter table user_intelligence.user_business_profile enable row level security;
drop policy if exists "user_business_profile own read" on user_intelligence.user_business_profile;
create policy "user_business_profile own read"
  on user_intelligence.user_business_profile for select
  using (auth.uid() = user_id);

alter table user_intelligence.user_learning_profile enable row level security;
drop policy if exists "user_learning_profile own read" on user_intelligence.user_learning_profile;
create policy "user_learning_profile own read"
  on user_intelligence.user_learning_profile for select
  using (auth.uid() = user_id);

alter table user_intelligence.user_recommendations enable row level security;
drop policy if exists "user_recommendations own read" on user_intelligence.user_recommendations;
create policy "user_recommendations own read"
  on user_intelligence.user_recommendations for select
  using (auth.uid() = user_id);

alter table user_intelligence.user_activity_summary enable row level security;
drop policy if exists "user_activity_summary own read" on user_intelligence.user_activity_summary;
create policy "user_activity_summary own read"
  on user_intelligence.user_activity_summary for select
  using (auth.uid() = user_id);

-- No insert, update or delete policy on any table. The engine writes with the
-- service role, which bypasses RLS; nothing reachable by a user session can
-- fabricate a recommendation.

grant select on all tables in schema user_intelligence to authenticated;
alter default privileges in schema user_intelligence
  grant select on tables to authenticated;

-- The engine's own grants. "Bypasses RLS" above is accurate and remains true —
-- but BYPASSRLS is not superuser, and GRANT checks are separate. Supabase's
-- default privileges cover `public` only, so a schema created here starts with
-- the service role holding nothing, and the engine's first statement fails with
-- `permission denied for schema user_intelligence`.
--
-- DELETE is granted here and withheld in `knowledge`, and the difference is real:
-- user_intelligence/writer.py hard-deletes a user's stale recommendations before
-- rewriting them, whereas the knowledge sync only ever sets sync_deleted_at.
grant usage on schema user_intelligence to service_role;
grant select, insert, update, delete on all tables in schema user_intelligence to service_role;
grant usage on all sequences in schema user_intelligence to service_role;
alter default privileges in schema user_intelligence
  grant select, insert, update, delete on tables to service_role;
alter default privileges in schema user_intelligence
  grant usage on sequences to service_role;

-- Current rules version at generation time: 1.0.0
-- Scores produced: 'skill_profile', 'business_readiness', 'learning_roadmap', 'district_opportunity', 'collaboration_score', 'ai_readiness', 'funding_readiness', 'startup_readiness'

-- ══════════════════════════════════════════════════════════════════════════
-- PHASE 5 · Commit
-- ══════════════════════════════════════════════════════════════════════════
commit;
