-- ValueWeave Knowledge Schema (Platform v3.0, Step 1)
-- GENERATED by knowledge_sync/generate_migration.py — do not edit by hand.
-- Re-generate after changing knowledge_sync/config.py; CI checks for drift.
--
-- WHY A SEPARATE SCHEMA
-- ---------------------
-- Three of the eight table names this framework needs — kg_skills, kg_schemes and
-- kg_relationships — already exist in `public` as admin-authored CMS tables with
-- different columns, different RLS and a different purpose. Putting the
-- projection in its own schema gives the tables their intended names while
-- guaranteeing that no existing application table is opened, and makes
--
--     drop schema knowledge cascade;
--
-- a complete rollback that cannot reach user data.
--
-- WHAT IS IN EVERY TABLE
-- ----------------------
--   sync_row_key         stable key; the primary key
--   sync_source_*        the package, dataset and row this came from
--   sync_content_hash    change detection; excludes the sync_* columns
--   sync_pending_fields  {column: sentinel} — WHICH values are unknown and WHY
--   sync_deleted_at      soft delete; rows are never removed by a sync
--
-- 8 tables. Git remains the single source of truth; this schema is a
-- read-optimised cache and may be dropped and rebuilt at any time.

create schema if not exists knowledge;
comment on schema knowledge is
  'Read-only projection of the Git knowledge repository. Written only by '
  'knowledge_sync using the service role. Never edit rows here: Git is canonical.';

-- Read access for the application. Writes are not granted to anyone: the sync
-- uses the service role, which bypasses grants and RLS alike.
grant usage on schema knowledge to anon, authenticated;


--------------------------------------------------------------------------
-- Global entity registry — every node in the knowledge graph.
-- source: knowledge_graph/entities.csv
-- owner:  knowledge_graph
create table if not exists knowledge.kg_entities (
  sync_row_key                 text primary key,
  global_entity_id             text not null,
  entity_type                  text not null,
  canonical_name               text not null,
  source_package               text not null,
  package_local_id             text,
  status                       text,
  lifecycle_state              text,
  created_at                   date,
  updated_at                   date,
  confidence_score             integer,
  verification_status          text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_entities_live_idx
  on knowledge.kg_entities (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_entities_source_idx
  on knowledge.kg_entities (sync_source_package, sync_source_dataset);
create index if not exists kg_entities_entity_type_idx
  on knowledge.kg_entities (entity_type);
create index if not exists kg_entities_canonical_name_idx
  on knowledge.kg_entities (canonical_name);

--------------------------------------------------------------------------
-- Typed, provenance-carrying edges between entities.
-- source: knowledge_graph/relationships.csv
-- owner:  knowledge_graph
create table if not exists knowledge.kg_relationships (
  sync_row_key                 text primary key,
  relationship_id              text not null,
  from_entity                  text not null,
  relationship_type            text not null,
  to_entity                    text not null,
  confidence                   integer,
  provenance_package           text not null,
  provenance_dataset           text not null,
  provenance_row_id            text not null,
  derived_at                   date,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_relationships_live_idx
  on knowledge.kg_relationships (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_relationships_source_idx
  on knowledge.kg_relationships (sync_source_package, sync_source_dataset);
create index if not exists kg_relationships_from_entity_idx
  on knowledge.kg_relationships (from_entity);
create index if not exists kg_relationships_to_entity_idx
  on knowledge.kg_relationships (to_entity);
create index if not exists kg_relationships_relationship_type_idx
  on knowledge.kg_relationships (relationship_type);

--------------------------------------------------------------------------
-- Districts of Telangana and Andhra Pradesh.
-- source: Package001_Geography/district.csv
-- owner:  Package001_Geography
create table if not exists knowledge.kg_districts (
  sync_row_key                 text primary key,
  dist_id                      text not null,
  district_name                text not null,
  st_id                        text not null,
  district_headquarters        text,
  area_sq_km                   numeric,
  population                   integer,
  mandal_count                 integer,
  density_per_sq_km            numeric,
  urban_pct                    numeric,
  literacy_rate_pct            numeric,
  sex_ratio                    numeric,
  latitude                     numeric,
  longitude                    numeric,
  govt_district_code           text,
  lgd_district_code            text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_districts_live_idx
  on knowledge.kg_districts (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_districts_source_idx
  on knowledge.kg_districts (sync_source_package, sync_source_dataset);
create index if not exists kg_districts_district_name_idx
  on knowledge.kg_districts (district_name);
create index if not exists kg_districts_st_id_idx
  on knowledge.kg_districts (st_id);

--------------------------------------------------------------------------
-- Skills with NSQF level, demand and automation risk.
-- source: Package006_Skills_and_Training/skills.csv
-- owner:  Package006_Skills_and_Training
create table if not exists knowledge.kg_skills (
  sync_row_key                 text primary key,
  skill_id                     text not null,
  skill_name                   text not null,
  category_id                  text,
  category_name                text,
  description                  text,
  difficulty_level             text,
  nsqf_level                   integer,
  learning_duration            text,
  demand_level                 text,
  automation_risk              text,
  ai_augmentation_level        text,
  future_demand                text,
  self_employment_score        integer,
  startup_opportunity          text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_skills_live_idx
  on knowledge.kg_skills (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_skills_source_idx
  on knowledge.kg_skills (sync_source_package, sync_source_dataset);
create index if not exists kg_skills_category_name_idx
  on knowledge.kg_skills (category_name);
create index if not exists kg_skills_skill_name_idx
  on knowledge.kg_skills (skill_name);

--------------------------------------------------------------------------
-- Government schemes — Package007 is the authoritative owner (ADR-003).
-- source: Package007_Government_Schemes/government_schemes.csv
-- owner:  Package007_Government_Schemes
create table if not exists knowledge.kg_schemes (
  sync_row_key                 text primary key,
  scheme_id                    text not null,
  scheme_name                  text not null,
  short_name                   text,
  category_id                  text,
  category_name                text,
  ministry                     text,
  department                   text,
  government_level             text,
  launch_year                  integer,
  objective                    text,
  benefit_summary              text,
  financial_assistance         text,
  subsidy_component            text,
  loan_support                 text,
  coverage                     text,
  application_mode             text,
  official_portal              text,
  status                       text,
  also_in_package              text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_schemes_live_idx
  on knowledge.kg_schemes (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_schemes_source_idx
  on knowledge.kg_schemes (sync_source_package, sync_source_dataset);
create index if not exists kg_schemes_category_name_idx
  on knowledge.kg_schemes (category_name);
create index if not exists kg_schemes_scheme_name_idx
  on knowledge.kg_schemes (scheme_name);

--------------------------------------------------------------------------
-- MSME businesses and business opportunities. Unions Package008's researched MSMEs with Package004's four opportunity datasets.
-- source: Package008_MSME/msme_businesses.csv, Package004_Industries/food_agro_processing_micro_enterprises.csv, Package004_Industries/construction_skilled_trade_services.csv, Package004_Industries/digital_technology_livelihoods.csv, Package004_Industries/china_inspired_adapted_opportunities.csv
-- owner:  Package008_MSME
create table if not exists knowledge.kg_businesses (
  sync_row_key                 text primary key,
  business_id                  text,
  id                           text,
  business_kind                text not null,
  business_name                text,
  name                         text,
  category_id                  text,
  category_name                text,
  description                  text,
  udyam_classification         text,
  investment_range             text,
  minimum_investment           text,
  working_capital_need         text,
  employment_generation        text,
  difficulty                   text,
  risk_level                   text,
  technology_level             text,
  automation_level             text,
  ai_readiness                 text,
  profitability_outlook        text,
  ideal_target_audience        text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_businesses_live_idx
  on knowledge.kg_businesses (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_businesses_source_idx
  on knowledge.kg_businesses (sync_source_package, sync_source_dataset);
create index if not exists kg_businesses_category_name_idx
  on knowledge.kg_businesses (category_name);
create index if not exists kg_businesses_business_name_idx
  on knowledge.kg_businesses (business_name);
create index if not exists kg_businesses_business_kind_idx
  on knowledge.kg_businesses (business_kind);

--------------------------------------------------------------------------
-- MSME sector taxonomy. Package004 has no standalone industry dataset — its industries are embedded in opportunity rows — so the graph's 78 Industry nodes stay in kg_entities and this table is the browsable sector list.
-- source: Package008_MSME/msme_categories.csv
-- owner:  Package008_MSME
create table if not exists knowledge.kg_industries (
  sync_row_key                 text primary key,
  category_id                  text not null,
  category_name                text not null,
  category_group               text,
  description                  text,
  nic_section_hint             text,
  capital_intensity            text,
  skill_intensity              text,
  typical_udyam_class          text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_industries_live_idx
  on knowledge.kg_industries (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_industries_source_idx
  on knowledge.kg_industries (sync_source_package, sync_source_dataset);
create index if not exists kg_industries_category_name_idx
  on knowledge.kg_industries (category_name);

--------------------------------------------------------------------------
-- Crops with agronomic attributes (Package005).
-- source: Package005_Agriculture/crops.csv
-- owner:  Package005_Agriculture
create table if not exists knowledge.kg_agriculture (
  sync_row_key                 text primary key,
  crop_id                      text not null,
  crop_name                    text not null,
  scientific_name              text,
  category_id                  text,
  category_name                text,
  season                       text,
  duration_days                integer,
  water_requirement_mm         integer,
  soil_type_preferred          text,
  rainfall_mm                  integer,
  temperature_min_c            numeric,
  temperature_max_c            numeric,
  avg_yield_tons_per_ha        numeric,
  major_states                 text,
  major_districts              text,
  data_source                  text,
  source_url                   text,
  collection_date              text,
  confidence_score             integer,
  verification_status          text,
  notes                        text,
  sync_source_package          text not null,
  sync_source_dataset          text not null,
  sync_source_row_id           text not null,
  sync_content_hash            text not null,
  sync_pending_fields          jsonb not null default '{}'::jsonb,
  sync_version                 text not null,
  sync_synced_at               timestamptz not null default now(),
  sync_deleted_at              timestamptz
);
create index if not exists kg_agriculture_live_idx
  on knowledge.kg_agriculture (sync_row_key)
  where sync_deleted_at is null;
create index if not exists kg_agriculture_source_idx
  on knowledge.kg_agriculture (sync_source_package, sync_source_dataset);
create index if not exists kg_agriculture_category_name_idx
  on knowledge.kg_agriculture (category_name);
create index if not exists kg_agriculture_crop_name_idx
  on knowledge.kg_agriculture (crop_name);

--------------------------------------------------------------------------
-- Row level security

alter table knowledge.kg_entities enable row level security;

drop policy if exists "kg_entities public read" on knowledge.kg_entities;
create policy "kg_entities public read"
  on knowledge.kg_entities for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_relationships enable row level security;

drop policy if exists "kg_relationships public read" on knowledge.kg_relationships;
create policy "kg_relationships public read"
  on knowledge.kg_relationships for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_districts enable row level security;

drop policy if exists "kg_districts public read" on knowledge.kg_districts;
create policy "kg_districts public read"
  on knowledge.kg_districts for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_skills enable row level security;

drop policy if exists "kg_skills public read" on knowledge.kg_skills;
create policy "kg_skills public read"
  on knowledge.kg_skills for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_schemes enable row level security;

drop policy if exists "kg_schemes public read" on knowledge.kg_schemes;
create policy "kg_schemes public read"
  on knowledge.kg_schemes for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_businesses enable row level security;

drop policy if exists "kg_businesses public read" on knowledge.kg_businesses;
create policy "kg_businesses public read"
  on knowledge.kg_businesses for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_industries enable row level security;

drop policy if exists "kg_industries public read" on knowledge.kg_industries;
create policy "kg_industries public read"
  on knowledge.kg_industries for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

alter table knowledge.kg_agriculture enable row level security;

drop policy if exists "kg_agriculture public read" on knowledge.kg_agriculture;
create policy "kg_agriculture public read"
  on knowledge.kg_agriculture for select
  using (sync_deleted_at is null);

-- No insert/update/delete policy exists, deliberately. The sync uses the service
-- role, which bypasses RLS; anon and authenticated therefore cannot write here at
-- all. "Never edit package data inside Supabase" is enforced by the absence of a
-- policy rather than by convention.

--------------------------------------------------------------------------
-- Default grants for tables created above, plus anything added later.
grant select on all tables in schema knowledge to anon, authenticated;
alter default privileges in schema knowledge
  grant select on tables to anon, authenticated;

-- Sync bookkeeping. One row per run, so an operator can answer "what happened on
-- the 14th" from SQL rather than from a log file on whichever machine ran it.
create table if not exists knowledge.sync_runs (
  run_id            text primary key,
  mode              text not null,
  outcome           text not null,
  version           text,
  started_at        timestamptz not null,
  finished_at       timestamptz,
  duration_seconds  numeric,
  rows_inserted     integer not null default 0,
  rows_updated      integer not null default 0,
  rows_deleted      integer not null default 0,
  rows_skipped      integer not null default 0,
  validation_errors integer not null default 0,
  metrics           jsonb not null default '{}'::jsonb
);
create index if not exists sync_runs_started_idx
  on knowledge.sync_runs (started_at desc);

alter table knowledge.sync_runs enable row level security;
drop policy if exists "sync runs admin read" on knowledge.sync_runs;
create policy "sync runs admin read"
  on knowledge.sync_runs for select
  using (public.is_valueweave_admin());

